#region Comments
/* Conversion Comments
   ************************************************************
   **   MODERN SYSTEMS INC.  COPYRIGHT 2000-2021
   **   DB-SHUTTLE COBOL to C# Conversion
   ************************************************************
   ** INIT   *  INITIAL VERSION   *  2021-11-16 12:36:06 PM
   **        *   FROM COBOL PGM   :  SWEXGE04
   **        *   FROM CANISTER    :  SR.CAECSES.PROD.LIBR.SOURCE.PDS
   ************************************************************ */

/* Original Program Identification Comments
   **************************************************************
                       SOURCE CODE GENERATED BY
                              COOL:GEN
               COPYRIGHT 2001, STERLING SOFTWARE, INC.
       NAME: CAB_SUBMIT_JOB_TO_JES            DATE: 2001/01/25
       TARGET OS:   MVS                       TIME: 07:57:46
       TARGET DBMS: DB2                       USER: SWSRGAD
       GENERATION OPTIONS:
       DEBUG TRACE OPTION NOT SELECTED
       DATA MODELING CONSTRAINT ENFORCEMENT NOT SELECTED
       OPTIMIZED IMPORT VIEW INITIALIZATION SELECTED
       HIGH PERFORMANCE VIEW PASSING NOT SELECTED
       NO LAST-STATEMENT-NUM EXECUTION SELECTED
       ENFORCE DEFAULT VALUES WITH DBMS NOT SELECTED
       INIT UNSPECIFIED OPTIONAL FIELDS TO NULL NOT SELECTED
   **************************************************************
*/
#endregion
#region Using Directives
using System;
using System.Data;
using System.Collections.Generic;
using MDSY.Framework.UI.Angular;
using MDSY.Framework.Control.CICS;
using MDSY.Framework.Buffer;
using MDSY.Framework.Buffer.BaseClasses;
using MDSY.Framework.Buffer.Interfaces;
using MDSY.Framework.Buffer.Common;
using MDSY.Framework.Core;
using MDSY.Framework.Data.SQL;
using MDSY.Framework.Interfaces;
#endregion

namespace GOV.KS.DCF.CSS.Online.BL
{
    #region Working Storage Class
    internal class SWEXGE04_ws : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string WorkingStorage = "SWEXGE04_ws_WorkingStorage";
            internal const string CICS_ITEMS = "CICS_ITEMS";
            internal const string QUEID = "QUEID";
            internal const string SUB1 = "SUB1";
            internal const string JCL_LENGTH = "JCL_LENGTH";
            internal const string OUTJCL = "OUTJCL";
            internal const string ADIM1 = "ADIM1";
            internal const string ADIM2 = "ADIM2";
            internal const string ADIM3 = "ADIM3";
            internal const string IMPORT_GROUP_0001FL = "IMPORT_GROUP_0001FL";
            internal const string IMPORT_GROUP_0001PS = "IMPORT_GROUP_0001PS";
            internal const string IMPORT_GROUP_0001RF = "IMPORT_GROUP_0001RF";
            internal const string IMPORT_GROUP_0001MM = "IMPORT_GROUP_0001MM";
        }
        #endregion

        #region Direct-access element properties
        public IGroup CICS_ITEMS { get { return GetElementByName<IGroup>(Names.CICS_ITEMS); } }
        public IField QUEID { get { return GetElementByName<IField>(Names.QUEID); } }
        public IField SUB1 { get { return GetElementByName<IField>(Names.SUB1); } }
        public IField JCL_LENGTH { get { return GetElementByName<IField>(Names.JCL_LENGTH); } }
        public IField OUTJCL { get { return GetElementByName<IField>(Names.OUTJCL); } }
        public IField ADIM1 { get { return GetElementByName<IField>(Names.ADIM1); } }
        public IField ADIM2 { get { return GetElementByName<IField>(Names.ADIM2); } }
        public IField ADIM3 { get { return GetElementByName<IField>(Names.ADIM3); } }
        public IField IMPORT_GROUP_0001FL { get { return GetElementByName<IField>(Names.IMPORT_GROUP_0001FL); } }
        public IField IMPORT_GROUP_0001PS { get { return GetElementByName<IField>(Names.IMPORT_GROUP_0001PS); } }
        public IField IMPORT_GROUP_0001RF { get { return GetElementByName<IField>(Names.IMPORT_GROUP_0001RF); } }
        public IField IMPORT_GROUP_0001MM { get { return GetElementByName<IField>(Names.IMPORT_GROUP_0001MM); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the WorkingStorage IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {

            recordDef.CreateNewGroup(Names.CICS_ITEMS, (CICS_ITEMS) =>
           {
               CICS_ITEMS.CreateNewField(Names.QUEID, FieldType.String, 4, "SINT");
               CICS_ITEMS.CreateNewField(Names.SUB1, FieldType.CompShort, 4, 0);
               CICS_ITEMS.CreateNewField(Names.JCL_LENGTH, FieldType.CompShort, 4, 80);
           });
            recordDef.CreateNewField(Names.OUTJCL, FieldType.String, 80, SPACES);

            recordDef.CreateNewGroup("FILLER", (FILLER) =>
           {
               FILLER.CreateNewField(Names.ADIM1, FieldType.CompInt, 8);
               FILLER.CreateNewField(Names.ADIM2, FieldType.CompInt, 8);
               FILLER.CreateNewField(Names.ADIM3, FieldType.CompInt, 8);
           });

            recordDef.CreateNewGroup("FILLER_d2", (FILLER_d2) =>
           {
               FILLER_d2.CreateNewField(Names.IMPORT_GROUP_0001FL, FieldType.String, 1);
               FILLER_d2.CreateNewField(Names.IMPORT_GROUP_0001PS, FieldType.CompShort, 4);
               FILLER_d2.CreateNewField(Names.IMPORT_GROUP_0001RF, FieldType.String, 1);
               FILLER_d2.CreateNewField(Names.IMPORT_GROUP_0001MM, FieldType.CompInt, 9, 200);
           });

        }

        protected override string GetRecordName()
        {
            return Names.WorkingStorage;
        }
        #endregion

    }
    #endregion Working Storage Class

    #region Linkage Section Class
    internal class SWEXGE04_ls : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string LinkageSection = "SWEXGE04_ls_LinkageSection";
            internal const string PSMGR_EAB_DATA = "PSMGR_EAB_DATA";
            internal const string PSMGR_EABPCB_CNT = "PSMGR_EABPCB_CNT";
            internal const string PSMGR_EABPCB_ENTRY = "PSMGR_EABPCB_ENTRY";
            internal const string PSMGR_EABPCB_ADR = "PSMGR_EABPCB_ADR";
            internal const string W_IA = "W_IA";
            internal const string A_0363083911_IA = "A_0363083911_IA";
            internal const string IMPORT_GROUP_0001RG = "IMPORT_GROUP_0001RG";
            internal const string IMPORT_GROUP_0001MA = "IMPORT_GROUP_0001MA";
            internal const string IMPORT_GROUP_0001MX = "IMPORT_GROUP_0001MX";
            internal const string IMPORT_GROUP_0001 = "IMPORT_GROUP_0001";
            internal const string IMPORT_GROUP_0001AC = "IMPORT_GROUP_0001AC";
            internal const string IMPORT_GRP_0001EV = "IMPORT_GRP_0001EV";
            internal const string JCL_TEMPLATE_0001ET = "JCL_TEMPLATE_0001ET";
            internal const string RECORD_TEXT_0001 = "RECORD_TEXT_0001";
            internal const string RECORD_TEXT_0001XX = "RECORD_TEXT_0001XX";
            internal const string W_OA = "W_OA";
            internal const string A_0001114214_OA = "A_0001114214_OA";
            internal const string EXPORT_0002EV = "EXPORT_0002EV";
            internal const string EXTERNAL_0002ET = "EXTERNAL_0002ET";
            internal const string NUMERIC_RETURN_CODE_0002 = "NUMERIC_RETURN_CODE_0002";
            internal const string NUMERIC_RETURN_CODE_0002XX = "NUMERIC_RETURN_CODE_0002XX";
        }
        #endregion

        #region Direct-access element properties
        public IGroup PSMGR_EAB_DATA { get { return GetElementByName<IGroup>(Names.PSMGR_EAB_DATA); } }
        public IField PSMGR_EABPCB_CNT { get { return GetElementByName<IField>(Names.PSMGR_EABPCB_CNT); } }
        public IArrayElementAccessor<IGroup> PSMGR_EABPCB_ENTRY { get { return GetArrayElementAccessor<IGroup>(Names.PSMGR_EABPCB_ENTRY); } }
        public IArrayElementAccessor<IField> PSMGR_EABPCB_ADR { get { return GetArrayElementAccessor<IField>(Names.PSMGR_EABPCB_ADR); } }
        public IGroup W_IA { get { return GetElementByName<IGroup>(Names.W_IA); } }
        public IGroup A_0363083911_IA { get { return GetElementByName<IGroup>(Names.A_0363083911_IA); } }
        public IGroup IMPORT_GROUP_0001RG { get { return GetElementByName<IGroup>(Names.IMPORT_GROUP_0001RG); } }
        public IField IMPORT_GROUP_0001MA { get { return GetElementByName<IField>(Names.IMPORT_GROUP_0001MA); } }
        public IField IMPORT_GROUP_0001MX { get { return GetElementByName<IField>(Names.IMPORT_GROUP_0001MX); } }
        public IArrayElementAccessor<IGroup> IMPORT_GROUP_0001 { get { return GetArrayElementAccessor<IGroup>(Names.IMPORT_GROUP_0001); } }
        public IArrayElementAccessor<IField> IMPORT_GROUP_0001AC { get { return GetArrayElementAccessor<IField>(Names.IMPORT_GROUP_0001AC); } }
        public IArrayElementAccessor<IGroup> IMPORT_GRP_0001EV { get { return GetArrayElementAccessor<IGroup>(Names.IMPORT_GRP_0001EV); } }
        public IArrayElementAccessor<IGroup> JCL_TEMPLATE_0001ET { get { return GetArrayElementAccessor<IGroup>(Names.JCL_TEMPLATE_0001ET); } }
        public IArrayElementAccessor<IField> RECORD_TEXT_0001 { get { return GetArrayElementAccessor<IField>(Names.RECORD_TEXT_0001); } }
        public IArrayElementAccessor<IField> RECORD_TEXT_0001XX { get { return GetArrayElementAccessor<IField>(Names.RECORD_TEXT_0001XX); } }
        public IGroup W_OA { get { return GetElementByName<IGroup>(Names.W_OA); } }
        public IGroup A_0001114214_OA { get { return GetElementByName<IGroup>(Names.A_0001114214_OA); } }
        public IGroup EXPORT_0002EV { get { return GetElementByName<IGroup>(Names.EXPORT_0002EV); } }
        public IGroup EXTERNAL_0002ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_0002ET); } }
        public IField NUMERIC_RETURN_CODE_0002 { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0002); } }
        public IField NUMERIC_RETURN_CODE_0002XX { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0002XX); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the LinkageSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {

            recordDef.CreateNewGroup(Names.PSMGR_EAB_DATA, (PSMGR_EAB_DATA) =>
           {
               PSMGR_EAB_DATA.CreateNewField(Names.PSMGR_EABPCB_CNT, FieldType.CompInt, 9);
               PSMGR_EAB_DATA.CreateNewGroupArray(Names.PSMGR_EABPCB_ENTRY, 255, (PSMGR_EABPCB_ENTRY) =>
               {
                   PSMGR_EABPCB_ENTRY.CreateNewField(Names.PSMGR_EABPCB_ADR, FieldType.CompInt, 9);
               });
           });

            recordDef.CreateNewGroup(Names.W_IA, (W_IA) =>
           {
               W_IA.CreateNewGroup(Names.A_0363083911_IA, (A_0363083911_IA) =>
               {
                   A_0363083911_IA.CreateNewGroup(Names.IMPORT_GROUP_0001RG, (IMPORT_GROUP_0001RG) =>
                   {

                       IField IMPORT_GROUP_0001MA_local = IMPORT_GROUP_0001RG.CreateNewField(Names.IMPORT_GROUP_0001MA, FieldType.SignedNumeric, 4);
                       IMPORT_GROUP_0001RG.CreateNewFieldRedefine(Names.IMPORT_GROUP_0001MX, FieldType.String, IMPORT_GROUP_0001MA_local, 4);
                       IMPORT_GROUP_0001RG.CreateNewGroupArray(Names.IMPORT_GROUP_0001, 200, (IMPORT_GROUP_0001) =>
                       {
                           IMPORT_GROUP_0001.CreateNewField(Names.IMPORT_GROUP_0001AC, FieldType.String, 1);
                           IMPORT_GROUP_0001.CreateNewGroup(Names.IMPORT_GRP_0001EV, (IMPORT_GRP_0001EV) =>
                           {
                               IMPORT_GRP_0001EV.CreateNewGroup(Names.JCL_TEMPLATE_0001ET, (JCL_TEMPLATE_0001ET) =>
                               {

                                   IField RECORD_TEXT_0001_local = JCL_TEMPLATE_0001ET.CreateNewField(Names.RECORD_TEXT_0001, FieldType.String, 80);
                                   JCL_TEMPLATE_0001ET.CreateNewFieldRedefine(Names.RECORD_TEXT_0001XX, FieldType.String, RECORD_TEXT_0001_local, 80);
                               });
                           });
                       });
                   });
               });
           });

            recordDef.CreateNewGroup(Names.W_OA, (W_OA) =>
           {
               W_OA.CreateNewGroup(Names.A_0001114214_OA, (A_0001114214_OA) =>
               {
                   A_0001114214_OA.CreateNewGroup(Names.EXPORT_0002EV, (EXPORT_0002EV) =>
                   {
                       EXPORT_0002EV.CreateNewGroup(Names.EXTERNAL_0002ET, (EXTERNAL_0002ET) =>
                       {

                           IField NUMERIC_RETURN_CODE_0002_local = EXTERNAL_0002ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0002, FieldType.SignedNumeric, 2);
                           EXTERNAL_0002ET.CreateNewFieldRedefine(Names.NUMERIC_RETURN_CODE_0002XX, FieldType.String, NUMERIC_RETURN_CODE_0002_local, 2);
                       });
                   });
               });
           });

        }

        protected override string GetRecordName()
        {
            return Names.LinkageSection;
        }
        #endregion

        public void SetPassedParameters(object[] args)
        {
            SetPassedParm(W_IA, args, 0);
            SetPassedParm(W_OA, args, 1);
            SetPassedParm(PSMGR_EAB_DATA, args, 2);
        }


        public void UpdateReturnParameters(object[] args)
        {
            SetReturnParm(W_IA, args, 0);
            SetReturnParm(W_OA, args, 1);
            SetReturnParm(PSMGR_EAB_DATA, args, 2);
        }
    }
    #endregion Linkage Section Class

    #region Business Logic Class
    public class SWEXGE04 : OnlineProgramBase
    {

        #region Public Constructors
        public SWEXGE04()
            : base()
        {
            this.ProgramName = "SWEXGE04";

            WS = new SWEXGE04_ws();
            LS = new SWEXGE04_ls();
        }

        public SWEXGE04(OnlineControl controlData) : base(controlData)
        {
            this.ProgramName = "SWEXGE04";

            WS = new SWEXGE04_ws();
            LS = new SWEXGE04_ls();
        }

        #endregion

        #region Private Fields


        //==== Working Storage Data Class ========================================
        private SWEXGE04_ws WS;

        //==== Linkage Section Data Class ========================================
        private SWEXGE04_ls LS;
        #endregion

        #region Public Methods
        //========================================================================
        //==== RunMain Entry Point Method ========================================
        //========================================================================
        public override int ExecuteMain(params object[] args)                                              //COBOL==> PROCEDURE DIVISION USING W-IA , W-OA , PSMGR-EAB-DATA.
        {
            try
            {
                WS.Initialize();
                LS.SetPassedParameters(args);
                SetData();
                RunMain();
                LS.UpdateReturnParameters(args);
                return Return_Code.AsInt();
            }
            catch (Exception ex)
            {
                Control.ReturnException(ex);
                return 12;
            }
            finally
            {
                Data.CloseConnection();
            }
        }
        #endregion

        #region Private Methods

        private void SetData()
        {
            LS.InitializeWithLowValues();
            WS.InitializeWithLowValues();
        }

        private void RunMain()
        {
            string returnMethod = "Main";
            // Execute Procedure Division Logic
            M_MAIN_0363083908(returnMethod);
        }
        /// <summary>
        /// Method M_MAIN_0363083908
        /// </summary>
        private void M_MAIN_0363083908(string returnMethod = "")
        {
            M_PARA_0363083908_INIT("M_PARA_0363083908_INIT_EXIT"); if (Control.ExitProgram) { return; }           //COBOL==> PERFORM PARA-0363083908-INIT THRU PARA-0363083908-INIT-EXIT
            M_PARA_0363083908("M_PARA_0363083908_EXIT"); if (Control.ExitProgram) { return; }                     //COBOL==> PERFORM PARA-0363083908 THRU PARA-0363083908-EXIT
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_PARA_0363083908
        /// </summary>
        private void M_PARA_0363083908(string returnMethod = "")
        {
            //COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
            //COMMENT:    USER-WRITTEN CODE SHOULD BE INSERTED HERE
            //COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
            SetHandleCondtions(HandleCondition.IOERR, "M_IO_ERROR", HandleCondition.INVREQ, "M_INVALID_REQUEST", HandleCondition.TRANSIDERR, "M_TRANSID_ERROR", HandleCondition.LENGERR, "M_LENGTH_ERROR", HandleCondition.NOTOPEN, "M_NOTOPEN_ERROR", HandleCondition.QIDERR, "M_QIDERR_ERROR");  //COBOL==> EXEC CICS HANDLE CONDITION IOERR ( IO-ERROR ) INVREQ ( INVALID-REQUEST ) TRANSIDERR ( TRANSID-ERROR ) LENGERR ( LENGTH-ERROR ) NOTOPEN ( NOTOPEN-ERROR ) QIDERR ( QIDERR-ERROR ) END-EXEC.
            Control.SetResourceLock(WS.QUEID, WS.QUEID.LengthInBuffer);                                         //COBOL==> EXEC CICS ENQ RESOURCE ( QUEID ) END-EXEC.
            for (WS.SUB1.SetValue(1); (!(WS.SUB1.IsGreaterThan(LS.IMPORT_GROUP_0001MA))); WS.SUB1.Add(1))      //COBOL==> PERFORM VARYING SUB1 FROM 1 BY 1 UNTIL SUB1 > IMPORT-GROUP-0001MA
            {
                WS.OUTJCL.SetValue(LS.RECORD_TEXT_0001[WS.SUB1.AsInt()]);                                           //COBOL==> MOVE RECORD-TEXT-0001 ( SUB1 ) TO OUTJCL
                Control.WriteTransientQueue(WS.QUEID, WS.OUTJCL, WS.JCL_LENGTH); if (CheckHandleConditions(returnMethod)) { return; }  //COBOL==> EXEC CICS WRITEQ TD QUEUE ( QUEID ) FROM ( OUTJCL ) LENGTH ( JCL-LENGTH ) END-EXEC
            }                                                                                                   //COBOL==> END-PERFORM.
            Control.RemoveResourceLock(WS.QUEID, WS.QUEID.LengthInBuffer);                                      //COBOL==> EXEC CICS DEQ RESOURCE ( QUEID ) END-EXEC.
            if (returnMethod != "" && returnMethod != "M_PARA_0363083908") { M_PARA_0363083908_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0363083908_EXIT
        /// </summary>
        private void M_PARA_0363083908_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0363083908_EXIT") { return; }                                           //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0363083908_EXIT") { M_PARA_0363083908_INIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0363083908_INIT
        /// </summary>
        private void M_PARA_0363083908_INIT(string returnMethod = "")
        {
            WS.IMPORT_GROUP_0001PS.SetValueWithZeroes();                                                        //COBOL==> MOVE ZERO TO IMPORT-GROUP-0001PS
            LS.EXPORT_0002EV.ResetToInitialValue();                                                             //COBOL==> INITIALIZE EXPORT-0002EV .
            if (returnMethod != "" && returnMethod != "M_PARA_0363083908_INIT") { M_PARA_0363083908_INIT_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0363083908_INIT_EXIT
        /// </summary>
        private void M_PARA_0363083908_INIT_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0363083908_INIT_EXIT") { return; }                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0363083908_INIT_EXIT") { M_IO_ERROR(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_IO_ERROR
        /// </summary>
        private void M_IO_ERROR(string returnMethod = "")
        {
            LS.NUMERIC_RETURN_CODE_0002.SetValue(1);                                                            //COBOL==> MOVE 1 TO NUMERIC-RETURN-CODE-0002.
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_INVALID_REQUEST
        /// </summary>
        private void M_INVALID_REQUEST(string returnMethod = "")
        {
            LS.NUMERIC_RETURN_CODE_0002.SetValue(2);                                                            //COBOL==> MOVE 2 TO NUMERIC-RETURN-CODE-0002.
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_TRANSID_ERROR
        /// </summary>
        private void M_TRANSID_ERROR(string returnMethod = "")
        {
            LS.NUMERIC_RETURN_CODE_0002.SetValue(3);                                                            //COBOL==> MOVE 3 TO NUMERIC-RETURN-CODE-0002.
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_LENGTH_ERROR
        /// </summary>
        private void M_LENGTH_ERROR(string returnMethod = "")
        {
            LS.NUMERIC_RETURN_CODE_0002.SetValue(4);                                                            //COBOL==> MOVE 4 TO NUMERIC-RETURN-CODE-0002.
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_NOTOPEN_ERROR
        /// </summary>
        private void M_NOTOPEN_ERROR(string returnMethod = "")
        {
            LS.NUMERIC_RETURN_CODE_0002.SetValue(5);                                                            //COBOL==> MOVE 5 TO NUMERIC-RETURN-CODE-0002.
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_QIDERR_ERROR
        /// </summary>
        private void M_QIDERR_ERROR(string returnMethod = "")
        {
            LS.NUMERIC_RETURN_CODE_0002.SetValue(6);                                                            //COBOL==> MOVE 6 TO NUMERIC-RETURN-CODE-0002.
        }
        #endregion
    }
    #endregion
}
