#region Comments
/* Conversion Comments
   ************************************************************
   **   MODERN SYSTEMS INC.  COPYRIGHT 2000-2021
   **   DB-SHUTTLE COBOL to C# Conversion
   ************************************************************
   ** INIT   *  INITIAL VERSION   *  2021-12-07 03:12:44 PM
   **        *   FROM COBOL PGM   :  SWEXFW00
   **        *   FROM CANISTER    :  SR.CAECSES.PROD.LIBR.SOURCE.PDS
   ************************************************************ */

/* Original Program Identification Comments
   **************************************************************
                       SOURCE CODE GENERATED BY
                   INFORMATION ENGINEERING FACILITY (TM)
                       TEXAS INSTRUMENTS INC.
                COPYRIGHT (C) TEXAS INSTRUMENTS INC. 1997
       NAME: FN_EAB_COLL_FORMAT_DETAIL_LINE   DATE: 97/10/23
       TARGET OS:   MVS                       TIME: 10:07:47
       TARGET DBMS: DB2                       USER: SWMTRBM
       GENERATION OPTIONS:
       DEBUG TRACE OPTION NOT SELECTED
       DATA MODELING CONSTRAINT ENFORCEMENT NOT SELECTED
       OPTIMIZED IMPORT VIEW INITIALIZATION SELECTED
   **************************************************************
*/
#endregion
#region Using Directives
using System;
using System.Data;
using System.Collections.Generic;
using MDSY.Framework.IO.Common;
using MDSY.Framework.Buffer;
using MDSY.Framework.Buffer.BaseClasses;
using MDSY.Framework.Buffer.Interfaces;
using MDSY.Framework.Buffer.Common;
using MDSY.Framework.Core;
using MDSY.Framework.Data.SQL;
using MDSY.Framework.Interfaces;
#endregion

namespace GOV.KS.DCF.CSS.Common.BL
{
    #region Working Storage Class
    internal class SWEXFW00_ws : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string WorkingStorage = "SWEXFW00_ws_WorkingStorage";
            internal const string FUNC_0329249676_ESC_FLAG = "FUNC_0329249676_ESC_FLAG";
            internal const string WS_DATE_FORMAT = "WS_DATE_FORMAT";
            internal const string WS_DATE_YYYY = "WS_DATE_YYYY";
            internal const string WS_DATE_MM = "WS_DATE_MM";
            internal const string WS_DATE_DD = "WS_DATE_DD";
            internal const string WS_DATE_FORMATTED = "WS_DATE_FORMATTED";
            internal const string WS_NEW_DATE = "WS_NEW_DATE";
            internal const string WS_DATE_MM_NEW = "WS_DATE_MM_NEW";
            internal const string WS_DATE_DD_NEW = "WS_DATE_DD_NEW";
            internal const string WS_DATE_YYYY_NEW = "WS_DATE_YYYY_NEW";
            internal const string WS_DATE_FORMAT_NEW = "WS_DATE_FORMAT_NEW";
            internal const string WS_DATE_FORMATTED_A = "WS_DATE_FORMATTED_A";
            internal const string WS_NEW_DATE_A = "WS_NEW_DATE_A";
            internal const string WS_DATE_MM_NEW_A = "WS_DATE_MM_NEW_A";
            internal const string WS_DATE_DD_NEW_A = "WS_DATE_DD_NEW_A";
            internal const string WS_DATE_YY_NEW_A = "WS_DATE_YY_NEW_A";
            internal const string WS_DATE_FORMAT_NEW_A = "WS_DATE_FORMAT_NEW_A";
            internal const string WS_ACTIVITY_LINE = "WS_ACTIVITY_LINE";
            internal const string WS_DEBT_TYPE = "WS_DEBT_TYPE";
            internal const string WS_DEBT_DUE_DATE = "WS_DEBT_DUE_DATE";
            internal const string WS_PROGRAM_CODE = "WS_PROGRAM_CODE";
            internal const string WS_DIST_PGM_STATE = "WS_DIST_PGM_STATE";
            internal const string WS_INTERSTATE_IND = "WS_INTERSTATE_IND";
            internal const string WS_FORMATTED_NAME = "WS_FORMATTED_NAME";
            internal const string WS_PSJ_IND = "WS_PSJ_IND";
            internal const string WS_PROC_DATE = "WS_PROC_DATE";
            internal const string WS_AMOUNT = "WS_AMOUNT";
            internal const string WS_MAN_AUTO_IND = "WS_MAN_AUTO_IND";
            internal const string WS_WORKER_ID = "WS_WORKER_ID";
            internal const string WS_COLLECTION_LINE = "WS_COLLECTION_LINE";
            internal const string WS_RECEIPT_DATE = "WS_RECEIPT_DATE";
            internal const string WS_SOURCE_TYPE = "WS_SOURCE_TYPE";
            internal const string WS_COLLECT_DATE = "WS_COLLECT_DATE";
            internal const string WS_COLLECT_AMT = "WS_COLLECT_AMT";
            internal const string WS_UNDISTR_AMT = "WS_UNDISTR_AMT";
            internal const string WS_REASON_CODE = "WS_REASON_CODE";
            internal const string WS_REFUND_AMT = "WS_REFUND_AMT";
            internal const string WS_ADJUSTMENT_LINE = "WS_ADJUSTMENT_LINE";
            internal const string WS_ADJ_DATE = "WS_ADJ_DATE";
            internal const string WS_ADJ_RSN_CODE = "WS_ADJ_RSN_CODE";
            internal const string WS_ADJ_AMT = "WS_ADJ_AMT";
        }
        #endregion

        #region Direct-access element properties
        public IField FUNC_0329249676_ESC_FLAG { get { return GetElementByName<IField>(Names.FUNC_0329249676_ESC_FLAG); } }
        public IGroup WS_DATE_FORMAT { get { return GetElementByName<IGroup>(Names.WS_DATE_FORMAT); } }
        public IField WS_DATE_YYYY { get { return GetElementByName<IField>(Names.WS_DATE_YYYY); } }
        public IField WS_DATE_MM { get { return GetElementByName<IField>(Names.WS_DATE_MM); } }
        public IField WS_DATE_DD { get { return GetElementByName<IField>(Names.WS_DATE_DD); } }
        public IGroup WS_DATE_FORMATTED { get { return GetElementByName<IGroup>(Names.WS_DATE_FORMATTED); } }
        public IGroup WS_NEW_DATE { get { return GetElementByName<IGroup>(Names.WS_NEW_DATE); } }
        public IField WS_DATE_MM_NEW { get { return GetElementByName<IField>(Names.WS_DATE_MM_NEW); } }
        public IField WS_DATE_DD_NEW { get { return GetElementByName<IField>(Names.WS_DATE_DD_NEW); } }
        public IField WS_DATE_YYYY_NEW { get { return GetElementByName<IField>(Names.WS_DATE_YYYY_NEW); } }
        public IField WS_DATE_FORMAT_NEW { get { return GetElementByName<IField>(Names.WS_DATE_FORMAT_NEW); } }
        public IGroup WS_DATE_FORMATTED_A { get { return GetElementByName<IGroup>(Names.WS_DATE_FORMATTED_A); } }
        public IGroup WS_NEW_DATE_A { get { return GetElementByName<IGroup>(Names.WS_NEW_DATE_A); } }
        public IField WS_DATE_MM_NEW_A { get { return GetElementByName<IField>(Names.WS_DATE_MM_NEW_A); } }
        public IField WS_DATE_DD_NEW_A { get { return GetElementByName<IField>(Names.WS_DATE_DD_NEW_A); } }
        public IField WS_DATE_YY_NEW_A { get { return GetElementByName<IField>(Names.WS_DATE_YY_NEW_A); } }
        public IField WS_DATE_FORMAT_NEW_A { get { return GetElementByName<IField>(Names.WS_DATE_FORMAT_NEW_A); } }
        public IGroup WS_ACTIVITY_LINE { get { return GetElementByName<IGroup>(Names.WS_ACTIVITY_LINE); } }
        public IField WS_DEBT_TYPE { get { return GetElementByName<IField>(Names.WS_DEBT_TYPE); } }
        public IField WS_DEBT_DUE_DATE { get { return GetElementByName<IField>(Names.WS_DEBT_DUE_DATE); } }
        public IField WS_PROGRAM_CODE { get { return GetElementByName<IField>(Names.WS_PROGRAM_CODE); } }
        public IField WS_DIST_PGM_STATE { get { return GetElementByName<IField>(Names.WS_DIST_PGM_STATE); } }
        public IField WS_INTERSTATE_IND { get { return GetElementByName<IField>(Names.WS_INTERSTATE_IND); } }
        public IField WS_FORMATTED_NAME { get { return GetElementByName<IField>(Names.WS_FORMATTED_NAME); } }
        public IField WS_PSJ_IND { get { return GetElementByName<IField>(Names.WS_PSJ_IND); } }
        public IField WS_PROC_DATE { get { return GetElementByName<IField>(Names.WS_PROC_DATE); } }
        public IField WS_AMOUNT { get { return GetElementByName<IField>(Names.WS_AMOUNT); } }
        public IField WS_MAN_AUTO_IND { get { return GetElementByName<IField>(Names.WS_MAN_AUTO_IND); } }
        public IField WS_WORKER_ID { get { return GetElementByName<IField>(Names.WS_WORKER_ID); } }
        public IGroup WS_COLLECTION_LINE { get { return GetElementByName<IGroup>(Names.WS_COLLECTION_LINE); } }
        public IField WS_RECEIPT_DATE { get { return GetElementByName<IField>(Names.WS_RECEIPT_DATE); } }
        public IField WS_SOURCE_TYPE { get { return GetElementByName<IField>(Names.WS_SOURCE_TYPE); } }
        public IField WS_COLLECT_DATE { get { return GetElementByName<IField>(Names.WS_COLLECT_DATE); } }
        public IField WS_COLLECT_AMT { get { return GetElementByName<IField>(Names.WS_COLLECT_AMT); } }
        public IField WS_UNDISTR_AMT { get { return GetElementByName<IField>(Names.WS_UNDISTR_AMT); } }
        public IField WS_REASON_CODE { get { return GetElementByName<IField>(Names.WS_REASON_CODE); } }
        public IField WS_REFUND_AMT { get { return GetElementByName<IField>(Names.WS_REFUND_AMT); } }
        public IGroup WS_ADJUSTMENT_LINE { get { return GetElementByName<IGroup>(Names.WS_ADJUSTMENT_LINE); } }
        public IField WS_ADJ_DATE { get { return GetElementByName<IField>(Names.WS_ADJ_DATE); } }
        public IField WS_ADJ_RSN_CODE { get { return GetElementByName<IField>(Names.WS_ADJ_RSN_CODE); } }
        public IField WS_ADJ_AMT { get { return GetElementByName<IField>(Names.WS_ADJ_AMT); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the WorkingStorage IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.FUNC_0329249676_ESC_FLAG, FieldType.String, 1);

            recordDef.CreateNewGroup(Names.WS_DATE_FORMAT, (WS_DATE_FORMAT) =>
           {
               WS_DATE_FORMAT.CreateNewField(Names.WS_DATE_YYYY, FieldType.UnsignedNumeric, 4, ZERO);
               WS_DATE_FORMAT.CreateNewField(Names.WS_DATE_MM, FieldType.UnsignedNumeric, 2, ZERO);
               WS_DATE_FORMAT.CreateNewField(Names.WS_DATE_DD, FieldType.UnsignedNumeric, 2, ZERO);
           });

            recordDef.CreateNewGroup(Names.WS_DATE_FORMATTED, (WS_DATE_FORMATTED) =>
           {
               IGroup WS_NEW_DATE_local = (IGroup)WS_DATE_FORMATTED.CreateNewGroup(Names.WS_NEW_DATE, (WS_NEW_DATE) =>
               {
                   WS_NEW_DATE.CreateNewField(Names.WS_DATE_MM_NEW, FieldType.UnsignedNumeric, 2, ZERO);
                   WS_NEW_DATE.CreateNewField(Names.WS_DATE_DD_NEW, FieldType.UnsignedNumeric, 2, ZERO);
                   WS_NEW_DATE.CreateNewField(Names.WS_DATE_YYYY_NEW, FieldType.UnsignedNumeric, 4, ZERO);
               });
               WS_DATE_FORMATTED.CreateNewFieldRedefine(Names.WS_DATE_FORMAT_NEW, FieldType.String, WS_NEW_DATE_local, 8);
           });

            recordDef.CreateNewGroup(Names.WS_DATE_FORMATTED_A, (WS_DATE_FORMATTED_A) =>
           {
               IGroup WS_NEW_DATE_A_local = (IGroup)WS_DATE_FORMATTED_A.CreateNewGroup(Names.WS_NEW_DATE_A, (WS_NEW_DATE_A) =>
               {
                   WS_NEW_DATE_A.CreateNewField(Names.WS_DATE_MM_NEW_A, FieldType.UnsignedNumeric, 2, ZERO);
                   WS_NEW_DATE_A.CreateNewField(Names.WS_DATE_DD_NEW_A, FieldType.UnsignedNumeric, 2, ZERO);
                   WS_NEW_DATE_A.CreateNewField(Names.WS_DATE_YY_NEW_A, FieldType.UnsignedNumeric, 2, ZERO);
               });
               WS_DATE_FORMATTED_A.CreateNewFieldRedefine(Names.WS_DATE_FORMAT_NEW_A, FieldType.String, WS_NEW_DATE_A_local, 6);
           });

            recordDef.CreateNewGroup(Names.WS_ACTIVITY_LINE, (WS_ACTIVITY_LINE) =>
           {
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_DEBT_TYPE, FieldType.String, 7);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_DEBT_DUE_DATE, FieldType.String, 6);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_PROGRAM_CODE, FieldType.String, 3);
               WS_ACTIVITY_LINE.CreateNewFillerField(FieldType.String, 1, "-");
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_DIST_PGM_STATE, FieldType.String, 2);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_INTERSTATE_IND, FieldType.String, 1);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_FORMATTED_NAME, FieldType.String, 21);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_PSJ_IND, FieldType.String, 1);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_PROC_DATE, FieldType.String, 6);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_AMOUNT, FieldType.NumericEdited, "ZZZZ9.99", 8, null, 2);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_MAN_AUTO_IND, FieldType.String, 1);
               WS_ACTIVITY_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_ACTIVITY_LINE.CreateNewField(Names.WS_WORKER_ID, FieldType.String, 8);
           });

            recordDef.CreateNewGroup(Names.WS_COLLECTION_LINE, (WS_COLLECTION_LINE) =>
           {
               WS_COLLECTION_LINE.CreateNewField(Names.WS_RECEIPT_DATE, FieldType.String, 8);
               WS_COLLECTION_LINE.CreateNewFillerField(3, FillWith.Hashes);
               WS_COLLECTION_LINE.CreateNewField(Names.WS_SOURCE_TYPE, FieldType.String, 10);
               WS_COLLECTION_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_COLLECTION_LINE.CreateNewField(Names.WS_COLLECT_DATE, FieldType.String, 8);
               WS_COLLECTION_LINE.CreateNewFillerField(2, FillWith.Hashes);
               WS_COLLECTION_LINE.CreateNewField(Names.WS_COLLECT_AMT, FieldType.NumericEdited, "ZZZZZZ9.99", 10, null, 2);
               WS_COLLECTION_LINE.CreateNewFillerField(1, FillWith.Hashes);
               WS_COLLECTION_LINE.CreateNewField(Names.WS_UNDISTR_AMT, FieldType.NumericEdited, "ZZZZZZ9.99", 10, null, 2);
               WS_COLLECTION_LINE.CreateNewFillerField(2, FillWith.Hashes);
               WS_COLLECTION_LINE.CreateNewField(Names.WS_REASON_CODE, FieldType.String, 10);
               WS_COLLECTION_LINE.CreateNewFillerField(2, FillWith.Hashes);
               WS_COLLECTION_LINE.CreateNewField(Names.WS_REFUND_AMT, FieldType.NumericEdited, "ZZZZZ9.99", 9, null, 2);
           });

            recordDef.CreateNewGroup(Names.WS_ADJUSTMENT_LINE, (WS_ADJUSTMENT_LINE) =>
           {
               WS_ADJUSTMENT_LINE.CreateNewFillerField(3, FillWith.Hashes);
               WS_ADJUSTMENT_LINE.CreateNewField(Names.WS_ADJ_DATE, FieldType.String, 8);
               WS_ADJUSTMENT_LINE.CreateNewFillerField(13, FillWith.Hashes);
               WS_ADJUSTMENT_LINE.CreateNewField(Names.WS_ADJ_RSN_CODE, FieldType.String, 8);
               WS_ADJUSTMENT_LINE.CreateNewFillerField(23, FillWith.Hashes);
               WS_ADJUSTMENT_LINE.CreateNewField(Names.WS_ADJ_AMT, FieldType.NumericEdited, "ZZZZZZ9.99-", 11, null, 2);
               WS_ADJUSTMENT_LINE.CreateNewFillerField(13, FillWith.Hashes);
           });

        }

        protected override string GetRecordName()
        {
            return Names.WorkingStorage;
        }
        #endregion

    }
    #endregion Working Storage Class

    #region Linkage Section Class
    internal class SWEXFW00_ls : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string LinkageSection = "SWEXFW00_ls_LinkageSection";
            internal const string IEF_RUNTIME_PARM1 = "IEF_RUNTIME_PARM1";
            internal const string IEF_RUNTIME_PARM2 = "IEF_RUNTIME_PARM2";
            internal const string PSMGR_EAB_DATA = "PSMGR_EAB_DATA";
            internal const string PSMGR_EABPCB_CNT = "PSMGR_EABPCB_CNT";
            internal const string PSMGR_EABPCB_ENTRY = "PSMGR_EABPCB_ENTRY";
            internal const string PSMGR_EABPCB_ADR = "PSMGR_EABPCB_ADR";
            internal const string W_IA = "W_IA";
            internal const string A_0329249682_IA = "A_0329249682_IA";
            internal const string IMPORT_LINE_TYPE_0001EV = "IMPORT_LINE_TYPE_0001EV";
            internal const string IEF_SUPPLIED_0001ET = "IEF_SUPPLIED_0001ET";
            internal const string FLAG_0001AS = "FLAG_0001AS";
            internal const string FLAG_0001 = "FLAG_0001";
            internal const string FLAG_0001XX = "FLAG_0001XX";
            internal const string IMPORT_GROUP_ACTIVITY_L_0001GV = "IMPORT_GROUP_ACTIVITY_L_0001GV";
            internal const string IMPORT_GRP_0019EV = "IMPORT_GRP_0019EV";
            internal const string OBLIGATION_0019ET = "OBLIGATION_0019ET";
            internal const string PRIMARY_SECONDARY_CODE_0019AS = "PRIMARY_SECONDARY_CODE_0019AS";
            internal const string PRIMARY_SECONDARY_CODE_0019 = "PRIMARY_SECONDARY_CODE_0019";
            internal const string PRIMARY_SECONDARY_CODE_0019XX = "PRIMARY_SECONDARY_CODE_0019XX";
            internal const string IMPORT_GRP_0002EV = "IMPORT_GRP_0002EV";
            internal const string OBLIGATION_TYPE_0002ET = "OBLIGATION_TYPE_0002ET";
            internal const string CODE_0002AS = "CODE_0002AS";
            internal const string CODE_0002 = "CODE_0002";
            internal const string CODE_0002XX = "CODE_0002XX";
            internal const string IMPORT_GRP_0003EV = "IMPORT_GRP_0003EV";
            internal const string CSE_PERSONS_WORK_SET_0003ET = "CSE_PERSONS_WORK_SET_0003ET";
            internal const string FORMATTED_NAME_0003AS = "FORMATTED_NAME_0003AS";
            internal const string FORMATTED_NAME_0003 = "FORMATTED_NAME_0003";
            internal const string FORMATTED_NAME_0003XX = "FORMATTED_NAME_0003XX";
            internal const string IMPORT_GRP_0004EV = "IMPORT_GRP_0004EV";
            internal const string PROGRAM_0004ET = "PROGRAM_0004ET";
            internal const string CODE_0004AS = "CODE_0004AS";
            internal const string CODE_0004 = "CODE_0004";
            internal const string CODE_0004XX = "CODE_0004XX";
            internal const string IMPORT_GRP_0005EV = "IMPORT_GRP_0005EV";
            internal const string SERVICE_PROVIDER_0005ET = "SERVICE_PROVIDER_0005ET";
            internal const string USER_ID_0005AS = "USER_ID_0005AS";
            internal const string USER_ID_0005 = "USER_ID_0005";
            internal const string USER_ID_0005XX = "USER_ID_0005XX";
            internal const string IMPORT_GRP_0006EV = "IMPORT_GRP_0006EV";
            internal const string COLLECTION_0006ET = "COLLECTION_0006ET";
            internal const string AMOUNT_0006AS = "AMOUNT_0006AS";
            internal const string AMOUNT_0006 = "AMOUNT_0006";
            internal const string AMOUNT_0006XX = "AMOUNT_0006XX";
            internal const string APPLIED_TO_CODE_0006AS = "APPLIED_TO_CODE_0006AS";
            internal const string APPLIED_TO_CODE_0006 = "APPLIED_TO_CODE_0006";
            internal const string APPLIED_TO_CODE_0006XX = "APPLIED_TO_CODE_0006XX";
            internal const string DIST_PGM_STATE_APPLD_TO_0008AS = "DIST_PGM_STATE_APPLD_TO_0008AS";
            internal const string DIST_PGM_STATE_APPLD_TO_0008 = "DIST_PGM_STATE_APPLD_TO_0008";
            internal const string DIST_PGM_STATE_APPLD_TO_0008XX = "DIST_PGM_STATE_APPLD_TO_0008XX";
            internal const string IMPORT_GRP_0007EV = "IMPORT_GRP_0007EV";
            internal const string DATE_WORK_AREA_0007ET = "DATE_WORK_AREA_0007ET";
            internal const string DATE_0007AS = "DATE_0007AS";
            internal const string DATE_0007 = "DATE_0007";
            internal const string DATE_0007XX = "DATE_0007XX";
            internal const string IMPORT_AUTO_MANUAL_DIST_0008EV = "IMPORT_AUTO_MANUAL_DIST_0008EV";
            internal const string IEF_SUPPLIED_0008ET = "IEF_SUPPLIED_0008ET";
            internal const string FLAG_0008AS = "FLAG_0008AS";
            internal const string FLAG_0008 = "FLAG_0008";
            internal const string FLAG_0008XX = "FLAG_0008XX";
            internal const string IMPORT_GRP_0009EV = "IMPORT_GRP_0009EV";
            internal const string DEBT_DETAIL_0009ET = "DEBT_DETAIL_0009ET";
            internal const string DUE_DT_0009AS = "DUE_DT_0009AS";
            internal const string DUE_DT_0009 = "DUE_DT_0009";
            internal const string DUE_DT_0009XX = "DUE_DT_0009XX";
            internal const string IMPORT_GROUP_COLLECTION_0002GV = "IMPORT_GROUP_COLLECTION_0002GV";
            internal const string IMPORT_GRP_C_0020EV = "IMPORT_GRP_C_0020EV";
            internal const string CASH_RECEIPT_EVENT_0020ET = "CASH_RECEIPT_EVENT_0020ET";
            internal const string RECEIVED_DATE_0020AS = "RECEIVED_DATE_0020AS";
            internal const string RECEIVED_DATE_0020 = "RECEIVED_DATE_0020";
            internal const string RECEIVED_DATE_0020XX = "RECEIVED_DATE_0020XX";
            internal const string IMPORT_GRP_C_0010EV = "IMPORT_GRP_C_0010EV";
            internal const string CASH_RECEIPT_DETAIL_STA_0010ET = "CASH_RECEIPT_DETAIL_STA_0010ET";
            internal const string REASON_TEXT_0010AS = "REASON_TEXT_0010AS";
            internal const string REASON_TEXT_0010 = "REASON_TEXT_0010";
            internal const string REASON_TEXT_0010DL = "REASON_TEXT_0010DL";
            internal const string REASON_TEXT_0010XL = "REASON_TEXT_0010XL";
            internal const string REASON_TEXT_0010DV = "REASON_TEXT_0010DV";
            internal const string REASON_TEXT_0010XV = "REASON_TEXT_0010XV";
            internal const string REASON_TEXT_0010XX = "REASON_TEXT_0010XX";
            internal const string REASON_CODE_ID_0010AS = "REASON_CODE_ID_0010AS";
            internal const string REASON_CODE_ID_0010 = "REASON_CODE_ID_0010";
            internal const string REASON_CODE_ID_0010XX = "REASON_CODE_ID_0010XX";
            internal const string IMPORT_GRP_C_0011EV = "IMPORT_GRP_C_0011EV";
            internal const string CASH_RECEIPT_SOURCE_TYP_0011ET = "CASH_RECEIPT_SOURCE_TYP_0011ET";
            internal const string CODE_0011AS = "CODE_0011AS";
            internal const string CODE_0011 = "CODE_0011";
            internal const string CODE_0011XX = "CODE_0011XX";
            internal const string IMPORT_GRP_C_0012EV = "IMPORT_GRP_C_0012EV";
            internal const string IEF_SUPPLIED_0012ET = "IEF_SUPPLIED_0012ET";
            internal const string TOTAL_CURRENCY_0012AS = "TOTAL_CURRENCY_0012AS";
            internal const string TOTAL_CURRENCY_0012 = "TOTAL_CURRENCY_0012";
            internal const string TOTAL_CURRENCY_0012XX = "TOTAL_CURRENCY_0012XX";
            internal const string IMPORT_GRP_C_0013EV = "IMPORT_GRP_C_0013EV";
            internal const string CASH_RECEIPT_0013ET = "CASH_RECEIPT_0013ET";
            internal const string RECEIPT_DATE_0013AS = "RECEIPT_DATE_0013AS";
            internal const string RECEIPT_DATE_0013 = "RECEIPT_DATE_0013";
            internal const string RECEIPT_DATE_0013XX = "RECEIPT_DATE_0013XX";
            internal const string RECEIVED_DATE_0013AS = "RECEIVED_DATE_0013AS";
            internal const string RECEIVED_DATE_0013 = "RECEIVED_DATE_0013";
            internal const string RECEIVED_DATE_0013XX = "RECEIVED_DATE_0013XX";
            internal const string IMPORT_GRP_C_0014EV = "IMPORT_GRP_C_0014EV";
            internal const string CASH_RECEIPT_DETAIL_0014ET = "CASH_RECEIPT_DETAIL_0014ET";
            internal const string COLLECTION_DATE_0014AS = "COLLECTION_DATE_0014AS";
            internal const string COLLECTION_DATE_0014 = "COLLECTION_DATE_0014";
            internal const string COLLECTION_DATE_0014XX = "COLLECTION_DATE_0014XX";
            internal const string COLLECTION_AMOUNT_0014AS = "COLLECTION_AMOUNT_0014AS";
            internal const string COLLECTION_AMOUNT_0014 = "COLLECTION_AMOUNT_0014";
            internal const string COLLECTION_AMOUNT_0014XX = "COLLECTION_AMOUNT_0014XX";
            internal const string REFUNDED_AMOUNT_0014AS = "REFUNDED_AMOUNT_0014AS";
            internal const string REFUNDED_AMOUNT_0014 = "REFUNDED_AMOUNT_0014";
            internal const string REFUNDED_AMOUNT_0014XX = "REFUNDED_AMOUNT_0014XX";
            internal const string IMPORT_ADJ_LINE_ADJ_RSN_0015EV = "IMPORT_ADJ_LINE_ADJ_RSN_0015EV";
            internal const string COLLECTION_ADJUSTMENT_R_0015ET = "COLLECTION_ADJUSTMENT_R_0015ET";
            internal const string CODE_0015AS = "CODE_0015AS";
            internal const string CODE_0015 = "CODE_0015";
            internal const string CODE_0015XX = "CODE_0015XX";
            internal const string IMPORT_ADJ_LINE_COLL_AD_0016EV = "IMPORT_ADJ_LINE_COLL_AD_0016EV";
            internal const string COLLECTION_0016ET = "COLLECTION_0016ET";
            internal const string AMOUNT_0016AS = "AMOUNT_0016AS";
            internal const string AMOUNT_0016 = "AMOUNT_0016";
            internal const string AMOUNT_0016XX = "AMOUNT_0016XX";
            internal const string COLLECTION_ADJUSTMENT_D_0017AS = "COLLECTION_ADJUSTMENT_D_0017AS";
            internal const string COLLECTION_ADJUSTMENT_DT_0017 = "COLLECTION_ADJUSTMENT_DT_0017";
            internal const string COLLECTION_ADJUSTMENT_D_0017XX = "COLLECTION_ADJUSTMENT_D_0017XX";
            internal const string LAST_UPDATED_BY_0017AS = "LAST_UPDATED_BY_0017AS";
            internal const string LAST_UPDATED_BY_0017 = "LAST_UPDATED_BY_0017";
            internal const string LAST_UPDATED_BY_0017XX = "LAST_UPDATED_BY_0017XX";
            internal const string W_OA = "W_OA";
            internal const string A_0329249684_OA = "A_0329249684_OA";
            internal const string EXPORT_0018EV = "EXPORT_0018EV";
            internal const string LIST_SCREEN_WORK_AREA_0018ET = "LIST_SCREEN_WORK_AREA_0018ET";
            internal const string TEXT_LINE_76_0018AS = "TEXT_LINE_76_0018AS";
            internal const string TEXT_LINE_76_0018 = "TEXT_LINE_76_0018";
            internal const string TEXT_LINE_76_0018XX = "TEXT_LINE_76_0018XX";
        }
        #endregion

        #region Direct-access element properties
        public IField IEF_RUNTIME_PARM1 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM1); } }
        public IField IEF_RUNTIME_PARM2 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM2); } }
        public IGroup PSMGR_EAB_DATA { get { return GetElementByName<IGroup>(Names.PSMGR_EAB_DATA); } }
        public IField PSMGR_EABPCB_CNT { get { return GetElementByName<IField>(Names.PSMGR_EABPCB_CNT); } }
        public IArrayElementAccessor<IGroup> PSMGR_EABPCB_ENTRY { get { return GetArrayElementAccessor<IGroup>(Names.PSMGR_EABPCB_ENTRY); } }
        public IArrayElementAccessor<IField> PSMGR_EABPCB_ADR { get { return GetArrayElementAccessor<IField>(Names.PSMGR_EABPCB_ADR); } }
        public IGroup W_IA { get { return GetElementByName<IGroup>(Names.W_IA); } }
        public IGroup A_0329249682_IA { get { return GetElementByName<IGroup>(Names.A_0329249682_IA); } }
        public IGroup IMPORT_LINE_TYPE_0001EV { get { return GetElementByName<IGroup>(Names.IMPORT_LINE_TYPE_0001EV); } }
        public IGroup IEF_SUPPLIED_0001ET { get { return GetElementByName<IGroup>(Names.IEF_SUPPLIED_0001ET); } }
        public IField FLAG_0001AS { get { return GetElementByName<IField>(Names.FLAG_0001AS); } }
        public IField FLAG_0001 { get { return GetElementByName<IField>(Names.FLAG_0001); } }
        public IField FLAG_0001XX { get { return GetElementByName<IField>(Names.FLAG_0001XX); } }
        public IGroup IMPORT_GROUP_ACTIVITY_L_0001GV { get { return GetElementByName<IGroup>(Names.IMPORT_GROUP_ACTIVITY_L_0001GV); } }
        public IGroup IMPORT_GRP_0019EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0019EV); } }
        public IGroup OBLIGATION_0019ET { get { return GetElementByName<IGroup>(Names.OBLIGATION_0019ET); } }
        public IField PRIMARY_SECONDARY_CODE_0019AS { get { return GetElementByName<IField>(Names.PRIMARY_SECONDARY_CODE_0019AS); } }
        public IField PRIMARY_SECONDARY_CODE_0019 { get { return GetElementByName<IField>(Names.PRIMARY_SECONDARY_CODE_0019); } }
        public IField PRIMARY_SECONDARY_CODE_0019XX { get { return GetElementByName<IField>(Names.PRIMARY_SECONDARY_CODE_0019XX); } }
        public IGroup IMPORT_GRP_0002EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0002EV); } }
        public IGroup OBLIGATION_TYPE_0002ET { get { return GetElementByName<IGroup>(Names.OBLIGATION_TYPE_0002ET); } }
        public IField CODE_0002AS { get { return GetElementByName<IField>(Names.CODE_0002AS); } }
        public IField CODE_0002 { get { return GetElementByName<IField>(Names.CODE_0002); } }
        public IField CODE_0002XX { get { return GetElementByName<IField>(Names.CODE_0002XX); } }
        public IGroup IMPORT_GRP_0003EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0003EV); } }
        public IGroup CSE_PERSONS_WORK_SET_0003ET { get { return GetElementByName<IGroup>(Names.CSE_PERSONS_WORK_SET_0003ET); } }
        public IField FORMATTED_NAME_0003AS { get { return GetElementByName<IField>(Names.FORMATTED_NAME_0003AS); } }
        public IField FORMATTED_NAME_0003 { get { return GetElementByName<IField>(Names.FORMATTED_NAME_0003); } }
        public IField FORMATTED_NAME_0003XX { get { return GetElementByName<IField>(Names.FORMATTED_NAME_0003XX); } }
        public IGroup IMPORT_GRP_0004EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0004EV); } }
        public IGroup PROGRAM_0004ET { get { return GetElementByName<IGroup>(Names.PROGRAM_0004ET); } }
        public IField CODE_0004AS { get { return GetElementByName<IField>(Names.CODE_0004AS); } }
        public IField CODE_0004 { get { return GetElementByName<IField>(Names.CODE_0004); } }
        public IField CODE_0004XX { get { return GetElementByName<IField>(Names.CODE_0004XX); } }
        public IGroup IMPORT_GRP_0005EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0005EV); } }
        public IGroup SERVICE_PROVIDER_0005ET { get { return GetElementByName<IGroup>(Names.SERVICE_PROVIDER_0005ET); } }
        public IField USER_ID_0005AS { get { return GetElementByName<IField>(Names.USER_ID_0005AS); } }
        public IField USER_ID_0005 { get { return GetElementByName<IField>(Names.USER_ID_0005); } }
        public IField USER_ID_0005XX { get { return GetElementByName<IField>(Names.USER_ID_0005XX); } }
        public IGroup IMPORT_GRP_0006EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0006EV); } }
        public IGroup COLLECTION_0006ET { get { return GetElementByName<IGroup>(Names.COLLECTION_0006ET); } }
        public IField AMOUNT_0006AS { get { return GetElementByName<IField>(Names.AMOUNT_0006AS); } }
        public IField AMOUNT_0006 { get { return GetElementByName<IField>(Names.AMOUNT_0006); } }
        public IField AMOUNT_0006XX { get { return GetElementByName<IField>(Names.AMOUNT_0006XX); } }
        public IField APPLIED_TO_CODE_0006AS { get { return GetElementByName<IField>(Names.APPLIED_TO_CODE_0006AS); } }
        public IField APPLIED_TO_CODE_0006 { get { return GetElementByName<IField>(Names.APPLIED_TO_CODE_0006); } }
        public IField APPLIED_TO_CODE_0006XX { get { return GetElementByName<IField>(Names.APPLIED_TO_CODE_0006XX); } }
        public IField DIST_PGM_STATE_APPLD_TO_0008AS { get { return GetElementByName<IField>(Names.DIST_PGM_STATE_APPLD_TO_0008AS); } }
        public IField DIST_PGM_STATE_APPLD_TO_0008 { get { return GetElementByName<IField>(Names.DIST_PGM_STATE_APPLD_TO_0008); } }
        public IField DIST_PGM_STATE_APPLD_TO_0008XX { get { return GetElementByName<IField>(Names.DIST_PGM_STATE_APPLD_TO_0008XX); } }
        public IGroup IMPORT_GRP_0007EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0007EV); } }
        public IGroup DATE_WORK_AREA_0007ET { get { return GetElementByName<IGroup>(Names.DATE_WORK_AREA_0007ET); } }
        public IField DATE_0007AS { get { return GetElementByName<IField>(Names.DATE_0007AS); } }
        public IField DATE_0007 { get { return GetElementByName<IField>(Names.DATE_0007); } }
        public IField DATE_0007XX { get { return GetElementByName<IField>(Names.DATE_0007XX); } }
        public IGroup IMPORT_AUTO_MANUAL_DIST_0008EV { get { return GetElementByName<IGroup>(Names.IMPORT_AUTO_MANUAL_DIST_0008EV); } }
        public IGroup IEF_SUPPLIED_0008ET { get { return GetElementByName<IGroup>(Names.IEF_SUPPLIED_0008ET); } }
        public IField FLAG_0008AS { get { return GetElementByName<IField>(Names.FLAG_0008AS); } }
        public IField FLAG_0008 { get { return GetElementByName<IField>(Names.FLAG_0008); } }
        public IField FLAG_0008XX { get { return GetElementByName<IField>(Names.FLAG_0008XX); } }
        public IGroup IMPORT_GRP_0009EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_0009EV); } }
        public IGroup DEBT_DETAIL_0009ET { get { return GetElementByName<IGroup>(Names.DEBT_DETAIL_0009ET); } }
        public IField DUE_DT_0009AS { get { return GetElementByName<IField>(Names.DUE_DT_0009AS); } }
        public IField DUE_DT_0009 { get { return GetElementByName<IField>(Names.DUE_DT_0009); } }
        public IField DUE_DT_0009XX { get { return GetElementByName<IField>(Names.DUE_DT_0009XX); } }
        public IGroup IMPORT_GROUP_COLLECTION_0002GV { get { return GetElementByName<IGroup>(Names.IMPORT_GROUP_COLLECTION_0002GV); } }
        public IGroup IMPORT_GRP_C_0020EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_C_0020EV); } }
        public IGroup CASH_RECEIPT_EVENT_0020ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_EVENT_0020ET); } }
        public IField RECEIVED_DATE_0020AS { get { return GetElementByName<IField>(Names.RECEIVED_DATE_0020AS); } }
        public IField RECEIVED_DATE_0020 { get { return GetElementByName<IField>(Names.RECEIVED_DATE_0020); } }
        public IField RECEIVED_DATE_0020XX { get { return GetElementByName<IField>(Names.RECEIVED_DATE_0020XX); } }
        public IGroup IMPORT_GRP_C_0010EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_C_0010EV); } }
        public IGroup CASH_RECEIPT_DETAIL_STA_0010ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_DETAIL_STA_0010ET); } }
        public IField REASON_TEXT_0010AS { get { return GetElementByName<IField>(Names.REASON_TEXT_0010AS); } }
        public IGroup REASON_TEXT_0010 { get { return GetElementByName<IGroup>(Names.REASON_TEXT_0010); } }
        public IField REASON_TEXT_0010DL { get { return GetElementByName<IField>(Names.REASON_TEXT_0010DL); } }
        public IField REASON_TEXT_0010XL { get { return GetElementByName<IField>(Names.REASON_TEXT_0010XL); } }
        public IField REASON_TEXT_0010DV { get { return GetElementByName<IField>(Names.REASON_TEXT_0010DV); } }
        public IField REASON_TEXT_0010XV { get { return GetElementByName<IField>(Names.REASON_TEXT_0010XV); } }
        public IField REASON_TEXT_0010XX { get { return GetElementByName<IField>(Names.REASON_TEXT_0010XX); } }
        public IField REASON_CODE_ID_0010AS { get { return GetElementByName<IField>(Names.REASON_CODE_ID_0010AS); } }
        public IField REASON_CODE_ID_0010 { get { return GetElementByName<IField>(Names.REASON_CODE_ID_0010); } }
        public IField REASON_CODE_ID_0010XX { get { return GetElementByName<IField>(Names.REASON_CODE_ID_0010XX); } }
        public IGroup IMPORT_GRP_C_0011EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_C_0011EV); } }
        public IGroup CASH_RECEIPT_SOURCE_TYP_0011ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_SOURCE_TYP_0011ET); } }
        public IField CODE_0011AS { get { return GetElementByName<IField>(Names.CODE_0011AS); } }
        public IField CODE_0011 { get { return GetElementByName<IField>(Names.CODE_0011); } }
        public IField CODE_0011XX { get { return GetElementByName<IField>(Names.CODE_0011XX); } }
        public IGroup IMPORT_GRP_C_0012EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_C_0012EV); } }
        public IGroup IEF_SUPPLIED_0012ET { get { return GetElementByName<IGroup>(Names.IEF_SUPPLIED_0012ET); } }
        public IField TOTAL_CURRENCY_0012AS { get { return GetElementByName<IField>(Names.TOTAL_CURRENCY_0012AS); } }
        public IField TOTAL_CURRENCY_0012 { get { return GetElementByName<IField>(Names.TOTAL_CURRENCY_0012); } }
        public IField TOTAL_CURRENCY_0012XX { get { return GetElementByName<IField>(Names.TOTAL_CURRENCY_0012XX); } }
        public IGroup IMPORT_GRP_C_0013EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_C_0013EV); } }
        public IGroup CASH_RECEIPT_0013ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_0013ET); } }
        public IField RECEIPT_DATE_0013AS { get { return GetElementByName<IField>(Names.RECEIPT_DATE_0013AS); } }
        public IField RECEIPT_DATE_0013 { get { return GetElementByName<IField>(Names.RECEIPT_DATE_0013); } }
        public IField RECEIPT_DATE_0013XX { get { return GetElementByName<IField>(Names.RECEIPT_DATE_0013XX); } }
        public IField RECEIVED_DATE_0013AS { get { return GetElementByName<IField>(Names.RECEIVED_DATE_0013AS); } }
        public IField RECEIVED_DATE_0013 { get { return GetElementByName<IField>(Names.RECEIVED_DATE_0013); } }
        public IField RECEIVED_DATE_0013XX { get { return GetElementByName<IField>(Names.RECEIVED_DATE_0013XX); } }
        public IGroup IMPORT_GRP_C_0014EV { get { return GetElementByName<IGroup>(Names.IMPORT_GRP_C_0014EV); } }
        public IGroup CASH_RECEIPT_DETAIL_0014ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_DETAIL_0014ET); } }
        public IField COLLECTION_DATE_0014AS { get { return GetElementByName<IField>(Names.COLLECTION_DATE_0014AS); } }
        public IField COLLECTION_DATE_0014 { get { return GetElementByName<IField>(Names.COLLECTION_DATE_0014); } }
        public IField COLLECTION_DATE_0014XX { get { return GetElementByName<IField>(Names.COLLECTION_DATE_0014XX); } }
        public IField COLLECTION_AMOUNT_0014AS { get { return GetElementByName<IField>(Names.COLLECTION_AMOUNT_0014AS); } }
        public IField COLLECTION_AMOUNT_0014 { get { return GetElementByName<IField>(Names.COLLECTION_AMOUNT_0014); } }
        public IField COLLECTION_AMOUNT_0014XX { get { return GetElementByName<IField>(Names.COLLECTION_AMOUNT_0014XX); } }
        public IField REFUNDED_AMOUNT_0014AS { get { return GetElementByName<IField>(Names.REFUNDED_AMOUNT_0014AS); } }
        public IField REFUNDED_AMOUNT_0014 { get { return GetElementByName<IField>(Names.REFUNDED_AMOUNT_0014); } }
        public IField REFUNDED_AMOUNT_0014XX { get { return GetElementByName<IField>(Names.REFUNDED_AMOUNT_0014XX); } }
        public IGroup IMPORT_ADJ_LINE_ADJ_RSN_0015EV { get { return GetElementByName<IGroup>(Names.IMPORT_ADJ_LINE_ADJ_RSN_0015EV); } }
        public IGroup COLLECTION_ADJUSTMENT_R_0015ET { get { return GetElementByName<IGroup>(Names.COLLECTION_ADJUSTMENT_R_0015ET); } }
        public IField CODE_0015AS { get { return GetElementByName<IField>(Names.CODE_0015AS); } }
        public IField CODE_0015 { get { return GetElementByName<IField>(Names.CODE_0015); } }
        public IField CODE_0015XX { get { return GetElementByName<IField>(Names.CODE_0015XX); } }
        public IGroup IMPORT_ADJ_LINE_COLL_AD_0016EV { get { return GetElementByName<IGroup>(Names.IMPORT_ADJ_LINE_COLL_AD_0016EV); } }
        public IGroup COLLECTION_0016ET { get { return GetElementByName<IGroup>(Names.COLLECTION_0016ET); } }
        public IField AMOUNT_0016AS { get { return GetElementByName<IField>(Names.AMOUNT_0016AS); } }
        public IField AMOUNT_0016 { get { return GetElementByName<IField>(Names.AMOUNT_0016); } }
        public IField AMOUNT_0016XX { get { return GetElementByName<IField>(Names.AMOUNT_0016XX); } }
        public IField COLLECTION_ADJUSTMENT_D_0017AS { get { return GetElementByName<IField>(Names.COLLECTION_ADJUSTMENT_D_0017AS); } }
        public IField COLLECTION_ADJUSTMENT_DT_0017 { get { return GetElementByName<IField>(Names.COLLECTION_ADJUSTMENT_DT_0017); } }
        public IField COLLECTION_ADJUSTMENT_D_0017XX { get { return GetElementByName<IField>(Names.COLLECTION_ADJUSTMENT_D_0017XX); } }
        public IField LAST_UPDATED_BY_0017AS { get { return GetElementByName<IField>(Names.LAST_UPDATED_BY_0017AS); } }
        public IField LAST_UPDATED_BY_0017 { get { return GetElementByName<IField>(Names.LAST_UPDATED_BY_0017); } }
        public IField LAST_UPDATED_BY_0017XX { get { return GetElementByName<IField>(Names.LAST_UPDATED_BY_0017XX); } }
        public IGroup W_OA { get { return GetElementByName<IGroup>(Names.W_OA); } }
        public IGroup A_0329249684_OA { get { return GetElementByName<IGroup>(Names.A_0329249684_OA); } }
        public IGroup EXPORT_0018EV { get { return GetElementByName<IGroup>(Names.EXPORT_0018EV); } }
        public IGroup LIST_SCREEN_WORK_AREA_0018ET { get { return GetElementByName<IGroup>(Names.LIST_SCREEN_WORK_AREA_0018ET); } }
        public IField TEXT_LINE_76_0018AS { get { return GetElementByName<IField>(Names.TEXT_LINE_76_0018AS); } }
        public IField TEXT_LINE_76_0018 { get { return GetElementByName<IField>(Names.TEXT_LINE_76_0018); } }
        public IField TEXT_LINE_76_0018XX { get { return GetElementByName<IField>(Names.TEXT_LINE_76_0018XX); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the LinkageSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM1, FieldType.String, 1);
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM2, FieldType.String, 1);

            recordDef.CreateNewGroup(Names.PSMGR_EAB_DATA, (PSMGR_EAB_DATA) =>
           {
               PSMGR_EAB_DATA.CreateNewField(Names.PSMGR_EABPCB_CNT, FieldType.CompInt, 9);
               PSMGR_EAB_DATA.CreateNewGroupArray(Names.PSMGR_EABPCB_ENTRY, 255, (PSMGR_EABPCB_ENTRY) =>
               {
                   PSMGR_EABPCB_ENTRY.CreateNewField(Names.PSMGR_EABPCB_ADR, FieldType.CompInt, 9);
               });
           });

            recordDef.CreateNewGroup(Names.W_IA, (W_IA) =>
           {
               W_IA.CreateNewGroup(Names.A_0329249682_IA, (A_0329249682_IA) =>
               {
                   A_0329249682_IA.CreateNewGroup(Names.IMPORT_LINE_TYPE_0001EV, (IMPORT_LINE_TYPE_0001EV) =>
                   {
                       IMPORT_LINE_TYPE_0001EV.CreateNewGroup(Names.IEF_SUPPLIED_0001ET, (IEF_SUPPLIED_0001ET) =>
                       {
                           IEF_SUPPLIED_0001ET.CreateNewField(Names.FLAG_0001AS, FieldType.String, 1);

                           IField FLAG_0001_local = IEF_SUPPLIED_0001ET.CreateNewField(Names.FLAG_0001, FieldType.String, 1);
                           IEF_SUPPLIED_0001ET.CreateNewFieldRedefine(Names.FLAG_0001XX, FieldType.String, FLAG_0001_local, 1);
                       });
                   });
                   A_0329249682_IA.CreateNewGroup(Names.IMPORT_GROUP_ACTIVITY_L_0001GV, (IMPORT_GROUP_ACTIVITY_L_0001GV) =>
                   {
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0019EV, (IMPORT_GRP_0019EV) =>
                       {
                           IMPORT_GRP_0019EV.CreateNewGroup(Names.OBLIGATION_0019ET, (OBLIGATION_0019ET) =>
                           {
                               OBLIGATION_0019ET.CreateNewField(Names.PRIMARY_SECONDARY_CODE_0019AS, FieldType.String, 1);

                               IField PRIMARY_SECONDARY_CODE_0019_local = OBLIGATION_0019ET.CreateNewField(Names.PRIMARY_SECONDARY_CODE_0019, FieldType.String, 1);
                               OBLIGATION_0019ET.CreateNewFieldRedefine(Names.PRIMARY_SECONDARY_CODE_0019XX, FieldType.String, PRIMARY_SECONDARY_CODE_0019_local, 1);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0002EV, (IMPORT_GRP_0002EV) =>
                       {
                           IMPORT_GRP_0002EV.CreateNewGroup(Names.OBLIGATION_TYPE_0002ET, (OBLIGATION_TYPE_0002ET) =>
                           {
                               OBLIGATION_TYPE_0002ET.CreateNewField(Names.CODE_0002AS, FieldType.String, 1);

                               IField CODE_0002_local = OBLIGATION_TYPE_0002ET.CreateNewField(Names.CODE_0002, FieldType.String, 7);
                               OBLIGATION_TYPE_0002ET.CreateNewFieldRedefine(Names.CODE_0002XX, FieldType.String, CODE_0002_local, 7);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0003EV, (IMPORT_GRP_0003EV) =>
                       {
                           IMPORT_GRP_0003EV.CreateNewGroup(Names.CSE_PERSONS_WORK_SET_0003ET, (CSE_PERSONS_WORK_SET_0003ET) =>
                           {
                               CSE_PERSONS_WORK_SET_0003ET.CreateNewField(Names.FORMATTED_NAME_0003AS, FieldType.String, 1);

                               IField FORMATTED_NAME_0003_local = CSE_PERSONS_WORK_SET_0003ET.CreateNewField(Names.FORMATTED_NAME_0003, FieldType.String, 33);
                               CSE_PERSONS_WORK_SET_0003ET.CreateNewFieldRedefine(Names.FORMATTED_NAME_0003XX, FieldType.String, FORMATTED_NAME_0003_local, 33);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0004EV, (IMPORT_GRP_0004EV) =>
                       {
                           IMPORT_GRP_0004EV.CreateNewGroup(Names.PROGRAM_0004ET, (PROGRAM_0004ET) =>
                           {
                               PROGRAM_0004ET.CreateNewField(Names.CODE_0004AS, FieldType.String, 1);

                               IField CODE_0004_local = PROGRAM_0004ET.CreateNewField(Names.CODE_0004, FieldType.String, 3);
                               PROGRAM_0004ET.CreateNewFieldRedefine(Names.CODE_0004XX, FieldType.String, CODE_0004_local, 3);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0005EV, (IMPORT_GRP_0005EV) =>
                       {
                           IMPORT_GRP_0005EV.CreateNewGroup(Names.SERVICE_PROVIDER_0005ET, (SERVICE_PROVIDER_0005ET) =>
                           {
                               SERVICE_PROVIDER_0005ET.CreateNewField(Names.USER_ID_0005AS, FieldType.String, 1);

                               IField USER_ID_0005_local = SERVICE_PROVIDER_0005ET.CreateNewField(Names.USER_ID_0005, FieldType.String, 8);
                               SERVICE_PROVIDER_0005ET.CreateNewFieldRedefine(Names.USER_ID_0005XX, FieldType.String, USER_ID_0005_local, 8);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0006EV, (IMPORT_GRP_0006EV) =>
                       {
                           IMPORT_GRP_0006EV.CreateNewGroup(Names.COLLECTION_0006ET, (COLLECTION_0006ET) =>
                           {
                               COLLECTION_0006ET.CreateNewField(Names.AMOUNT_0006AS, FieldType.String, 1);

                               IField AMOUNT_0006_local = COLLECTION_0006ET.CreateNewField(Names.AMOUNT_0006, FieldType.SignedNumeric, 9, null, 2);
                               COLLECTION_0006ET.CreateNewFieldRedefine(Names.AMOUNT_0006XX, FieldType.String, AMOUNT_0006_local, 9);
                               COLLECTION_0006ET.CreateNewField(Names.APPLIED_TO_CODE_0006AS, FieldType.String, 1);

                               IField APPLIED_TO_CODE_0006_local = COLLECTION_0006ET.CreateNewField(Names.APPLIED_TO_CODE_0006, FieldType.String, 1);
                               COLLECTION_0006ET.CreateNewFieldRedefine(Names.APPLIED_TO_CODE_0006XX, FieldType.String, APPLIED_TO_CODE_0006_local, 1);
                               COLLECTION_0006ET.CreateNewField(Names.DIST_PGM_STATE_APPLD_TO_0008AS, FieldType.String, 1);

                               IField DIST_PGM_STATE_APPLD_TO_0008_local = COLLECTION_0006ET.CreateNewField(Names.DIST_PGM_STATE_APPLD_TO_0008, FieldType.String, 2);
                               COLLECTION_0006ET.CreateNewFieldRedefine(Names.DIST_PGM_STATE_APPLD_TO_0008XX, FieldType.String, DIST_PGM_STATE_APPLD_TO_0008_local, 2);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0007EV, (IMPORT_GRP_0007EV) =>
                       {
                           IMPORT_GRP_0007EV.CreateNewGroup(Names.DATE_WORK_AREA_0007ET, (DATE_WORK_AREA_0007ET) =>
                           {
                               DATE_WORK_AREA_0007ET.CreateNewField(Names.DATE_0007AS, FieldType.String, 1);

                               IField DATE_0007_local = DATE_WORK_AREA_0007ET.CreateNewField(Names.DATE_0007, FieldType.SignedNumeric, 8);
                               DATE_WORK_AREA_0007ET.CreateNewFieldRedefine(Names.DATE_0007XX, FieldType.String, DATE_0007_local, 8);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_AUTO_MANUAL_DIST_0008EV, (IMPORT_AUTO_MANUAL_DIST_0008EV) =>
                       {
                           IMPORT_AUTO_MANUAL_DIST_0008EV.CreateNewGroup(Names.IEF_SUPPLIED_0008ET, (IEF_SUPPLIED_0008ET) =>
                           {
                               IEF_SUPPLIED_0008ET.CreateNewField(Names.FLAG_0008AS, FieldType.String, 1);

                               IField FLAG_0008_local = IEF_SUPPLIED_0008ET.CreateNewField(Names.FLAG_0008, FieldType.String, 1);
                               IEF_SUPPLIED_0008ET.CreateNewFieldRedefine(Names.FLAG_0008XX, FieldType.String, FLAG_0008_local, 1);
                           });
                       });
                       IMPORT_GROUP_ACTIVITY_L_0001GV.CreateNewGroup(Names.IMPORT_GRP_0009EV, (IMPORT_GRP_0009EV) =>
                       {
                           IMPORT_GRP_0009EV.CreateNewGroup(Names.DEBT_DETAIL_0009ET, (DEBT_DETAIL_0009ET) =>
                           {
                               DEBT_DETAIL_0009ET.CreateNewField(Names.DUE_DT_0009AS, FieldType.String, 1);

                               IField DUE_DT_0009_local = DEBT_DETAIL_0009ET.CreateNewField(Names.DUE_DT_0009, FieldType.SignedNumeric, 8);
                               DEBT_DETAIL_0009ET.CreateNewFieldRedefine(Names.DUE_DT_0009XX, FieldType.String, DUE_DT_0009_local, 8);
                           });
                       });
                   });
                   A_0329249682_IA.CreateNewGroup(Names.IMPORT_GROUP_COLLECTION_0002GV, (IMPORT_GROUP_COLLECTION_0002GV) =>
                   {
                       IMPORT_GROUP_COLLECTION_0002GV.CreateNewGroup(Names.IMPORT_GRP_C_0020EV, (IMPORT_GRP_C_0020EV) =>
                       {
                           IMPORT_GRP_C_0020EV.CreateNewGroup(Names.CASH_RECEIPT_EVENT_0020ET, (CASH_RECEIPT_EVENT_0020ET) =>
                           {
                               CASH_RECEIPT_EVENT_0020ET.CreateNewField(Names.RECEIVED_DATE_0020AS, FieldType.String, 1);

                               IField RECEIVED_DATE_0020_local = CASH_RECEIPT_EVENT_0020ET.CreateNewField(Names.RECEIVED_DATE_0020, FieldType.SignedNumeric, 8);
                               CASH_RECEIPT_EVENT_0020ET.CreateNewFieldRedefine(Names.RECEIVED_DATE_0020XX, FieldType.String, RECEIVED_DATE_0020_local, 8);
                           });
                       });
                       IMPORT_GROUP_COLLECTION_0002GV.CreateNewGroup(Names.IMPORT_GRP_C_0010EV, (IMPORT_GRP_C_0010EV) =>
                       {
                           IMPORT_GRP_C_0010EV.CreateNewGroup(Names.CASH_RECEIPT_DETAIL_STA_0010ET, (CASH_RECEIPT_DETAIL_STA_0010ET) =>
                           {
                               CASH_RECEIPT_DETAIL_STA_0010ET.CreateNewField(Names.REASON_TEXT_0010AS, FieldType.String, 1);
                               IGroup REASON_TEXT_0010_local = (IGroup)CASH_RECEIPT_DETAIL_STA_0010ET.CreateNewGroup(Names.REASON_TEXT_0010, (REASON_TEXT_0010) =>
                               {

                                   IField REASON_TEXT_0010DL_local = REASON_TEXT_0010.CreateNewField(Names.REASON_TEXT_0010DL, FieldType.CompShort, 4);
                                   REASON_TEXT_0010.CreateNewFieldRedefine(Names.REASON_TEXT_0010XL, FieldType.String, REASON_TEXT_0010DL_local, 2);

                                   IField REASON_TEXT_0010DV_local = REASON_TEXT_0010.CreateNewField(Names.REASON_TEXT_0010DV, FieldType.String, 240);
                                   REASON_TEXT_0010.CreateNewFieldRedefine(Names.REASON_TEXT_0010XV, FieldType.String, REASON_TEXT_0010DV_local, 240);
                               });
                               CASH_RECEIPT_DETAIL_STA_0010ET.CreateNewFieldRedefine(Names.REASON_TEXT_0010XX, FieldType.String, REASON_TEXT_0010_local, 242);
                               CASH_RECEIPT_DETAIL_STA_0010ET.CreateNewField(Names.REASON_CODE_ID_0010AS, FieldType.String, 1);

                               IField REASON_CODE_ID_0010_local = CASH_RECEIPT_DETAIL_STA_0010ET.CreateNewField(Names.REASON_CODE_ID_0010, FieldType.String, 10);
                               CASH_RECEIPT_DETAIL_STA_0010ET.CreateNewFieldRedefine(Names.REASON_CODE_ID_0010XX, FieldType.String, REASON_CODE_ID_0010_local, 10);
                           });
                       });
                       IMPORT_GROUP_COLLECTION_0002GV.CreateNewGroup(Names.IMPORT_GRP_C_0011EV, (IMPORT_GRP_C_0011EV) =>
                       {
                           IMPORT_GRP_C_0011EV.CreateNewGroup(Names.CASH_RECEIPT_SOURCE_TYP_0011ET, (CASH_RECEIPT_SOURCE_TYP_0011ET) =>
                           {
                               CASH_RECEIPT_SOURCE_TYP_0011ET.CreateNewField(Names.CODE_0011AS, FieldType.String, 1);

                               IField CODE_0011_local = CASH_RECEIPT_SOURCE_TYP_0011ET.CreateNewField(Names.CODE_0011, FieldType.String, 10);
                               CASH_RECEIPT_SOURCE_TYP_0011ET.CreateNewFieldRedefine(Names.CODE_0011XX, FieldType.String, CODE_0011_local, 10);
                           });
                       });
                       IMPORT_GROUP_COLLECTION_0002GV.CreateNewGroup(Names.IMPORT_GRP_C_0012EV, (IMPORT_GRP_C_0012EV) =>
                       {
                           IMPORT_GRP_C_0012EV.CreateNewGroup(Names.IEF_SUPPLIED_0012ET, (IEF_SUPPLIED_0012ET) =>
                           {
                               IEF_SUPPLIED_0012ET.CreateNewField(Names.TOTAL_CURRENCY_0012AS, FieldType.String, 1);

                               IField TOTAL_CURRENCY_0012_local = IEF_SUPPLIED_0012ET.CreateNewField(Names.TOTAL_CURRENCY_0012, FieldType.SignedNumeric, 15, null, 2);
                               IEF_SUPPLIED_0012ET.CreateNewFieldRedefine(Names.TOTAL_CURRENCY_0012XX, FieldType.String, TOTAL_CURRENCY_0012_local, 15);
                           });
                       });
                       IMPORT_GROUP_COLLECTION_0002GV.CreateNewGroup(Names.IMPORT_GRP_C_0013EV, (IMPORT_GRP_C_0013EV) =>
                       {
                           IMPORT_GRP_C_0013EV.CreateNewGroup(Names.CASH_RECEIPT_0013ET, (CASH_RECEIPT_0013ET) =>
                           {
                               CASH_RECEIPT_0013ET.CreateNewField(Names.RECEIPT_DATE_0013AS, FieldType.String, 1);

                               IField RECEIPT_DATE_0013_local = CASH_RECEIPT_0013ET.CreateNewField(Names.RECEIPT_DATE_0013, FieldType.SignedNumeric, 8);
                               CASH_RECEIPT_0013ET.CreateNewFieldRedefine(Names.RECEIPT_DATE_0013XX, FieldType.String, RECEIPT_DATE_0013_local, 8);
                               CASH_RECEIPT_0013ET.CreateNewField(Names.RECEIVED_DATE_0013AS, FieldType.String, 1);

                               IField RECEIVED_DATE_0013_local = CASH_RECEIPT_0013ET.CreateNewField(Names.RECEIVED_DATE_0013, FieldType.SignedNumeric, 8);
                               CASH_RECEIPT_0013ET.CreateNewFieldRedefine(Names.RECEIVED_DATE_0013XX, FieldType.String, RECEIVED_DATE_0013_local, 8);
                           });
                       });
                       IMPORT_GROUP_COLLECTION_0002GV.CreateNewGroup(Names.IMPORT_GRP_C_0014EV, (IMPORT_GRP_C_0014EV) =>
                       {
                           IMPORT_GRP_C_0014EV.CreateNewGroup(Names.CASH_RECEIPT_DETAIL_0014ET, (CASH_RECEIPT_DETAIL_0014ET) =>
                           {
                               CASH_RECEIPT_DETAIL_0014ET.CreateNewField(Names.COLLECTION_DATE_0014AS, FieldType.String, 1);

                               IField COLLECTION_DATE_0014_local = CASH_RECEIPT_DETAIL_0014ET.CreateNewField(Names.COLLECTION_DATE_0014, FieldType.SignedNumeric, 8);
                               CASH_RECEIPT_DETAIL_0014ET.CreateNewFieldRedefine(Names.COLLECTION_DATE_0014XX, FieldType.String, COLLECTION_DATE_0014_local, 8);
                               CASH_RECEIPT_DETAIL_0014ET.CreateNewField(Names.COLLECTION_AMOUNT_0014AS, FieldType.String, 1);

                               IField COLLECTION_AMOUNT_0014_local = CASH_RECEIPT_DETAIL_0014ET.CreateNewField(Names.COLLECTION_AMOUNT_0014, FieldType.SignedNumeric, 9, null, 2);
                               CASH_RECEIPT_DETAIL_0014ET.CreateNewFieldRedefine(Names.COLLECTION_AMOUNT_0014XX, FieldType.String, COLLECTION_AMOUNT_0014_local, 9);
                               CASH_RECEIPT_DETAIL_0014ET.CreateNewField(Names.REFUNDED_AMOUNT_0014AS, FieldType.String, 1);

                               IField REFUNDED_AMOUNT_0014_local = CASH_RECEIPT_DETAIL_0014ET.CreateNewField(Names.REFUNDED_AMOUNT_0014, FieldType.SignedNumeric, 9, null, 2);
                               CASH_RECEIPT_DETAIL_0014ET.CreateNewFieldRedefine(Names.REFUNDED_AMOUNT_0014XX, FieldType.String, REFUNDED_AMOUNT_0014_local, 9);
                           });
                       });
                   });
                   A_0329249682_IA.CreateNewGroup(Names.IMPORT_ADJ_LINE_ADJ_RSN_0015EV, (IMPORT_ADJ_LINE_ADJ_RSN_0015EV) =>
                   {
                       IMPORT_ADJ_LINE_ADJ_RSN_0015EV.CreateNewGroup(Names.COLLECTION_ADJUSTMENT_R_0015ET, (COLLECTION_ADJUSTMENT_R_0015ET) =>
                       {
                           COLLECTION_ADJUSTMENT_R_0015ET.CreateNewField(Names.CODE_0015AS, FieldType.String, 1);

                           IField CODE_0015_local = COLLECTION_ADJUSTMENT_R_0015ET.CreateNewField(Names.CODE_0015, FieldType.String, 7);
                           COLLECTION_ADJUSTMENT_R_0015ET.CreateNewFieldRedefine(Names.CODE_0015XX, FieldType.String, CODE_0015_local, 7);
                       });
                   });
                   A_0329249682_IA.CreateNewGroup(Names.IMPORT_ADJ_LINE_COLL_AD_0016EV, (IMPORT_ADJ_LINE_COLL_AD_0016EV) =>
                   {
                       IMPORT_ADJ_LINE_COLL_AD_0016EV.CreateNewGroup(Names.COLLECTION_0016ET, (COLLECTION_0016ET) =>
                       {
                           COLLECTION_0016ET.CreateNewField(Names.AMOUNT_0016AS, FieldType.String, 1);

                           IField AMOUNT_0016_local = COLLECTION_0016ET.CreateNewField(Names.AMOUNT_0016, FieldType.SignedNumeric, 9, null, 2);
                           COLLECTION_0016ET.CreateNewFieldRedefine(Names.AMOUNT_0016XX, FieldType.String, AMOUNT_0016_local, 9);
                           COLLECTION_0016ET.CreateNewField(Names.COLLECTION_ADJUSTMENT_D_0017AS, FieldType.String, 1);

                           IField COLLECTION_ADJUSTMENT_DT_0017_local = COLLECTION_0016ET.CreateNewField(Names.COLLECTION_ADJUSTMENT_DT_0017, FieldType.SignedNumeric, 8);
                           COLLECTION_0016ET.CreateNewFieldRedefine(Names.COLLECTION_ADJUSTMENT_D_0017XX, FieldType.String, COLLECTION_ADJUSTMENT_DT_0017_local, 8);
                           COLLECTION_0016ET.CreateNewField(Names.LAST_UPDATED_BY_0017AS, FieldType.String, 1);

                           IField LAST_UPDATED_BY_0017_local = COLLECTION_0016ET.CreateNewField(Names.LAST_UPDATED_BY_0017, FieldType.String, 8);
                           COLLECTION_0016ET.CreateNewFieldRedefine(Names.LAST_UPDATED_BY_0017XX, FieldType.String, LAST_UPDATED_BY_0017_local, 8);
                       });
                   });
               });
           });

            recordDef.CreateNewGroup(Names.W_OA, (W_OA) =>
           {
               W_OA.CreateNewGroup(Names.A_0329249684_OA, (A_0329249684_OA) =>
               {
                   A_0329249684_OA.CreateNewGroup(Names.EXPORT_0018EV, (EXPORT_0018EV) =>
                   {
                       EXPORT_0018EV.CreateNewGroup(Names.LIST_SCREEN_WORK_AREA_0018ET, (LIST_SCREEN_WORK_AREA_0018ET) =>
                       {
                           LIST_SCREEN_WORK_AREA_0018ET.CreateNewField(Names.TEXT_LINE_76_0018AS, FieldType.String, 1);

                           IField TEXT_LINE_76_0018_local = LIST_SCREEN_WORK_AREA_0018ET.CreateNewField(Names.TEXT_LINE_76_0018, FieldType.String, 76);
                           LIST_SCREEN_WORK_AREA_0018ET.CreateNewFieldRedefine(Names.TEXT_LINE_76_0018XX, FieldType.String, TEXT_LINE_76_0018_local, 76);
                       });
                   });
               });
           });

        }

        protected override string GetRecordName()
        {
            return Names.LinkageSection;
        }
        #endregion

        public void SetPassedParameters(object[] args)
        {
            SetPassedParm(W_IA, args, 0);
            SetPassedParm(W_OA, args, 1);
            SetPassedParm(PSMGR_EAB_DATA, args, 2);
        }


        public void UpdateReturnParameters(object[] args)
        {
            SetReturnParm(W_IA, args, 0);
            SetReturnParm(W_OA, args, 1);
            SetReturnParm(PSMGR_EAB_DATA, args, 2);
        }
    }
    #endregion Linkage Section Class

    #region Business Logic Class
    public class SWEXFW00 : EABBase
    {

        #region Public Constructors
        public SWEXFW00()
            : base()
        {
            this.ProgramName.SetValue("SWEXFW00");

            WS = new SWEXFW00_ws();
            LS = new SWEXFW00_ls();
        }

        #endregion

        #region Private Fields


        //==== Working Storage Data Class ========================================
        private SWEXFW00_ws WS;

        //==== Linkage Section Data Class ========================================
        private SWEXFW00_ls LS;
        #endregion

        #region Public Methods
        //========================================================================
        //==== RunMain Entry Point Method ========================================
        //========================================================================
        public override int ExecuteMain(params object[] args)                                              //COBOL==> PROCEDURE DIVISION USING W-IA , W-OA , PSMGR-EAB-DATA.
        {
            try
            {
                WS.Initialize();
                LS.SetPassedParameters(args);
                RunMain();
                LS.UpdateReturnParameters(args);
                return Return_Code.AsInt();
            }
            catch (Exception ex)
            {
                Control.ReturnException(ex);
                return 12;
            }
        }
        #endregion

        #region Private Methods

        private void RunMain()
        {
            string returnMethod = "Main";
            // Execute Procedure Division Logic
            M_MAIN_0329249676(returnMethod);
        }
        /// <summary>
        /// Method M_MAIN_0329249676
        /// </summary>
        private void M_MAIN_0329249676(string returnMethod = "")
        {
            M_PARA_0329249676_INIT("M_PARA_0329249676_INIT_EXIT"); if (Control.ExitProgram) { return; }           //COBOL==> PERFORM PARA-0329249676-INIT THRU PARA-0329249676-INIT-EXIT
            M_PARA_0329249676("M_PARA_0329249676_EXIT"); if (Control.ExitProgram) { return; }                     //COBOL==> PERFORM PARA-0329249676 THRU PARA-0329249676-EXIT
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_PARA_0329249676
        /// </summary>
        private void M_PARA_0329249676(string returnMethod = "")
        {
            WS.FUNC_0329249676_ESC_FLAG.SetValue("N");                                                          //COBOL==> MOVE 'N' TO FUNC-0329249676-ESC-FLAG
                                                                                                                //COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
                                                                                                                //COMMENT:    USER-WRITTEN CODE SHOULD BE INSERTED HERE
                                                                                                                //COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
            M_BEGIN_MAIN_PROCESSING_PARA("M_END_MAIN_PROCESSING_PARA"); if (Control.ExitProgram) { return; }      //COBOL==> PERFORM BEGIN-MAIN-PROCESSING-PARA THRU END-MAIN-PROCESSING-PARA.
            if (returnMethod != "" && returnMethod != "M_PARA_0329249676") { M_PARA_0329249676_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0329249676_EXIT
        /// </summary>
        private void M_PARA_0329249676_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0329249676_EXIT") { return; }                                           //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0329249676_EXIT") { M_PARA_0329249676_INIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0329249676_INIT
        /// </summary>
        private void M_PARA_0329249676_INIT(string returnMethod = "")
        {
            LS.EXPORT_0018EV.ResetToInitialValue();                                                             //COBOL==> INITIALIZE EXPORT-0018EV .
            if (returnMethod != "" && returnMethod != "M_PARA_0329249676_INIT") { M_PARA_0329249676_INIT_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0329249676_INIT_EXIT
        /// </summary>
        private void M_PARA_0329249676_INIT_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0329249676_INIT_EXIT") { return; }                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0329249676_INIT_EXIT") { M_BEGIN_MAIN_PROCESSING_PARA(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_BEGIN_MAIN_PROCESSING_PARA
        /// </summary>
        private void M_BEGIN_MAIN_PROCESSING_PARA(string returnMethod = "")
        {
            WS.WS_ACTIVITY_LINE.ResetToInitialValue();                                                          //COBOL==> INITIALIZE WS-ACTIVITY-LINE
            WS.WS_COLLECTION_LINE.ResetToInitialValue();                                                        //COBOL==> INITIALIZE WS-COLLECTION-LINE
            WS.WS_ADJUSTMENT_LINE.ResetToInitialValue();                                                        //COBOL==> INITIALIZE WS-ADJUSTMENT-LINE
            WS.WS_DATE_FORMAT.ResetToInitialValue();                                                            //COBOL==> INITIALIZE WS-DATE-FORMAT
            WS.WS_DATE_FORMAT_NEW.ResetToInitialValue();                                                        //COBOL==> INITIALIZE WS-DATE-FORMAT-NEW
            WS.WS_DATE_FORMAT_NEW_A.ResetToInitialValue();                                                      //COBOL==> INITIALIZE WS-DATE-FORMAT-NEW-A
            if (LS.FLAG_0001.IsEqualTo("A"))                                                                    //COBOL==> IF FLAG-0001 = 'A'
            {
                WS.WS_DEBT_TYPE.SetValue(LS.CODE_0002);                                                             //COBOL==> MOVE CODE-0002 TO WS-DEBT-TYPE
                WS.WS_DATE_FORMAT.SetValue(LS.DUE_DT_0009);                                                         //COBOL==> MOVE DUE-DT-0009 TO WS-DATE-FORMAT
                WS.WS_DATE_MM_NEW_A.SetValue(WS.WS_DATE_MM);                                                        //COBOL==> MOVE WS-DATE-MM TO WS-DATE-MM-NEW-A
                WS.WS_DATE_DD_NEW_A.SetValue(WS.WS_DATE_DD);                                                        //COBOL==> MOVE WS-DATE-DD TO WS-DATE-DD-NEW-A
                WS.WS_DATE_YY_NEW_A.SetValue(WS.WS_DATE_YYYY);                                                      //COBOL==> MOVE WS-DATE-YYYY TO WS-DATE-YY-NEW-A
                WS.WS_DEBT_DUE_DATE.SetValue(WS.WS_DATE_FORMAT_NEW_A);                                              //COBOL==> MOVE WS-DATE-FORMAT-NEW-A TO WS-DEBT-DUE-DATE
                WS.WS_DIST_PGM_STATE.SetValue(LS.DIST_PGM_STATE_APPLD_TO_0008);                                     //COBOL==> MOVE DIST-PGM-STATE-APPLD-TO-0008 TO WS-DIST-PGM-STATE
                WS.WS_DATE_FORMAT_NEW_A.ResetToInitialValue();                                                      //COBOL==> INITIALIZE WS-DATE-FORMAT-NEW-A , WS-DATE-FORMAT
                WS.WS_DATE_FORMAT.ResetToInitialValue();
                WS.WS_FORMATTED_NAME.SetValue(LS.FORMATTED_NAME_0003);                                              //COBOL==> MOVE FORMATTED-NAME-0003 TO WS-FORMATTED-NAME
                WS.WS_PSJ_IND.SetValue(LS.PRIMARY_SECONDARY_CODE_0019);                                             //COBOL==> MOVE PRIMARY-SECONDARY-CODE-0019 TO WS-PSJ-IND
                                                                                                                    //COMMENT:        DISPLAY 'PSJ IND' PRIMARY-SECONDARY-CODE-0019
                WS.WS_PROGRAM_CODE.SetValue(LS.CODE_0004);                                                          //COBOL==> MOVE CODE-0004 TO WS-PROGRAM-CODE
                WS.WS_INTERSTATE_IND.SetValue(LS.APPLIED_TO_CODE_0006);                                             //COBOL==> MOVE APPLIED-TO-CODE-0006 TO WS-INTERSTATE-IND
                WS.WS_AMOUNT.SetValue(LS.AMOUNT_0006);                                                              //COBOL==> MOVE AMOUNT-0006 TO WS-AMOUNT
                WS.WS_DATE_FORMAT.SetValue(LS.DATE_0007);                                                           //COBOL==> MOVE DATE-0007 TO WS-DATE-FORMAT
                WS.WS_DATE_MM_NEW_A.SetValue(WS.WS_DATE_MM);                                                        //COBOL==> MOVE WS-DATE-MM TO WS-DATE-MM-NEW-A
                WS.WS_DATE_DD_NEW_A.SetValue(WS.WS_DATE_DD);                                                        //COBOL==> MOVE WS-DATE-DD TO WS-DATE-DD-NEW-A
                WS.WS_DATE_YY_NEW_A.SetValue(WS.WS_DATE_YYYY);                                                      //COBOL==> MOVE WS-DATE-YYYY TO WS-DATE-YY-NEW-A
                WS.WS_PROC_DATE.SetValue(WS.WS_DATE_FORMAT_NEW_A);                                                  //COBOL==> MOVE WS-DATE-FORMAT-NEW-A TO WS-PROC-DATE
                WS.WS_WORKER_ID.SetValue(LS.USER_ID_0005);                                                          //COBOL==> MOVE USER-ID-0005 TO WS-WORKER-ID
                WS.WS_MAN_AUTO_IND.SetValue(LS.FLAG_0008);                                                          //COBOL==> MOVE FLAG-0008 TO WS-MAN-AUTO-IND
                LS.TEXT_LINE_76_0018.SetValue(WS.WS_ACTIVITY_LINE);                                                 //COBOL==> MOVE WS-ACTIVITY-LINE TO TEXT-LINE-76-0018
            }                                                                                                   //COBOL==> ELSE
            else
            {
                if (LS.FLAG_0001.IsEqualTo("C"))                                                                    //COBOL==> IF FLAG-0001 = 'C'
                {
                    WS.WS_REASON_CODE.SetValue(LS.REASON_CODE_ID_0010);                                                 //COBOL==> MOVE REASON-CODE-ID-0010 TO WS-REASON-CODE
                    WS.WS_SOURCE_TYPE.SetValue(LS.CODE_0011);                                                           //COBOL==> MOVE CODE-0011 TO WS-SOURCE-TYPE
                    WS.WS_UNDISTR_AMT.SetValue(LS.TOTAL_CURRENCY_0012);                                                 //COBOL==> MOVE TOTAL-CURRENCY-0012 TO WS-UNDISTR-AMT
                    WS.WS_DATE_FORMAT.SetValue(LS.RECEIVED_DATE_0020);                                                  //COBOL==> MOVE RECEIVED-DATE-0020 TO WS-DATE-FORMAT
                    WS.WS_DATE_MM_NEW.SetValue(WS.WS_DATE_MM);                                                          //COBOL==> MOVE WS-DATE-MM TO WS-DATE-MM-NEW
                    WS.WS_DATE_DD_NEW.SetValue(WS.WS_DATE_DD);                                                          //COBOL==> MOVE WS-DATE-DD TO WS-DATE-DD-NEW
                    WS.WS_DATE_YYYY_NEW.SetValue(WS.WS_DATE_YYYY);                                                      //COBOL==> MOVE WS-DATE-YYYY TO WS-DATE-YYYY-NEW
                    WS.WS_RECEIPT_DATE.SetValue(WS.WS_DATE_FORMAT_NEW);                                                 //COBOL==> MOVE WS-DATE-FORMAT-NEW TO WS-RECEIPT-DATE
                    WS.WS_DATE_FORMAT.SetValue(LS.COLLECTION_DATE_0014);                                                //COBOL==> MOVE COLLECTION-DATE-0014 TO WS-DATE-FORMAT
                    WS.WS_DATE_MM_NEW.SetValue(WS.WS_DATE_MM);                                                          //COBOL==> MOVE WS-DATE-MM TO WS-DATE-MM-NEW
                    WS.WS_DATE_DD_NEW.SetValue(WS.WS_DATE_DD);                                                          //COBOL==> MOVE WS-DATE-DD TO WS-DATE-DD-NEW
                    WS.WS_DATE_YYYY_NEW.SetValue(WS.WS_DATE_YYYY);                                                      //COBOL==> MOVE WS-DATE-YYYY TO WS-DATE-YYYY-NEW
                    WS.WS_COLLECT_DATE.SetValue(WS.WS_DATE_FORMAT_NEW);                                                 //COBOL==> MOVE WS-DATE-FORMAT-NEW TO WS-COLLECT-DATE
                    WS.WS_COLLECT_AMT.SetValue(LS.COLLECTION_AMOUNT_0014);                                              //COBOL==> MOVE COLLECTION-AMOUNT-0014 TO WS-COLLECT-AMT
                    WS.WS_REFUND_AMT.SetValue(LS.REFUNDED_AMOUNT_0014);                                                 //COBOL==> MOVE REFUNDED-AMOUNT-0014 TO WS-REFUND-AMT
                    LS.TEXT_LINE_76_0018.SetValue(WS.WS_COLLECTION_LINE);                                               //COBOL==> MOVE WS-COLLECTION-LINE TO TEXT-LINE-76-0018
                }                                                                                                   //COBOL==> ELSE
                else
                {
                    if (LS.FLAG_0001.IsEqualTo("D"))                                                                    //COBOL==> IF FLAG-0001 = 'D'
                    {
                        WS.WS_ADJ_RSN_CODE.SetValue(LS.CODE_0015);                                                          //COBOL==> MOVE CODE-0015 TO WS-ADJ-RSN-CODE
                        WS.WS_ADJ_AMT.SetValue(LS.AMOUNT_0016);                                                             //COBOL==> MOVE AMOUNT-0016 TO WS-ADJ-AMT
                        WS.WS_DATE_FORMAT.SetValue(LS.COLLECTION_ADJUSTMENT_DT_0017);                                       //COBOL==> MOVE COLLECTION-ADJUSTMENT-DT-0017 TO WS-DATE-FORMAT
                        WS.WS_DATE_MM_NEW.SetValue(WS.WS_DATE_MM);                                                          //COBOL==> MOVE WS-DATE-MM TO WS-DATE-MM-NEW
                        WS.WS_DATE_DD_NEW.SetValue(WS.WS_DATE_DD);                                                          //COBOL==> MOVE WS-DATE-DD TO WS-DATE-DD-NEW
                        WS.WS_DATE_YYYY_NEW.SetValue(WS.WS_DATE_YYYY);                                                      //COBOL==> MOVE WS-DATE-YYYY TO WS-DATE-YYYY-NEW
                        WS.WS_ADJ_DATE.SetValue(WS.WS_DATE_FORMAT_NEW);                                                     //COBOL==> MOVE WS-DATE-FORMAT-NEW TO WS-ADJ-DATE
                        LS.TEXT_LINE_76_0018.SetValue(WS.WS_ADJUSTMENT_LINE);                                               //COBOL==> MOVE WS-ADJUSTMENT-LINE TO TEXT-LINE-76-0018
                    }                                                                                                   //COBOL==> ELSE
                    else
                    {
                        LS.TEXT_LINE_76_0018.SetValue("ERROR IN FORMATTING");                                               //COBOL==> MOVE 'ERROR IN FORMATTING' TO TEXT-LINE-76-0018.
                    }
                }
            }
            if (returnMethod != "" && returnMethod != "M_BEGIN_MAIN_PROCESSING_PARA") { M_END_MAIN_PROCESSING_PARA(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_END_MAIN_PROCESSING_PARA
        /// </summary>
        private void M_END_MAIN_PROCESSING_PARA(string returnMethod = "")
        {
            if (returnMethod == "M_END_MAIN_PROCESSING_PARA") { return; }                                       //COBOL==> EXIT.
        }
        #endregion
    }
    #endregion
}
