#region Comments
/* Conversion Comments
   ************************************************************
   **   MODERN SYSTEMS INC.  COPYRIGHT 2000-2022
   **   DB-SHUTTLE COBOL to C# Conversion
   ************************************************************
   ** INIT   *  INITIAL VERSION   *  2022-03-02 04:47:11 PM
   **        *   FROM COBOL PGM   :  SWEXFE02
   **        *   FROM CANISTER    :  SR.CAECSES.PROD.LIBR.SOURCE.PDS
   ************************************************************ */

/* Original Program Identification Comments
   **************************************************************
                       SOURCE CODE GENERATED BY
                   INFORMATION ENGINEERING FACILITY (TM)
                       TEXAS INSTRUMENTS INC.
                COPYRIGHT (C) TEXAS INSTRUMENTS INC. 1995
       NAME: EXT_TO_DO_A_COMMIT               DATE: 95/08/15
       TARGET OS:   MVS                       TIME: 13:52:15
       TARGET DBMS: DB2                       USER: SWMTMAF
       GENERATION OPTIONS:
       DEBUG TRACE OPTION NOT SELECTED
       DATA MODELING CONSTRAINT ENFORCEMENT NOT SELECTED
       OPTIMIZED IMPORT VIEW INITIALIZATION SELECTED
   **************************************************************
*/
#endregion
#region Using Directives
using MDSY.Framework.Buffer;
using MDSY.Framework.Buffer.BaseClasses;
using MDSY.Framework.Buffer.Common;
using MDSY.Framework.Buffer.Interfaces;
using MDSY.Framework.Core;
using System;

/*  usings for referenced objects  */
#endregion

namespace GOV.KS.DCF.CSS.Common.BL
{
    #region Working Storage Class
    internal class SWEXFE02_ws : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string WorkingStorage = "SWEXFE02_ws_WorkingStorage";
            internal const string FUNC_0329081574_ESC_FLAG = "FUNC_0329081574_ESC_FLAG";
        }
        #endregion

        #region Direct-access element properties
        public IField FUNC_0329081574_ESC_FLAG { get { return GetElementByName<IField>(Names.FUNC_0329081574_ESC_FLAG); } }

        public CPY_SQLCA SQLCA = new CPY_SQLCA(null, true);
        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the WorkingStorage IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.FUNC_0329081574_ESC_FLAG, FieldType.String, 1);


        }

        protected override string GetRecordName()
        {
            return Names.WorkingStorage;
        }
        #endregion

        #region Initialize
        public override void Initialize()
        {
            InitializeWithLowValues();
            SQLCA.InitializeWithLowValues();
        }
        #endregion

    }
    #endregion Working Storage Class

    #region Linkage Section Class
    internal class SWEXFE02_ls : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string LinkageSection = "SWEXFE02_ls_LinkageSection";
            internal const string IEF_RUNTIME_PARM1 = "IEF_RUNTIME_PARM1";
            internal const string IEF_RUNTIME_PARM2 = "IEF_RUNTIME_PARM2";
            internal const string PSMGR_EAB_DATA = "PSMGR_EAB_DATA";
            internal const string PSMGR_EABPCB_CNT = "PSMGR_EABPCB_CNT";
            internal const string PSMGR_EABPCB_ENTRY = "PSMGR_EABPCB_ENTRY";
            internal const string PSMGR_EABPCB_ADR = "PSMGR_EABPCB_ADR";
            internal const string W_OA = "W_OA";
            internal const string A_0329081580_OA = "A_0329081580_OA";
            internal const string S0329081582_0001EV = "S0329081582_0001EV";
            internal const string EXTERNAL_0001ET = "EXTERNAL_0001ET";
            internal const string NUMERIC_RETURN_CODE_0001AS = "NUMERIC_RETURN_CODE_0001AS";
            internal const string NUMERIC_RETURN_CODE_0001 = "NUMERIC_RETURN_CODE_0001";
            internal const string NUMERIC_RETURN_CODE_0001XX = "NUMERIC_RETURN_CODE_0001XX";
        }
        #endregion

        #region Direct-access element properties
        public IField IEF_RUNTIME_PARM1 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM1); } }
        public IField IEF_RUNTIME_PARM2 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM2); } }
        public IGroup PSMGR_EAB_DATA { get { return GetElementByName<IGroup>(Names.PSMGR_EAB_DATA); } }
        public IField PSMGR_EABPCB_CNT { get { return GetElementByName<IField>(Names.PSMGR_EABPCB_CNT); } }
        public IArrayElementAccessor<IGroup> PSMGR_EABPCB_ENTRY { get { return GetArrayElementAccessor<IGroup>(Names.PSMGR_EABPCB_ENTRY); } }
        public IArrayElementAccessor<IField> PSMGR_EABPCB_ADR { get { return GetArrayElementAccessor<IField>(Names.PSMGR_EABPCB_ADR); } }
        public IGroup W_OA { get { return GetElementByName<IGroup>(Names.W_OA); } }
        public IGroup A_0329081580_OA { get { return GetElementByName<IGroup>(Names.A_0329081580_OA); } }
        public IGroup S0329081582_0001EV { get { return GetElementByName<IGroup>(Names.S0329081582_0001EV); } }
        public IGroup EXTERNAL_0001ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_0001ET); } }
        public IField NUMERIC_RETURN_CODE_0001AS { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0001AS); } }
        public IField NUMERIC_RETURN_CODE_0001 { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0001); } }
        public IField NUMERIC_RETURN_CODE_0001XX { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0001XX); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the LinkageSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM1, FieldType.String, 1);
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM2, FieldType.String, 1);

            recordDef.CreateNewGroup(Names.PSMGR_EAB_DATA, (PSMGR_EAB_DATA) =>
           {
               PSMGR_EAB_DATA.CreateNewField(Names.PSMGR_EABPCB_CNT, FieldType.CompInt, 9);
               PSMGR_EAB_DATA.CreateNewGroupArray(Names.PSMGR_EABPCB_ENTRY, 255, (PSMGR_EABPCB_ENTRY) =>
               {
                   PSMGR_EABPCB_ENTRY.CreateNewField(Names.PSMGR_EABPCB_ADR, FieldType.CompInt, 9);
               });
           });

            recordDef.CreateNewGroup(Names.W_OA, (W_OA) =>
           {
               W_OA.CreateNewGroup(Names.A_0329081580_OA, (A_0329081580_OA) =>
               {
                   A_0329081580_OA.CreateNewGroup(Names.S0329081582_0001EV, (S0329081582_0001EV) =>
                   {
                       S0329081582_0001EV.CreateNewGroup(Names.EXTERNAL_0001ET, (EXTERNAL_0001ET) =>
                       {
                           EXTERNAL_0001ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0001AS, FieldType.String, 1);

                           IField NUMERIC_RETURN_CODE_0001_local = EXTERNAL_0001ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0001, FieldType.SignedNumeric, 2);
                           EXTERNAL_0001ET.CreateNewFieldRedefine(Names.NUMERIC_RETURN_CODE_0001XX, FieldType.String, NUMERIC_RETURN_CODE_0001_local, 2);
                       });
                   });
               });
           });

        }

        protected override string GetRecordName()
        {
            return Names.LinkageSection;
        }
        #endregion

        public void SetPassedParameters(object[] args)
        {
            SetPassedParm(IEF_RUNTIME_PARM1, args, 0);
            SetPassedParm(IEF_RUNTIME_PARM2, args, 1);
            SetPassedParm(W_OA, args, 2);
            SetPassedParm(PSMGR_EAB_DATA, args, 3);
        }


        public void UpdateReturnParameters(object[] args)
        {
            SetReturnParm(IEF_RUNTIME_PARM1, args, 0);
            SetReturnParm(IEF_RUNTIME_PARM2, args, 1);
            SetReturnParm(W_OA, args, 2);
            SetReturnParm(PSMGR_EAB_DATA, args, 3);
        }
    }
    #endregion Linkage Section Class

    #region Business Logic Class
    public class SWEXFE02 : EABBase
    {

        #region Public Constructors
        public SWEXFE02()
            : base()
        {
            this.ProgramName.SetValue("SWEXFE02");

            WS = new SWEXFE02_ws();
            LS = new SWEXFE02_ls();
            DbConv.SQLCA.Record = WS.SQLCA.Record;

        }

        #endregion

        #region Private Fields


        //==== Working Storage Data Class ========================================
        private SWEXFE02_ws WS;

        //==== Linkage Section Data Class ========================================
        private SWEXFE02_ls LS;
        #endregion

        #region Public Methods
        //========================================================================
        //==== RunMain Entry Point Method ========================================
        //========================================================================
        public override int ExecuteMain(params object[] args)                                              //COBOL==> PROCEDURE DIVISION USING IEF-RUNTIME-PARM1 , IEF-RUNTIME-PARM2 , W-OA , PSMGR-EAB-DATA.
        {
            try
            {
                WS.Initialize();
                LS.SetPassedParameters(args);
                RunMain();
                LS.UpdateReturnParameters(args);
                return Return_Code.AsInt();
            }
            catch (Exception ex)
            {
                Control.ReturnException(ex);
                return 12;
            }
        }
        #endregion

        #region Private Methods

        private void RunMain()
        {
            string returnMethod = "Main";
            // Execute Procedure Division Logic
            M_MAIN_0329081574(returnMethod);
        }
        /// <summary>
        /// Method M_MAIN_0329081574
        /// </summary>
        private void M_MAIN_0329081574(string returnMethod = "")
        {
            M_PARA_0329081574_INIT("M_PARA_0329081574_INIT_EXIT"); if (Control.ExitProgram) { return; }           //COBOL==> PERFORM PARA-0329081574-INIT THRU PARA-0329081574-INIT-EXIT
            M_PARA_0329081574("M_PARA_0329081574_EXIT"); if (Control.ExitProgram) { return; }                     //COBOL==> PERFORM PARA-0329081574 THRU PARA-0329081574-EXIT
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_PARA_0329081574
        /// </summary>
        private void M_PARA_0329081574(string returnMethod = "")
        {
            WS.FUNC_0329081574_ESC_FLAG.SetValue("N");                                                          //COBOL==> MOVE 'N' TO FUNC-0329081574-ESC-FLAG
                                                                                                                //COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
                                                                                                                //COMMENT:    USER-WRITTEN CODE SHOULD BE INSERTED HERE
                                                                                                                //COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
            DbConv.Commit();                                                                                    //COBOL==> EXEC SQL COMMIT WORK END-EXEC
            if (!(DbConv.SQLCA.SQLCODE.IsEqualTo(0)))                                                           //COBOL==> IF SQLCODE NOT EQUAL 0
            {
                LS.NUMERIC_RETURN_CODE_0001.SetValue(DbConv.SQLCA.SQLCODE);                                         //COBOL==> MOVE SQLCODE TO NUMERIC-RETURN-CODE-0001
            }                                                                                                   //COBOL==> END-IF .
            if (returnMethod != "" && returnMethod != "M_PARA_0329081574") { M_PARA_0329081574_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0329081574_EXIT
        /// </summary>
        private void M_PARA_0329081574_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0329081574_EXIT") { return; }                                           //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0329081574_EXIT") { M_PARA_0329081574_INIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0329081574_INIT
        /// </summary>
        private void M_PARA_0329081574_INIT(string returnMethod = "")
        {
            LS.S0329081582_0001EV.ResetToInitialValue();                                                        //COBOL==> INITIALIZE S0329081582-0001EV .
            if (returnMethod != "" && returnMethod != "M_PARA_0329081574_INIT") { M_PARA_0329081574_INIT_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0329081574_INIT_EXIT
        /// </summary>
        private void M_PARA_0329081574_INIT_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0329081574_INIT_EXIT") { return; }                                      //COBOL==> EXIT.
        }
        #endregion
    }
    #endregion
}
