#region Comments
/* Conversion Comments
   ************************************************************
   **   MODERN SYSTEMS INC.  COPYRIGHT 2000-2021
   **   DB-SHUTTLE COBOL to C# Conversion
   ************************************************************
   ** INIT   *  INITIAL VERSION   *  2021-12-07 03:12:28 PM
   **        *   FROM COBOL PGM   :  SWEXFE98
   **        *   FROM CANISTER    :  SR.CAECSES.PROD.LIBR.SOURCE.PDS
   ************************************************************ */

/* Original Program Identification Comments
   **************************************************************
                       SOURCE CODE GENERATED BY
                   INFORMATION ENGINEERING FACILITY (TM)
                       TEXAS INSTRUMENTS INC.
                COPYRIGHT (C) TEXAS INSTRUMENTS INC. 1996
       NAME: EAB_SDSO_INTERFACE_DRVR          DATE: 96/10/10
       TARGET OS:   MVS                       TIME: 17:31:51
       TARGET DBMS: DB2                       USER: SWMTRLM
       GENERATION OPTIONS:
       DEBUG TRACE OPTION NOT SELECTED
       DATA MODELING CONSTRAINT ENFORCEMENT NOT SELECTED
       OPTIMIZED IMPORT VIEW INITIALIZATION SELECTED
   **************************************************************
*/
#endregion
#region Using Directives
using System;
using System.Data;
using System.Collections.Generic;
using MDSY.Framework.IO.Common;
using MDSY.Framework.Buffer;
using MDSY.Framework.Buffer.BaseClasses;
using MDSY.Framework.Buffer.Interfaces;
using MDSY.Framework.Buffer.Common;
using MDSY.Framework.Core;
using MDSY.Framework.Data.SQL;
using MDSY.Framework.Interfaces;
using MDSY.Framework.IO.Common;
#endregion

namespace GOV.KS.DCF.CSS.Common.BL
{
    #region File Section Class
    internal class SWEXFE98_fd : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string FileSection = "SWEXFE98_fd_FileSection";
            internal const string SDSO_INPUT_FILE = "SDSO_INPUT_FILE";
            internal const string SDSO_INPUT_RECORD = "SDSO_INPUT_RECORD";
            internal const string HEADER_RECORD = "HEADER_RECORD";
            internal const string SDSO_RECORD_TYPE = "SDSO_RECORD_TYPE";
            internal const string SDSO_SOURCE_CREATION_DT = "SDSO_SOURCE_CREATION_DT";
            internal const string SDSO_SRC_CREATE_MM = "SDSO_SRC_CREATE_MM";
            internal const string SDSO_SRC_CREATE_DD = "SDSO_SRC_CREATE_DD";
            internal const string SDSO_SRC_CREATE_CC = "SDSO_SRC_CREATE_CC";
            internal const string SDSO_SRC_CREATE_YY = "SDSO_SRC_CREATE_YY";
            internal const string DETAIL_RECORD = "DETAIL_RECORD";
            internal const string SDSO_RECORD_TYPE_d2 = "SDSO_RECORD_TYPE_d2";
            internal const string SDSO_REGION_TEAM = "SDSO_REGION_TEAM";
            internal const string SDSO_AP_NUMBER = "SDSO_AP_NUMBER";
            internal const string SDSO_FILLER = "SDSO_FILLER";
            internal const string SDSO_PAYMENT_AMT = "SDSO_PAYMENT_AMT";
            internal const string SDSO_FILLER_d2 = "SDSO_FILLER_d2";
            internal const string SDSO_COLL_TYPE = "SDSO_COLL_TYPE";
            internal const string SDSO_FILLER_d3 = "SDSO_FILLER_d3";
            internal const string TOTAL_RECORD = "TOTAL_RECORD";
            internal const string SDSO_RECORD_TYPE_d3 = "SDSO_RECORD_TYPE_d3";
            internal const string SDSO_RECORD_COUNT = "SDSO_RECORD_COUNT";
            internal const string SDSO_TOTAL_AMOUNT = "SDSO_TOTAL_AMOUNT";
            internal const string SDSO_FILLER_d4 = "SDSO_FILLER_d4";
        }
        #endregion

        #region Direct-access element properties
        public IFileLink SDSO_INPUT_FILE { get; set; }
        public IGroup SDSO_INPUT_RECORD { get { return GetElementByName<IGroup>(Names.SDSO_INPUT_RECORD); } }
        public IGroup HEADER_RECORD { get { return GetElementByName<IGroup>(Names.HEADER_RECORD); } }
        public IField SDSO_RECORD_TYPE { get { return GetElementByName<IField>(Names.SDSO_RECORD_TYPE); } }
        public IGroup SDSO_SOURCE_CREATION_DT { get { return GetElementByName<IGroup>(Names.SDSO_SOURCE_CREATION_DT); } }
        public IField SDSO_SRC_CREATE_MM { get { return GetElementByName<IField>(Names.SDSO_SRC_CREATE_MM); } }
        public IField SDSO_SRC_CREATE_DD { get { return GetElementByName<IField>(Names.SDSO_SRC_CREATE_DD); } }
        public IField SDSO_SRC_CREATE_CC { get { return GetElementByName<IField>(Names.SDSO_SRC_CREATE_CC); } }
        public IField SDSO_SRC_CREATE_YY { get { return GetElementByName<IField>(Names.SDSO_SRC_CREATE_YY); } }
        public IGroup DETAIL_RECORD { get { return GetElementByName<IGroup>(Names.DETAIL_RECORD); } }
        public IField SDSO_RECORD_TYPE_d2 { get { return GetElementByName<IField>(Names.SDSO_RECORD_TYPE_d2); } }
        public IField SDSO_REGION_TEAM { get { return GetElementByName<IField>(Names.SDSO_REGION_TEAM); } }
        public IField SDSO_AP_NUMBER { get { return GetElementByName<IField>(Names.SDSO_AP_NUMBER); } }
        public IField SDSO_FILLER { get { return GetElementByName<IField>(Names.SDSO_FILLER); } }
        public IField SDSO_PAYMENT_AMT { get { return GetElementByName<IField>(Names.SDSO_PAYMENT_AMT); } }
        public IField SDSO_FILLER_d2 { get { return GetElementByName<IField>(Names.SDSO_FILLER_d2); } }
        public IField SDSO_COLL_TYPE { get { return GetElementByName<IField>(Names.SDSO_COLL_TYPE); } }
        public IField SDSO_FILLER_d3 { get { return GetElementByName<IField>(Names.SDSO_FILLER_d3); } }
        public IGroup TOTAL_RECORD { get { return GetElementByName<IGroup>(Names.TOTAL_RECORD); } }
        public IField SDSO_RECORD_TYPE_d3 { get { return GetElementByName<IField>(Names.SDSO_RECORD_TYPE_d3); } }
        public IField SDSO_RECORD_COUNT { get { return GetElementByName<IField>(Names.SDSO_RECORD_COUNT); } }
        public IField SDSO_TOTAL_AMOUNT { get { return GetElementByName<IField>(Names.SDSO_TOTAL_AMOUNT); } }
        public IField SDSO_FILLER_d4 { get { return GetElementByName<IField>(Names.SDSO_FILLER_d4); } }


        internal SWEXFE98_ws WS;
        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the FileSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {

            recordDef.CreateNewGroup(Names.SDSO_INPUT_RECORD, (SDSO_INPUT_RECORD) =>
           {
               IGroup HEADER_RECORD_local = (IGroup)SDSO_INPUT_RECORD.CreateNewGroup(Names.HEADER_RECORD, (HEADER_RECORD) =>
               {
                   HEADER_RECORD.CreateNewField(Names.SDSO_RECORD_TYPE, FieldType.String, 1);
                   HEADER_RECORD.CreateNewGroup(Names.SDSO_SOURCE_CREATION_DT, (SDSO_SOURCE_CREATION_DT) =>
                   {
                       SDSO_SOURCE_CREATION_DT.CreateNewField(Names.SDSO_SRC_CREATE_MM, FieldType.UnsignedNumeric, 2);
                       SDSO_SOURCE_CREATION_DT.CreateNewField(Names.SDSO_SRC_CREATE_DD, FieldType.UnsignedNumeric, 2);
                       SDSO_SOURCE_CREATION_DT.CreateNewField(Names.SDSO_SRC_CREATE_CC, FieldType.UnsignedNumeric, 2);
                       SDSO_SOURCE_CREATION_DT.CreateNewField(Names.SDSO_SRC_CREATE_YY, FieldType.UnsignedNumeric, 2);
                   });
                   HEADER_RECORD.CreateNewFillerField(71, FillWith.Hashes);
               });
               SDSO_INPUT_RECORD.CreateNewGroupRedefine(Names.DETAIL_RECORD, HEADER_RECORD_local, (DETAIL_RECORD) =>
               {
                   DETAIL_RECORD.CreateNewField(Names.SDSO_RECORD_TYPE_d2, FieldType.String, 1);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_REGION_TEAM, FieldType.String, 3);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_AP_NUMBER, FieldType.String, 10);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_FILLER, FieldType.String, 1);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_PAYMENT_AMT, FieldType.UnsignedNumeric, 9, null, 2);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_FILLER_d2, FieldType.String, 1);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_COLL_TYPE, FieldType.String, 1);
                   DETAIL_RECORD.CreateNewField(Names.SDSO_FILLER_d3, FieldType.String, 54);
               });
               SDSO_INPUT_RECORD.CreateNewGroupRedefine(Names.TOTAL_RECORD, HEADER_RECORD_local, (TOTAL_RECORD) =>
               {
                   TOTAL_RECORD.CreateNewField(Names.SDSO_RECORD_TYPE_d3, FieldType.String, 1);
                   TOTAL_RECORD.CreateNewField(Names.SDSO_RECORD_COUNT, FieldType.String, 4);
                   TOTAL_RECORD.CreateNewField(Names.SDSO_TOTAL_AMOUNT, FieldType.UnsignedNumeric, 9, null, 2);
                   TOTAL_RECORD.CreateNewField(Names.SDSO_FILLER_d4, FieldType.String, 66);
               });
           });

        }

        protected override string GetRecordName()
        {
            return Names.FileSection;
        }
        #endregion

        #region Initialize
        public override void Initialize()
        {
            InitializeWithLowValues();
            IFileHandler FileHandler = InversionContainer.GetImplementingObject<IFileHandler>();

            SDSO_INPUT_FILE = FileHandler.GetFile("UT_S_SDSINPUT");
            SDSO_INPUT_FILE.StatusField = WS.SDSO_FILE_STATUS;
            SDSO_INPUT_FILE.AssociatedBuffer = SDSO_INPUT_RECORD;
        }
        #endregion

        #region Constructors
        public SWEXFE98_fd(SWEXFE98_ws ws)
            : base()
        {
            this.WS = ws;
            Initialize();

        }
        #endregion
    }
    #endregion File Section Class
    #region Working Storage Class
    internal class SWEXFE98_ws : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string WorkingStorage = "SWEXFE98_ws_WorkingStorage";
            internal const string SDSO_FILE_STATUS = "SDSO_FILE_STATUS";
            internal const string WS_INPUT_RESTART_INFO = "WS_INPUT_RESTART_INFO";
            internal const string WS_INPUT_SRC_CREATE_DT = "WS_INPUT_SRC_CREATE_DT";
            internal const string WS_INPUT_AP_NUMBER = "WS_INPUT_AP_NUMBER";
            internal const string WS_INPUT_COLL_TYPE = "WS_INPUT_COLL_TYPE";
            internal const string WS_FORMATTED_RESTART_INFO = "WS_FORMATTED_RESTART_INFO";
            internal const string WS_RECORD_TYPE = "WS_RECORD_TYPE";
            internal const string WS_SRC_CREATE_DATE = "WS_SRC_CREATE_DATE";
            internal const string WS_SRC_CREATE_MM = "WS_SRC_CREATE_MM";
            internal const string WS_SRC_CREATE_DD = "WS_SRC_CREATE_DD";
            internal const string WS_SRC_CREATE_CC = "WS_SRC_CREATE_CC";
            internal const string WS_SRC_CREATE_YY = "WS_SRC_CREATE_YY";
            internal const string WS_AP_NUMBER = "WS_AP_NUMBER";
            internal const string WS_COLL_TYPE = "WS_COLL_TYPE";
            internal const string WS_STANDARD_DATE = "WS_STANDARD_DATE";
            internal const string WS_STANDARD_CC = "WS_STANDARD_CC";
            internal const string WS_STANDARD_YY = "WS_STANDARD_YY";
            internal const string WS_STANDARD_MM = "WS_STANDARD_MM";
            internal const string WS_STANDARD_DD = "WS_STANDARD_DD";
            internal const string WS_INTERFACE_DATE = "WS_INTERFACE_DATE";
            internal const string WS_INTERFACE_MM = "WS_INTERFACE_MM";
            internal const string WS_INTERFACE_DD = "WS_INTERFACE_DD";
            internal const string WS_INTERFACE_CC = "WS_INTERFACE_CC";
            internal const string WS_INTERFACE_YY = "WS_INTERFACE_YY";
            internal const string FUNC_0661701014_ESC_FLAG = "FUNC_0661701014_ESC_FLAG";
        }
        #endregion

        #region Direct-access element properties
        public IField SDSO_FILE_STATUS { get { return GetExternalElementByName<IField>(Names.SDSO_FILE_STATUS); } }
        public IGroup WS_INPUT_RESTART_INFO { get { return GetElementByName<IGroup>(Names.WS_INPUT_RESTART_INFO); } }
        public IField WS_INPUT_SRC_CREATE_DT { get { return GetElementByName<IField>(Names.WS_INPUT_SRC_CREATE_DT); } }
        public IField WS_INPUT_AP_NUMBER { get { return GetElementByName<IField>(Names.WS_INPUT_AP_NUMBER); } }
        public IField WS_INPUT_COLL_TYPE { get { return GetElementByName<IField>(Names.WS_INPUT_COLL_TYPE); } }
        public IGroup WS_FORMATTED_RESTART_INFO { get { return GetElementByName<IGroup>(Names.WS_FORMATTED_RESTART_INFO); } }
        public IField WS_RECORD_TYPE { get { return GetElementByName<IField>(Names.WS_RECORD_TYPE); } }
        public IGroup WS_SRC_CREATE_DATE { get { return GetElementByName<IGroup>(Names.WS_SRC_CREATE_DATE); } }
        public IField WS_SRC_CREATE_MM { get { return GetElementByName<IField>(Names.WS_SRC_CREATE_MM); } }
        public IField WS_SRC_CREATE_DD { get { return GetElementByName<IField>(Names.WS_SRC_CREATE_DD); } }
        public IField WS_SRC_CREATE_CC { get { return GetElementByName<IField>(Names.WS_SRC_CREATE_CC); } }
        public IField WS_SRC_CREATE_YY { get { return GetElementByName<IField>(Names.WS_SRC_CREATE_YY); } }
        public IField WS_AP_NUMBER { get { return GetElementByName<IField>(Names.WS_AP_NUMBER); } }
        public IField WS_COLL_TYPE { get { return GetElementByName<IField>(Names.WS_COLL_TYPE); } }
        public IGroup WS_STANDARD_DATE { get { return GetElementByName<IGroup>(Names.WS_STANDARD_DATE); } }
        public IField WS_STANDARD_CC { get { return GetElementByName<IField>(Names.WS_STANDARD_CC); } }
        public IField WS_STANDARD_YY { get { return GetElementByName<IField>(Names.WS_STANDARD_YY); } }
        public IField WS_STANDARD_MM { get { return GetElementByName<IField>(Names.WS_STANDARD_MM); } }
        public IField WS_STANDARD_DD { get { return GetElementByName<IField>(Names.WS_STANDARD_DD); } }
        public IGroup WS_INTERFACE_DATE { get { return GetElementByName<IGroup>(Names.WS_INTERFACE_DATE); } }
        public IField WS_INTERFACE_MM { get { return GetElementByName<IField>(Names.WS_INTERFACE_MM); } }
        public IField WS_INTERFACE_DD { get { return GetElementByName<IField>(Names.WS_INTERFACE_DD); } }
        public IField WS_INTERFACE_CC { get { return GetElementByName<IField>(Names.WS_INTERFACE_CC); } }
        public IField WS_INTERFACE_YY { get { return GetElementByName<IField>(Names.WS_INTERFACE_YY); } }
        public IField FUNC_0661701014_ESC_FLAG { get { return GetElementByName<IField>(Names.FUNC_0661701014_ESC_FLAG); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the WorkingStorage IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            WsExternals.Instance.CreateNewField(Names.SDSO_FILE_STATUS, FieldType.UnsignedNumeric, 2);

            recordDef.CreateNewGroup(Names.WS_INPUT_RESTART_INFO, (WS_INPUT_RESTART_INFO) =>
           {
               WS_INPUT_RESTART_INFO.CreateNewField(Names.WS_INPUT_SRC_CREATE_DT, FieldType.UnsignedNumeric, 8);
               WS_INPUT_RESTART_INFO.CreateNewField(Names.WS_INPUT_AP_NUMBER, FieldType.String, 10);
               WS_INPUT_RESTART_INFO.CreateNewField(Names.WS_INPUT_COLL_TYPE, FieldType.UnsignedNumeric, 1);
               WS_INPUT_RESTART_INFO.CreateNewFillerField(61, FillWith.Hashes);
           });

            recordDef.CreateNewGroup(Names.WS_FORMATTED_RESTART_INFO, (WS_FORMATTED_RESTART_INFO) =>
           {
               WS_FORMATTED_RESTART_INFO.CreateNewField(Names.WS_RECORD_TYPE, FieldType.String, 1, "1");
               WS_FORMATTED_RESTART_INFO.CreateNewGroup(Names.WS_SRC_CREATE_DATE, (WS_SRC_CREATE_DATE) =>
               {
                   WS_SRC_CREATE_DATE.CreateNewField(Names.WS_SRC_CREATE_MM, FieldType.UnsignedNumeric, 2);
                   WS_SRC_CREATE_DATE.CreateNewField(Names.WS_SRC_CREATE_DD, FieldType.UnsignedNumeric, 2);
                   WS_SRC_CREATE_DATE.CreateNewField(Names.WS_SRC_CREATE_CC, FieldType.UnsignedNumeric, 2);
                   WS_SRC_CREATE_DATE.CreateNewField(Names.WS_SRC_CREATE_YY, FieldType.UnsignedNumeric, 2);
               });
               WS_FORMATTED_RESTART_INFO.CreateNewField(Names.WS_AP_NUMBER, FieldType.String, 10);
               WS_FORMATTED_RESTART_INFO.CreateNewField(Names.WS_COLL_TYPE, FieldType.UnsignedNumeric, 1);
               WS_FORMATTED_RESTART_INFO.CreateNewFillerField(FieldType.String, 60, SPACES);
           });

            recordDef.CreateNewGroup(Names.WS_STANDARD_DATE, (WS_STANDARD_DATE) =>
           {
               WS_STANDARD_DATE.CreateNewField(Names.WS_STANDARD_CC, FieldType.UnsignedNumeric, 2);
               WS_STANDARD_DATE.CreateNewField(Names.WS_STANDARD_YY, FieldType.UnsignedNumeric, 2);
               WS_STANDARD_DATE.CreateNewField(Names.WS_STANDARD_MM, FieldType.UnsignedNumeric, 2);
               WS_STANDARD_DATE.CreateNewField(Names.WS_STANDARD_DD, FieldType.UnsignedNumeric, 2);
           });

            recordDef.CreateNewGroup(Names.WS_INTERFACE_DATE, (WS_INTERFACE_DATE) =>
           {
               WS_INTERFACE_DATE.CreateNewField(Names.WS_INTERFACE_MM, FieldType.UnsignedNumeric, 2);
               WS_INTERFACE_DATE.CreateNewField(Names.WS_INTERFACE_DD, FieldType.UnsignedNumeric, 2);
               WS_INTERFACE_DATE.CreateNewField(Names.WS_INTERFACE_CC, FieldType.UnsignedNumeric, 2);
               WS_INTERFACE_DATE.CreateNewField(Names.WS_INTERFACE_YY, FieldType.UnsignedNumeric, 2);
           });
            recordDef.CreateNewField(Names.FUNC_0661701014_ESC_FLAG, FieldType.String, 1);

        }

        protected override string GetRecordName()
        {
            return Names.WorkingStorage;
        }
        #endregion

    }
    #endregion Working Storage Class

    #region Linkage Section Class
    internal class SWEXFE98_ls : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string LinkageSection = "SWEXFE98_ls_LinkageSection";
            internal const string IEF_RUNTIME_PARM1 = "IEF_RUNTIME_PARM1";
            internal const string IEF_RUNTIME_PARM2 = "IEF_RUNTIME_PARM2";
            internal const string PSMGR_EAB_DATA = "PSMGR_EAB_DATA";
            internal const string PSMGR_EABPCB_CNT = "PSMGR_EABPCB_CNT";
            internal const string PSMGR_EABPCB_ENTRY = "PSMGR_EABPCB_ENTRY";
            internal const string PSMGR_EABPCB_ADR = "PSMGR_EABPCB_ADR";
            internal const string W_IA = "W_IA";
            internal const string A_0661701017_IA = "A_0661701017_IA";
            internal const string IMPORT_0001EV = "IMPORT_0001EV";
            internal const string EXTERNAL_0001ET = "EXTERNAL_0001ET";
            internal const string FILE_INSTRUCTION_0001AS = "FILE_INSTRUCTION_0001AS";
            internal const string FILE_INSTRUCTION_0001 = "FILE_INSTRUCTION_0001";
            internal const string FILE_INSTRUCTION_0001XX = "FILE_INSTRUCTION_0001XX";
            internal const string TEXT_LINE_80_0001AS = "TEXT_LINE_80_0001AS";
            internal const string TEXT_LINE_80_0001 = "TEXT_LINE_80_0001";
            internal const string TEXT_LINE_80_0001XX = "TEXT_LINE_80_0001XX";
            internal const string TEXT_RETURN_CODE_0001AS = "TEXT_RETURN_CODE_0001AS";
            internal const string TEXT_RETURN_CODE_0001 = "TEXT_RETURN_CODE_0001";
            internal const string TEXT_RETURN_CODE_0001XX = "TEXT_RETURN_CODE_0001XX";
            internal const string NUMERIC_RETURN_CODE_0001AS = "NUMERIC_RETURN_CODE_0001AS";
            internal const string NUMERIC_RETURN_CODE_0001 = "NUMERIC_RETURN_CODE_0001";
            internal const string NUMERIC_RETURN_CODE_0001XX = "NUMERIC_RETURN_CODE_0001XX";
            internal const string W_OA = "W_OA";
            internal const string A_0661701018_OA = "A_0661701018_OA";
            internal const string EXPORT_0002EV = "EXPORT_0002EV";
            internal const string EXTERNAL_0002ET = "EXTERNAL_0002ET";
            internal const string FILE_INSTRUCTION_0002AS = "FILE_INSTRUCTION_0002AS";
            internal const string FILE_INSTRUCTION_0002 = "FILE_INSTRUCTION_0002";
            internal const string FILE_INSTRUCTION_0002XX = "FILE_INSTRUCTION_0002XX";
            internal const string TEXT_LINE_80_0002AS = "TEXT_LINE_80_0002AS";
            internal const string TEXT_LINE_80_0002 = "TEXT_LINE_80_0002";
            internal const string TEXT_LINE_80_0002XX = "TEXT_LINE_80_0002XX";
            internal const string NUMERIC_RETURN_CODE_0002AS = "NUMERIC_RETURN_CODE_0002AS";
            internal const string NUMERIC_RETURN_CODE_0002 = "NUMERIC_RETURN_CODE_0002";
            internal const string NUMERIC_RETURN_CODE_0002XX = "NUMERIC_RETURN_CODE_0002XX";
            internal const string TEXT_RETURN_CODE_0002AS = "TEXT_RETURN_CODE_0002AS";
            internal const string TEXT_RETURN_CODE_0002 = "TEXT_RETURN_CODE_0002";
            internal const string TEXT_RETURN_CODE_0002XX = "TEXT_RETURN_CODE_0002XX";
            internal const string EXPORT_RECORD_TYPE_0003EV = "EXPORT_RECORD_TYPE_0003EV";
            internal const string IEF_SUPPLIED_0003ET = "IEF_SUPPLIED_0003ET";
            internal const string COUNT_0003AS = "COUNT_0003AS";
            internal const string COUNT_0003 = "COUNT_0003";
            internal const string COUNT_0003XX = "COUNT_0003XX";
            internal const string EXPORT_GROUP_HEADER_REC_0001GV = "EXPORT_GROUP_HEADER_REC_0001GV";
            internal const string EXPORT_GRP_DETAIL_0004EV = "EXPORT_GRP_DETAIL_0004EV";
            internal const string CASH_RECEIPT_EVENT_0004ET = "CASH_RECEIPT_EVENT_0004ET";
            internal const string SOURCE_CREATION_DATE_0004AS = "SOURCE_CREATION_DATE_0004AS";
            internal const string SOURCE_CREATION_DATE_0004 = "SOURCE_CREATION_DATE_0004";
            internal const string SOURCE_CREATION_DATE_0004XX = "SOURCE_CREATION_DATE_0004XX";
            internal const string EXPORT_GROUP_DETAIL_REC_0002GV = "EXPORT_GROUP_DETAIL_REC_0002GV";
            internal const string EXPORT_COLLECTION_TYPE_0005EV = "EXPORT_COLLECTION_TYPE_0005EV";
            internal const string IEF_SUPPLIED_0005ET = "IEF_SUPPLIED_0005ET";
            internal const string SELECT_CHAR_0005AS = "SELECT_CHAR_0005AS";
            internal const string SELECT_CHAR_0005 = "SELECT_CHAR_0005";
            internal const string SELECT_CHAR_0005XX = "SELECT_CHAR_0005XX";
            internal const string EXPORT_GRP_DETAIL_0006EV = "EXPORT_GRP_DETAIL_0006EV";
            internal const string CASH_RECEIPT_DETAIL_0006ET = "CASH_RECEIPT_DETAIL_0006ET";
            internal const string OBLIGOR_PERSON_NUMBER_0006AS = "OBLIGOR_PERSON_NUMBER_0006AS";
            internal const string OBLIGOR_PERSON_NUMBER_0006 = "OBLIGOR_PERSON_NUMBER_0006";
            internal const string OBLIGOR_PERSON_NUMBER_0006XX = "OBLIGOR_PERSON_NUMBER_0006XX";
            internal const string COLLECTION_AMOUNT_0006AS = "COLLECTION_AMOUNT_0006AS";
            internal const string COLLECTION_AMOUNT_0006 = "COLLECTION_AMOUNT_0006";
            internal const string COLLECTION_AMOUNT_0006XX = "COLLECTION_AMOUNT_0006XX";
            internal const string EXPORT_GROUP_TOTAL_RECO_0003GV = "EXPORT_GROUP_TOTAL_RECO_0003GV";
            internal const string EXPORT_GRP_DETAIL_TOTAL_0007EV = "EXPORT_GRP_DETAIL_TOTAL_0007EV";
            internal const string CASH_RECEIPT_EVENT_0007ET = "CASH_RECEIPT_EVENT_0007ET";
            internal const string TOTAL_NON_CASH_TRANSACT_0008AS = "TOTAL_NON_CASH_TRANSACT_0008AS";
            internal const string TOTAL_NON_CASH_TRANSACTIO_0008 = "TOTAL_NON_CASH_TRANSACTIO_0008";
            internal const string TOTAL_NON_CASH_TRANSACT_0008XX = "TOTAL_NON_CASH_TRANSACT_0008XX";
            internal const string TOTAL_NON_CASH_AMT_0008AS = "TOTAL_NON_CASH_AMT_0008AS";
            internal const string TOTAL_NON_CASH_AMT_0008 = "TOTAL_NON_CASH_AMT_0008";
            internal const string TOTAL_NON_CASH_AMT_0008XX = "TOTAL_NON_CASH_AMT_0008XX";
        }
        #endregion

        #region Direct-access element properties
        public IField IEF_RUNTIME_PARM1 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM1); } }
        public IField IEF_RUNTIME_PARM2 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM2); } }
        public IGroup PSMGR_EAB_DATA { get { return GetElementByName<IGroup>(Names.PSMGR_EAB_DATA); } }
        public IField PSMGR_EABPCB_CNT { get { return GetElementByName<IField>(Names.PSMGR_EABPCB_CNT); } }
        public IArrayElementAccessor<IGroup> PSMGR_EABPCB_ENTRY { get { return GetArrayElementAccessor<IGroup>(Names.PSMGR_EABPCB_ENTRY); } }
        public IArrayElementAccessor<IField> PSMGR_EABPCB_ADR { get { return GetArrayElementAccessor<IField>(Names.PSMGR_EABPCB_ADR); } }
        public IGroup W_IA { get { return GetElementByName<IGroup>(Names.W_IA); } }
        public IGroup A_0661701017_IA { get { return GetElementByName<IGroup>(Names.A_0661701017_IA); } }
        public IGroup IMPORT_0001EV { get { return GetElementByName<IGroup>(Names.IMPORT_0001EV); } }
        public IGroup EXTERNAL_0001ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_0001ET); } }
        public IField FILE_INSTRUCTION_0001AS { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0001AS); } }
        public IField FILE_INSTRUCTION_0001 { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0001); } }
        public IField FILE_INSTRUCTION_0001XX { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0001XX); } }
        public IField TEXT_LINE_80_0001AS { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0001AS); } }
        public IField TEXT_LINE_80_0001 { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0001); } }
        public IField TEXT_LINE_80_0001XX { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0001XX); } }
        public IField TEXT_RETURN_CODE_0001AS { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0001AS); } }
        public IField TEXT_RETURN_CODE_0001 { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0001); } }
        public IField TEXT_RETURN_CODE_0001XX { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0001XX); } }
        public IField NUMERIC_RETURN_CODE_0001AS { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0001AS); } }
        public IField NUMERIC_RETURN_CODE_0001 { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0001); } }
        public IField NUMERIC_RETURN_CODE_0001XX { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0001XX); } }
        public IGroup W_OA { get { return GetElementByName<IGroup>(Names.W_OA); } }
        public IGroup A_0661701018_OA { get { return GetElementByName<IGroup>(Names.A_0661701018_OA); } }
        public IGroup EXPORT_0002EV { get { return GetElementByName<IGroup>(Names.EXPORT_0002EV); } }
        public IGroup EXTERNAL_0002ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_0002ET); } }
        public IField FILE_INSTRUCTION_0002AS { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0002AS); } }
        public IField FILE_INSTRUCTION_0002 { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0002); } }
        public IField FILE_INSTRUCTION_0002XX { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0002XX); } }
        public IField TEXT_LINE_80_0002AS { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0002AS); } }
        public IField TEXT_LINE_80_0002 { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0002); } }
        public IField TEXT_LINE_80_0002XX { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0002XX); } }
        public IField NUMERIC_RETURN_CODE_0002AS { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0002AS); } }
        public IField NUMERIC_RETURN_CODE_0002 { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0002); } }
        public IField NUMERIC_RETURN_CODE_0002XX { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0002XX); } }
        public IField TEXT_RETURN_CODE_0002AS { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0002AS); } }
        public IField TEXT_RETURN_CODE_0002 { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0002); } }
        public IField TEXT_RETURN_CODE_0002XX { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0002XX); } }
        public IGroup EXPORT_RECORD_TYPE_0003EV { get { return GetElementByName<IGroup>(Names.EXPORT_RECORD_TYPE_0003EV); } }
        public IGroup IEF_SUPPLIED_0003ET { get { return GetElementByName<IGroup>(Names.IEF_SUPPLIED_0003ET); } }
        public IField COUNT_0003AS { get { return GetElementByName<IField>(Names.COUNT_0003AS); } }
        public IField COUNT_0003 { get { return GetElementByName<IField>(Names.COUNT_0003); } }
        public IField COUNT_0003XX { get { return GetElementByName<IField>(Names.COUNT_0003XX); } }
        public IGroup EXPORT_GROUP_HEADER_REC_0001GV { get { return GetElementByName<IGroup>(Names.EXPORT_GROUP_HEADER_REC_0001GV); } }
        public IGroup EXPORT_GRP_DETAIL_0004EV { get { return GetElementByName<IGroup>(Names.EXPORT_GRP_DETAIL_0004EV); } }
        public IGroup CASH_RECEIPT_EVENT_0004ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_EVENT_0004ET); } }
        public IField SOURCE_CREATION_DATE_0004AS { get { return GetElementByName<IField>(Names.SOURCE_CREATION_DATE_0004AS); } }
        public IField SOURCE_CREATION_DATE_0004 { get { return GetElementByName<IField>(Names.SOURCE_CREATION_DATE_0004); } }
        public IField SOURCE_CREATION_DATE_0004XX { get { return GetElementByName<IField>(Names.SOURCE_CREATION_DATE_0004XX); } }
        public IGroup EXPORT_GROUP_DETAIL_REC_0002GV { get { return GetElementByName<IGroup>(Names.EXPORT_GROUP_DETAIL_REC_0002GV); } }
        public IGroup EXPORT_COLLECTION_TYPE_0005EV { get { return GetElementByName<IGroup>(Names.EXPORT_COLLECTION_TYPE_0005EV); } }
        public IGroup IEF_SUPPLIED_0005ET { get { return GetElementByName<IGroup>(Names.IEF_SUPPLIED_0005ET); } }
        public IField SELECT_CHAR_0005AS { get { return GetElementByName<IField>(Names.SELECT_CHAR_0005AS); } }
        public IField SELECT_CHAR_0005 { get { return GetElementByName<IField>(Names.SELECT_CHAR_0005); } }
        public IField SELECT_CHAR_0005XX { get { return GetElementByName<IField>(Names.SELECT_CHAR_0005XX); } }
        public IGroup EXPORT_GRP_DETAIL_0006EV { get { return GetElementByName<IGroup>(Names.EXPORT_GRP_DETAIL_0006EV); } }
        public IGroup CASH_RECEIPT_DETAIL_0006ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_DETAIL_0006ET); } }
        public IField OBLIGOR_PERSON_NUMBER_0006AS { get { return GetElementByName<IField>(Names.OBLIGOR_PERSON_NUMBER_0006AS); } }
        public IField OBLIGOR_PERSON_NUMBER_0006 { get { return GetElementByName<IField>(Names.OBLIGOR_PERSON_NUMBER_0006); } }
        public IField OBLIGOR_PERSON_NUMBER_0006XX { get { return GetElementByName<IField>(Names.OBLIGOR_PERSON_NUMBER_0006XX); } }
        public IField COLLECTION_AMOUNT_0006AS { get { return GetElementByName<IField>(Names.COLLECTION_AMOUNT_0006AS); } }
        public IField COLLECTION_AMOUNT_0006 { get { return GetElementByName<IField>(Names.COLLECTION_AMOUNT_0006); } }
        public IField COLLECTION_AMOUNT_0006XX { get { return GetElementByName<IField>(Names.COLLECTION_AMOUNT_0006XX); } }
        public IGroup EXPORT_GROUP_TOTAL_RECO_0003GV { get { return GetElementByName<IGroup>(Names.EXPORT_GROUP_TOTAL_RECO_0003GV); } }
        public IGroup EXPORT_GRP_DETAIL_TOTAL_0007EV { get { return GetElementByName<IGroup>(Names.EXPORT_GRP_DETAIL_TOTAL_0007EV); } }
        public IGroup CASH_RECEIPT_EVENT_0007ET { get { return GetElementByName<IGroup>(Names.CASH_RECEIPT_EVENT_0007ET); } }
        public IField TOTAL_NON_CASH_TRANSACT_0008AS { get { return GetElementByName<IField>(Names.TOTAL_NON_CASH_TRANSACT_0008AS); } }
        public IField TOTAL_NON_CASH_TRANSACTIO_0008 { get { return GetElementByName<IField>(Names.TOTAL_NON_CASH_TRANSACTIO_0008); } }
        public IField TOTAL_NON_CASH_TRANSACT_0008XX { get { return GetElementByName<IField>(Names.TOTAL_NON_CASH_TRANSACT_0008XX); } }
        public IField TOTAL_NON_CASH_AMT_0008AS { get { return GetElementByName<IField>(Names.TOTAL_NON_CASH_AMT_0008AS); } }
        public IField TOTAL_NON_CASH_AMT_0008 { get { return GetElementByName<IField>(Names.TOTAL_NON_CASH_AMT_0008); } }
        public IField TOTAL_NON_CASH_AMT_0008XX { get { return GetElementByName<IField>(Names.TOTAL_NON_CASH_AMT_0008XX); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the LinkageSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM1, FieldType.String, 1);
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM2, FieldType.String, 1);

            recordDef.CreateNewGroup(Names.PSMGR_EAB_DATA, (PSMGR_EAB_DATA) =>
           {
               PSMGR_EAB_DATA.CreateNewField(Names.PSMGR_EABPCB_CNT, FieldType.CompInt, 9);
               PSMGR_EAB_DATA.CreateNewGroupArray(Names.PSMGR_EABPCB_ENTRY, 255, (PSMGR_EABPCB_ENTRY) =>
               {
                   PSMGR_EABPCB_ENTRY.CreateNewField(Names.PSMGR_EABPCB_ADR, FieldType.CompInt, 9);
               });
           });

            recordDef.CreateNewGroup(Names.W_IA, (W_IA) =>
           {
               W_IA.CreateNewGroup(Names.A_0661701017_IA, (A_0661701017_IA) =>
               {
                   A_0661701017_IA.CreateNewGroup(Names.IMPORT_0001EV, (IMPORT_0001EV) =>
                   {
                       IMPORT_0001EV.CreateNewGroup(Names.EXTERNAL_0001ET, (EXTERNAL_0001ET) =>
                       {
                           EXTERNAL_0001ET.CreateNewField(Names.FILE_INSTRUCTION_0001AS, FieldType.String, 1);

                           IField FILE_INSTRUCTION_0001_local = EXTERNAL_0001ET.CreateNewField(Names.FILE_INSTRUCTION_0001, FieldType.String, 10);
                           EXTERNAL_0001ET.CreateNewFieldRedefine(Names.FILE_INSTRUCTION_0001XX, FieldType.String, FILE_INSTRUCTION_0001_local, 10);
                           EXTERNAL_0001ET.CreateNewField(Names.TEXT_LINE_80_0001AS, FieldType.String, 1);

                           IField TEXT_LINE_80_0001_local = EXTERNAL_0001ET.CreateNewField(Names.TEXT_LINE_80_0001, FieldType.String, 130);
                           EXTERNAL_0001ET.CreateNewFieldRedefine(Names.TEXT_LINE_80_0001XX, FieldType.String, TEXT_LINE_80_0001_local, 130);
                           EXTERNAL_0001ET.CreateNewField(Names.TEXT_RETURN_CODE_0001AS, FieldType.String, 1);

                           IField TEXT_RETURN_CODE_0001_local = EXTERNAL_0001ET.CreateNewField(Names.TEXT_RETURN_CODE_0001, FieldType.String, 2);
                           EXTERNAL_0001ET.CreateNewFieldRedefine(Names.TEXT_RETURN_CODE_0001XX, FieldType.String, TEXT_RETURN_CODE_0001_local, 2);
                           EXTERNAL_0001ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0001AS, FieldType.String, 1);

                           IField NUMERIC_RETURN_CODE_0001_local = EXTERNAL_0001ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0001, FieldType.SignedNumeric, 2);
                           EXTERNAL_0001ET.CreateNewFieldRedefine(Names.NUMERIC_RETURN_CODE_0001XX, FieldType.String, NUMERIC_RETURN_CODE_0001_local, 2);
                       });
                   });
               });
           });

            recordDef.CreateNewGroup(Names.W_OA, (W_OA) =>
           {
               W_OA.CreateNewGroup(Names.A_0661701018_OA, (A_0661701018_OA) =>
               {
                   A_0661701018_OA.CreateNewGroup(Names.EXPORT_0002EV, (EXPORT_0002EV) =>
                   {
                       EXPORT_0002EV.CreateNewGroup(Names.EXTERNAL_0002ET, (EXTERNAL_0002ET) =>
                       {
                           EXTERNAL_0002ET.CreateNewField(Names.FILE_INSTRUCTION_0002AS, FieldType.String, 1);

                           IField FILE_INSTRUCTION_0002_local = EXTERNAL_0002ET.CreateNewField(Names.FILE_INSTRUCTION_0002, FieldType.String, 10);
                           EXTERNAL_0002ET.CreateNewFieldRedefine(Names.FILE_INSTRUCTION_0002XX, FieldType.String, FILE_INSTRUCTION_0002_local, 10);
                           EXTERNAL_0002ET.CreateNewField(Names.TEXT_LINE_80_0002AS, FieldType.String, 1);

                           IField TEXT_LINE_80_0002_local = EXTERNAL_0002ET.CreateNewField(Names.TEXT_LINE_80_0002, FieldType.String, 130);
                           EXTERNAL_0002ET.CreateNewFieldRedefine(Names.TEXT_LINE_80_0002XX, FieldType.String, TEXT_LINE_80_0002_local, 130);
                           EXTERNAL_0002ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0002AS, FieldType.String, 1);

                           IField NUMERIC_RETURN_CODE_0002_local = EXTERNAL_0002ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0002, FieldType.SignedNumeric, 2);
                           EXTERNAL_0002ET.CreateNewFieldRedefine(Names.NUMERIC_RETURN_CODE_0002XX, FieldType.String, NUMERIC_RETURN_CODE_0002_local, 2);
                           EXTERNAL_0002ET.CreateNewField(Names.TEXT_RETURN_CODE_0002AS, FieldType.String, 1);

                           IField TEXT_RETURN_CODE_0002_local = EXTERNAL_0002ET.CreateNewField(Names.TEXT_RETURN_CODE_0002, FieldType.String, 2);
                           EXTERNAL_0002ET.CreateNewFieldRedefine(Names.TEXT_RETURN_CODE_0002XX, FieldType.String, TEXT_RETURN_CODE_0002_local, 2);
                       });
                   });
                   A_0661701018_OA.CreateNewGroup(Names.EXPORT_RECORD_TYPE_0003EV, (EXPORT_RECORD_TYPE_0003EV) =>
                   {
                       EXPORT_RECORD_TYPE_0003EV.CreateNewGroup(Names.IEF_SUPPLIED_0003ET, (IEF_SUPPLIED_0003ET) =>
                       {
                           IEF_SUPPLIED_0003ET.CreateNewField(Names.COUNT_0003AS, FieldType.String, 1);

                           IField COUNT_0003_local = IEF_SUPPLIED_0003ET.CreateNewField(Names.COUNT_0003, FieldType.SignedNumeric, 9);
                           IEF_SUPPLIED_0003ET.CreateNewFieldRedefine(Names.COUNT_0003XX, FieldType.String, COUNT_0003_local, 9);
                       });
                   });
                   A_0661701018_OA.CreateNewGroup(Names.EXPORT_GROUP_HEADER_REC_0001GV, (EXPORT_GROUP_HEADER_REC_0001GV) =>
                   {
                       EXPORT_GROUP_HEADER_REC_0001GV.CreateNewGroup(Names.EXPORT_GRP_DETAIL_0004EV, (EXPORT_GRP_DETAIL_0004EV) =>
                       {
                           EXPORT_GRP_DETAIL_0004EV.CreateNewGroup(Names.CASH_RECEIPT_EVENT_0004ET, (CASH_RECEIPT_EVENT_0004ET) =>
                           {
                               CASH_RECEIPT_EVENT_0004ET.CreateNewField(Names.SOURCE_CREATION_DATE_0004AS, FieldType.String, 1);

                               IField SOURCE_CREATION_DATE_0004_local = CASH_RECEIPT_EVENT_0004ET.CreateNewField(Names.SOURCE_CREATION_DATE_0004, FieldType.UnsignedNumeric, 8);
                               CASH_RECEIPT_EVENT_0004ET.CreateNewFieldRedefine(Names.SOURCE_CREATION_DATE_0004XX, FieldType.String, SOURCE_CREATION_DATE_0004_local, 8);
                           });
                       });
                   });
                   A_0661701018_OA.CreateNewGroup(Names.EXPORT_GROUP_DETAIL_REC_0002GV, (EXPORT_GROUP_DETAIL_REC_0002GV) =>
                   {
                       EXPORT_GROUP_DETAIL_REC_0002GV.CreateNewGroup(Names.EXPORT_COLLECTION_TYPE_0005EV, (EXPORT_COLLECTION_TYPE_0005EV) =>
                       {
                           EXPORT_COLLECTION_TYPE_0005EV.CreateNewGroup(Names.IEF_SUPPLIED_0005ET, (IEF_SUPPLIED_0005ET) =>
                           {
                               IEF_SUPPLIED_0005ET.CreateNewField(Names.SELECT_CHAR_0005AS, FieldType.String, 1);

                               IField SELECT_CHAR_0005_local = IEF_SUPPLIED_0005ET.CreateNewField(Names.SELECT_CHAR_0005, FieldType.String, 1);
                               IEF_SUPPLIED_0005ET.CreateNewFieldRedefine(Names.SELECT_CHAR_0005XX, FieldType.String, SELECT_CHAR_0005_local, 1);
                           });
                       });
                       EXPORT_GROUP_DETAIL_REC_0002GV.CreateNewGroup(Names.EXPORT_GRP_DETAIL_0006EV, (EXPORT_GRP_DETAIL_0006EV) =>
                       {
                           EXPORT_GRP_DETAIL_0006EV.CreateNewGroup(Names.CASH_RECEIPT_DETAIL_0006ET, (CASH_RECEIPT_DETAIL_0006ET) =>
                           {
                               CASH_RECEIPT_DETAIL_0006ET.CreateNewField(Names.OBLIGOR_PERSON_NUMBER_0006AS, FieldType.String, 1);

                               IField OBLIGOR_PERSON_NUMBER_0006_local = CASH_RECEIPT_DETAIL_0006ET.CreateNewField(Names.OBLIGOR_PERSON_NUMBER_0006, FieldType.String, 10);
                               CASH_RECEIPT_DETAIL_0006ET.CreateNewFieldRedefine(Names.OBLIGOR_PERSON_NUMBER_0006XX, FieldType.String, OBLIGOR_PERSON_NUMBER_0006_local, 10);
                               CASH_RECEIPT_DETAIL_0006ET.CreateNewField(Names.COLLECTION_AMOUNT_0006AS, FieldType.String, 1);

                               IField COLLECTION_AMOUNT_0006_local = CASH_RECEIPT_DETAIL_0006ET.CreateNewField(Names.COLLECTION_AMOUNT_0006, FieldType.SignedNumeric, 9, null, 2);
                               CASH_RECEIPT_DETAIL_0006ET.CreateNewFieldRedefine(Names.COLLECTION_AMOUNT_0006XX, FieldType.String, COLLECTION_AMOUNT_0006_local, 9);
                           });
                       });
                   });
                   A_0661701018_OA.CreateNewGroup(Names.EXPORT_GROUP_TOTAL_RECO_0003GV, (EXPORT_GROUP_TOTAL_RECO_0003GV) =>
                   {
                       EXPORT_GROUP_TOTAL_RECO_0003GV.CreateNewGroup(Names.EXPORT_GRP_DETAIL_TOTAL_0007EV, (EXPORT_GRP_DETAIL_TOTAL_0007EV) =>
                       {
                           EXPORT_GRP_DETAIL_TOTAL_0007EV.CreateNewGroup(Names.CASH_RECEIPT_EVENT_0007ET, (CASH_RECEIPT_EVENT_0007ET) =>
                           {
                               CASH_RECEIPT_EVENT_0007ET.CreateNewField(Names.TOTAL_NON_CASH_TRANSACT_0008AS, FieldType.String, 1);

                               IField TOTAL_NON_CASH_TRANSACTIO_0008_local = CASH_RECEIPT_EVENT_0007ET.CreateNewField(Names.TOTAL_NON_CASH_TRANSACTIO_0008, FieldType.SignedNumeric, 7);
                               CASH_RECEIPT_EVENT_0007ET.CreateNewFieldRedefine(Names.TOTAL_NON_CASH_TRANSACT_0008XX, FieldType.String, TOTAL_NON_CASH_TRANSACTIO_0008_local, 7);
                               CASH_RECEIPT_EVENT_0007ET.CreateNewField(Names.TOTAL_NON_CASH_AMT_0008AS, FieldType.String, 1);

                               IField TOTAL_NON_CASH_AMT_0008_local = CASH_RECEIPT_EVENT_0007ET.CreateNewField(Names.TOTAL_NON_CASH_AMT_0008, FieldType.SignedNumeric, 9, null, 2);
                               CASH_RECEIPT_EVENT_0007ET.CreateNewFieldRedefine(Names.TOTAL_NON_CASH_AMT_0008XX, FieldType.String, TOTAL_NON_CASH_AMT_0008_local, 9);
                           });
                       });
                   });
               });
           });

        }

        protected override string GetRecordName()
        {
            return Names.LinkageSection;
        }
        #endregion

        public void SetPassedParameters(object[] args)
        {
            SetPassedParm(IEF_RUNTIME_PARM1, args, 0);
            SetPassedParm(IEF_RUNTIME_PARM2, args, 1);
            SetPassedParm(W_IA, args, 2);
            SetPassedParm(W_OA, args, 3);
            SetPassedParm(PSMGR_EAB_DATA, args, 4);
        }


        public void UpdateReturnParameters(object[] args)
        {
            SetReturnParm(IEF_RUNTIME_PARM1, args, 0);
            SetReturnParm(IEF_RUNTIME_PARM2, args, 1);
            SetReturnParm(W_IA, args, 2);
            SetReturnParm(W_OA, args, 3);
            SetReturnParm(PSMGR_EAB_DATA, args, 4);
        }
    }
    #endregion Linkage Section Class

    #region Business Logic Class
    public class SWEXFE98 : EABBase
    {

        #region Public Constructors
        public SWEXFE98()
            : base()
        {
            this.ProgramName.SetValue("SWEXFE98");

            WS = new SWEXFE98_ws();
            FD = new SWEXFE98_fd(WS);
            LS = new SWEXFE98_ls();
        }

        #endregion

        #region Private Fields


        //==== Working Storage Data Class ========================================
        private SWEXFE98_ws WS;

        //==== File Data Class ========================================
        private SWEXFE98_fd FD;

        //==== Linkage Section Data Class ========================================
        private SWEXFE98_ls LS;
        #endregion

        #region Public Methods
        //========================================================================
        //==== RunMain Entry Point Method ========================================
        //========================================================================
        public override int ExecuteMain(params object[] args)                                              //COBOL==> PROCEDURE DIVISION USING IEF-RUNTIME-PARM1 , IEF-RUNTIME-PARM2 , W-IA , W-OA , PSMGR-EAB-DATA.
        {
            try
            {
                WS.Initialize();
                LS.SetPassedParameters(args);
                RunMain();
                LS.UpdateReturnParameters(args);
                return Return_Code.AsInt();
            }
            catch (Exception ex)
            {
                Control.ReturnException(ex);
                return 12;
            }
        }
        #endregion

        #region Private Methods

        private void RunMain()
        {
            string returnMethod = "Main";
            // Execute Procedure Division Logic
            M_MAIN_0661701014(returnMethod);
        }
        /// <summary>
        /// Method M_MAIN_0661701014
        /// </summary>
        private void M_MAIN_0661701014(string returnMethod = "")
        {
            M_PARA_0661701014_INIT("M_PARA_0661701014_INIT_EXIT"); if (Control.ExitProgram) { return; }           //COBOL==> PERFORM PARA-0661701014-INIT THRU PARA-0661701014-INIT-EXIT
            M_PARA_0661701014("M_PARA_0661701014_EXIT"); if (Control.ExitProgram) { return; }                     //COBOL==> PERFORM PARA-0661701014 THRU PARA-0661701014-EXIT
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_PARA_0661701014
        /// </summary>
        private void M_PARA_0661701014(string returnMethod = "")
        {
            WS.FUNC_0661701014_ESC_FLAG.SetValue("N");                                                          //COBOL==> MOVE 'N' TO FUNC-0661701014-ESC-FLAG.
            if (returnMethod != "" && returnMethod != "M_PARA_0661701014") { M_0000_MAINLINE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_0000_MAINLINE
        /// </summary>
        /// <remarks>
        ///COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
        ///COMMENT:    USER-WRITTEN CODE SHOULD BE INSERTED HERE
        ///COMMENT:  * * * * * * * * * * * * * * * * * * * * * *
        ///COMMENT: ********************
        /// </remarks>
        private void M_0000_MAINLINE(string returnMethod = "")
        {
            //COMMENT: ********************
            LS.TEXT_RETURN_CODE_0002.SetValue("00");                                                            //COBOL==> MOVE '00' TO TEXT-RETURN-CODE-0002.
                                                                                                                // EvaluateList !LS.FILE_INSTRUCTION_0001!                                                          //COBOL==> EVALUATE FILE-INSTRUCTION-0001
            if ((LS.FILE_INSTRUCTION_0001.IsEqualTo("OPEN")))                                                   //COBOL==> WHEN 'OPEN'
            {
                M_1000_OPEN_FILE(); if (Control.ExitProgram) { return; }                                              //COBOL==> PERFORM 1000-OPEN-FILE
            }                                                                                                //COBOL==> WHEN 'READ'
            else
            if ((LS.FILE_INSTRUCTION_0001.IsEqualTo("READ")))
            {
                M_2000_READ_FILE(); if (Control.ExitProgram) { return; }                                              //COBOL==> PERFORM 2000-READ-FILE
            }                                                                                                //COBOL==> WHEN 'POSITION'
            else
            if ((LS.FILE_INSTRUCTION_0001.IsEqualTo("POSITION")))
            {
                M_1000_OPEN_FILE(); if (Control.ExitProgram) { return; }                                              //COBOL==> PERFORM 1000-OPEN-FILE
                if (LS.TEXT_RETURN_CODE_0002.IsEqualTo("00"))                                                       //COBOL==> IF TEXT-RETURN-CODE-0002 = '00'
                {
                    M_3000_POSITION_FILE(); if (Control.ExitProgram) { return; }                                          //COBOL==> PERFORM 3000-POSITION-FILE
                }                                                                                                   //COBOL==> END-IF
            }                                                                                                //COBOL==> WHEN OTHER
            else
            {
                LS.TEXT_RETURN_CODE_0002.SetValue("BI");                                                            //COBOL==> MOVE 'BI' TO TEXT-RETURN-CODE-0002
            }                                                                                                   //COBOL==> END-EVALUATE.
            M_9999_FINISHED(CheckGotoReturn(returnMethod)); return;                                             //COBOL==> GO TO 9999-FINISHED.
        }
        /// <summary>
        /// Method M_1000_OPEN_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT: ****************
        /// </remarks>
        private void M_1000_OPEN_FILE(string returnMethod = "")
        {
            //COMMENT: ****************
            FD.SDSO_INPUT_FILE.OpenFile(FileAccessMode.Read);                                                   //COBOL==> OPEN INPUT SDSO-INPUT-FILE
            if (WS.SDSO_FILE_STATUS.IsEqualTo(00))                                                              //COBOL==> IF SDSO-FILE-STATUS = 00
            {
                LS.TEXT_RETURN_CODE_0002.SetValue("00");                                                            //COBOL==> MOVE '00' TO TEXT-RETURN-CODE-0002
            }                                                                                                   //COBOL==> ELSE
            else
            {
                LS.TEXT_RETURN_CODE_0002.SetValue("PE");                                                            //COBOL==> MOVE 'PE' TO TEXT-RETURN-CODE-0002
            }                                                                                                   //COBOL==> END-IF.
            if (returnMethod != "" && returnMethod != "M_1000_OPEN_FILE") { M_2000_READ_FILE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_2000_READ_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT: ****************
        /// </remarks>
        private void M_2000_READ_FILE(string returnMethod = "")
        {
            //COMMENT: ****************
            FD.SDSO_INPUT_FILE.ReadLine();                                                                      //COBOL==> READ SDSO-INPUT-FILE
                                                                                                                // EvaluateList !WS.SDSO_FILE_STATUS!                                                               //COBOL==> EVALUATE SDSO-FILE-STATUS
            if ((WS.SDSO_FILE_STATUS.IsZeroes()))                                                               //COBOL==> WHEN 00
            {
                // EvaluateList !FD.SDSO_RECORD_TYPE!                                                               //COBOL==> EVALUATE SDSO-RECORD-TYPE OF HEADER-RECORD
                if ((FD.SDSO_RECORD_TYPE.IsEqualTo("1")))                                                           //COBOL==> WHEN '1'
                {
                    LS.COUNT_0003.SetValue(FD.SDSO_RECORD_TYPE);                                                        //COBOL==> MOVE SDSO-RECORD-TYPE OF HEADER-RECORD TO COUNT-0003
                    WS.WS_STANDARD_CC.SetValue(FD.SDSO_SRC_CREATE_CC);                                                  //COBOL==> MOVE SDSO-SRC-CREATE-CC TO WS-STANDARD-CC
                    WS.WS_STANDARD_YY.SetValue(FD.SDSO_SRC_CREATE_YY);                                                  //COBOL==> MOVE SDSO-SRC-CREATE-YY TO WS-STANDARD-YY
                    WS.WS_STANDARD_MM.SetValue(FD.SDSO_SRC_CREATE_MM);                                                  //COBOL==> MOVE SDSO-SRC-CREATE-MM TO WS-STANDARD-MM
                    WS.WS_STANDARD_DD.SetValue(FD.SDSO_SRC_CREATE_DD);                                                  //COBOL==> MOVE SDSO-SRC-CREATE-DD TO WS-STANDARD-DD
                    LS.SOURCE_CREATION_DATE_0004.SetValue(WS.WS_STANDARD_DATE);                                         //COBOL==> MOVE WS-STANDARD-DATE TO SOURCE-CREATION-DATE-0004
                }                                                                                                //COBOL==> WHEN '2'
                else
                if ((FD.SDSO_RECORD_TYPE.IsEqualTo("2")))
                {
                    LS.COUNT_0003.SetValue(FD.SDSO_RECORD_TYPE_d2);                                                     //COBOL==> MOVE SDSO-RECORD-TYPE OF DETAIL-RECORD TO COUNT-0003
                    LS.OBLIGOR_PERSON_NUMBER_0006.SetValue(FD.SDSO_AP_NUMBER);                                          //COBOL==> MOVE SDSO-AP-NUMBER OF DETAIL-RECORD TO OBLIGOR-PERSON-NUMBER-0006
                    LS.COLLECTION_AMOUNT_0006.SetValue(FD.SDSO_PAYMENT_AMT);                                            //COBOL==> MOVE SDSO-PAYMENT-AMT TO COLLECTION-AMOUNT-0006
                    LS.SELECT_CHAR_0005.SetValue(FD.SDSO_COLL_TYPE);                                                    //COBOL==> MOVE SDSO-COLL-TYPE TO SELECT-CHAR-0005
                }                                                                                                //COBOL==> WHEN '3'
                else
                if ((FD.SDSO_RECORD_TYPE.IsEqualTo("3")))
                {
                    LS.COUNT_0003.SetValue(FD.SDSO_RECORD_TYPE_d3);                                                     //COBOL==> MOVE SDSO-RECORD-TYPE OF TOTAL-RECORD TO COUNT-0003
                    LS.TOTAL_NON_CASH_TRANSACTIO_0008.SetValue(FD.SDSO_RECORD_COUNT);                                   //COBOL==> MOVE SDSO-RECORD-COUNT TO TOTAL-NON-CASH-TRANSACTIO-0008
                    LS.TOTAL_NON_CASH_AMT_0008.SetValue(FD.SDSO_TOTAL_AMOUNT);                                          //COBOL==> MOVE SDSO-TOTAL-AMOUNT TO TOTAL-NON-CASH-AMT-0008
                }                                                                                                //COBOL==> WHEN OTHER
                else
                {
                    LS.TEXT_RETURN_CODE_0002.SetValue("IC");                                                            //COBOL==> MOVE 'IC' TO TEXT-RETURN-CODE-0002
                    M_4000_CLOSE_FILE(); if (Control.ExitProgram) { return; }                                             //COBOL==> PERFORM 4000-CLOSE-FILE
                }                                                                                                   //COBOL==> END-EVALUATE
            }                                                                                                //COBOL==> WHEN 10
            else
            if ((WS.SDSO_FILE_STATUS.IsEqualTo(10)))
            {
                LS.TEXT_RETURN_CODE_0002.SetValue("EF");                                                            //COBOL==> MOVE 'EF' TO TEXT-RETURN-CODE-0002
                M_4000_CLOSE_FILE(); if (Control.ExitProgram) { return; }                                             //COBOL==> PERFORM 4000-CLOSE-FILE
            }                                                                                                //COBOL==> WHEN OTHER
            else
            {
                LS.TEXT_RETURN_CODE_0002.SetValue("BR");                                                            //COBOL==> MOVE 'BR' TO TEXT-RETURN-CODE-0002
                M_4000_CLOSE_FILE(); if (Control.ExitProgram) { return; }                                             //COBOL==> PERFORM 4000-CLOSE-FILE
            }                                                                                                   //COBOL==> END-EVALUATE.
            if (returnMethod != "" && returnMethod != "M_2000_READ_FILE") { M_3000_POSITION_FILE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_3000_POSITION_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT: ****************
        /// </remarks>
        private void M_3000_POSITION_FILE(string returnMethod = "")
        {
            //COMMENT: ****************
            WS.WS_INPUT_RESTART_INFO.SetValue(LS.TEXT_LINE_80_0001);                                            //COBOL==> MOVE TEXT-LINE-80-0001 TO WS-INPUT-RESTART-INFO
            WS.WS_STANDARD_DATE.SetValue(WS.WS_INPUT_SRC_CREATE_DT);                                            //COBOL==> MOVE WS-INPUT-SRC-CREATE-DT TO WS-STANDARD-DATE
            WS.WS_INTERFACE_CC.SetValue(WS.WS_STANDARD_CC);                                                     //COBOL==> MOVE WS-STANDARD-CC TO WS-INTERFACE-CC
            WS.WS_INTERFACE_YY.SetValue(WS.WS_STANDARD_YY);                                                     //COBOL==> MOVE WS-STANDARD-YY TO WS-INTERFACE-YY
            WS.WS_INTERFACE_MM.SetValue(WS.WS_STANDARD_MM);                                                     //COBOL==> MOVE WS-STANDARD-MM TO WS-INTERFACE-MM
            WS.WS_INTERFACE_DD.SetValue(WS.WS_STANDARD_DD);                                                     //COBOL==> MOVE WS-STANDARD-DD TO WS-INTERFACE-DD
            WS.WS_SRC_CREATE_DATE.SetValue(WS.WS_INTERFACE_DATE);                                               //COBOL==> MOVE WS-INTERFACE-DATE TO WS-SRC-CREATE-DATE
            WS.WS_AP_NUMBER.SetValue(WS.WS_INPUT_AP_NUMBER);                                                    //COBOL==> MOVE WS-INPUT-AP-NUMBER TO WS-AP-NUMBER
            WS.WS_COLL_TYPE.SetValue(WS.WS_INPUT_COLL_TYPE);                                                    //COBOL==> MOVE WS-INPUT-COLL-TYPE TO WS-COLL-TYPE
            while (!((FD.HEADER_RECORD.IsEqualTo(WS.WS_FORMATTED_RESTART_INFO)) || (!(LS.TEXT_RETURN_CODE_0002.IsEqualTo("00")))))  //COBOL==> PERFORM UNTIL HEADER-RECORD = WS-FORMATTED-RESTART-INFO OR TEXT-RETURN-CODE-0002 NOT = '00'
            {
                FD.SDSO_INPUT_FILE.ReadLine();                                                                      //COBOL==> READ SDSO-INPUT-FILE
                                                                                                                    // EvaluateList !WS.SDSO_FILE_STATUS!                                                               //COBOL==> EVALUATE SDSO-FILE-STATUS
                if ((WS.SDSO_FILE_STATUS.IsZeroes()))                                                               //COBOL==> WHEN 00
                {
                    //Continue                                                                                          //COBOL==> CONTINUE
                }                                                                                                //COBOL==> WHEN 10
                else
                if ((WS.SDSO_FILE_STATUS.IsEqualTo(10)))
                {
                    LS.TEXT_RETURN_CODE_0002.SetValue("EF");                                                            //COBOL==> MOVE 'EF' TO TEXT-RETURN-CODE-0002
                }                                                                                                //COBOL==> WHEN OTHER
                else
                {
                    LS.TEXT_RETURN_CODE_0002.SetValue("BR");                                                            //COBOL==> MOVE 'BR' TO TEXT-RETURN-CODE-0002
                }                                                                                                   //COBOL==> END-EVALUATE
            }                                                                                                   //COBOL==> END-PERFORM.
            if (LS.TEXT_RETURN_CODE_0002.IsEqualTo("EF"))                                                       //COBOL==> IF TEXT-RETURN-CODE-0002 = 'EF'
            {
                M_4000_CLOSE_FILE(); if (Control.ExitProgram) { return; }                                             //COBOL==> PERFORM 4000-CLOSE-FILE
            }                                                                                                   //COBOL==> END-IF.
            if (returnMethod != "" && returnMethod != "M_3000_POSITION_FILE") { M_4000_CLOSE_FILE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_4000_CLOSE_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT: ****************
        /// </remarks>
        private void M_4000_CLOSE_FILE(string returnMethod = "")
        {
            //COMMENT: ****************
            FD.SDSO_INPUT_FILE.CloseFile();                                                                     //COBOL==> CLOSE SDSO-INPUT-FILE.
            if (returnMethod != "" && returnMethod != "M_4000_CLOSE_FILE") { M_9999_FINISHED(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_9999_FINISHED
        /// </summary>
        /// <remarks>
        ///COMMENT: ****************
        /// </remarks>
        private void M_9999_FINISHED(string returnMethod = "")
        {
            //COMMENT: ****************
            if (returnMethod == "M_9999_FINISHED") { return; }                                                  //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_9999_FINISHED") { M_PARA_0661701014_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0661701014_EXIT
        /// </summary>
        private void M_PARA_0661701014_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0661701014_EXIT") { return; }                                           //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0661701014_EXIT") { M_PARA_0661701014_INIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0661701014_INIT
        /// </summary>
        private void M_PARA_0661701014_INIT(string returnMethod = "")
        {
            LS.EXPORT_RECORD_TYPE_0003EV.ResetToInitialValue();                                                 //COBOL==> INITIALIZE EXPORT-RECORD-TYPE-0003EV
            LS.EXPORT_GROUP_HEADER_REC_0001GV.ResetToInitialValue();                                            //COBOL==> INITIALIZE EXPORT-GROUP-HEADER-REC-0001GV
            LS.EXPORT_GROUP_DETAIL_REC_0002GV.ResetToInitialValue();                                            //COBOL==> INITIALIZE EXPORT-GROUP-DETAIL-REC-0002GV
            LS.EXPORT_GROUP_TOTAL_RECO_0003GV.ResetToInitialValue();                                            //COBOL==> INITIALIZE EXPORT-GROUP-TOTAL-RECO-0003GV .
            if (returnMethod != "" && returnMethod != "M_PARA_0661701014_INIT") { M_PARA_0661701014_INIT_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0661701014_INIT_EXIT
        /// </summary>
        private void M_PARA_0661701014_INIT_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0661701014_INIT_EXIT") { return; }                                      //COBOL==> EXIT.
        }
        #endregion
    }
    #endregion
}
