#region Comments
/* Conversion Comments
   ************************************************************
   **   MODERN SYSTEMS INC.  COPYRIGHT 2000-2022
   **   DB-SHUTTLE COBOL to C# Conversion
   ************************************************************
   ** INIT   *  INITIAL VERSION   *  2022-03-02 04:42:49 PM
   **        *   FROM COBOL PGM   :  SWEXEE04
   **        *   FROM CANISTER    :  SR.CAECSES.PROD.LIBR.SOURCE.PDS
   ************************************************************ */

/* Original Program Identification Comments
   **************************************************************
                       SOURCE CODE GENERATED BY
                   INFORMATION ENGINEERING FACILITY (TM)
                       TEXAS INSTRUMENTS INC.
                COPYRIGHT (C) TEXAS INSTRUMENTS INC. 1997
       NAME: OE_FPLS_EAB_SEND_FPLS_REQUEST    DATE: 97/09/12
       TARGET OS:   MVS                       TIME: 09:14:38
       TARGET DBMS: DB2                       USER: SWDPGPK
       GENERATION OPTIONS:
       DEBUG TRACE OPTION NOT SELECTED
       DATA MODELING CONSTRAINT ENFORCEMENT NOT SELECTED
       OPTIMIZED IMPORT VIEW INITIALIZATION SELECTED
   **************************************************************
*/
#endregion
#region Using Directives
using System;
using System.Data;
using System.Collections.Generic;
using MDSY.Framework.IO.Common;
using MDSY.Framework.Buffer;
using MDSY.Framework.Buffer.BaseClasses;
using MDSY.Framework.Buffer.Interfaces;
using MDSY.Framework.Buffer.Common;
using MDSY.Framework.Core;
using MDSY.Framework.Data.SQL;
using MDSY.Framework.Interfaces;
using GOV.KS.DCF.CSS.Common.BL;
using MDSY.Framework.IO.Common;

/*  usings for referenced objects  */
using GOV.KS.DCF.CSS.Common.BL;
#endregion

namespace GOV.KS.DCF.CSS.Batch.BL
{
    #region File Section Class
    internal class SWEXEE04_fd : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string FileSection = "SWEXEE04_fd_FileSection";
            internal const string EXTFILE = "EXTFILE";
            internal const string EXTFILE_RECORD = "EXTFILE_RECORD";
        }
        #endregion

        #region Direct-access element properties
        public IFileLink EXTFILE { get; set; }
        public IField EXTFILE_RECORD { get { return GetElementByName<IField>(Names.EXTFILE_RECORD); } }


        internal SWEXEE04_ws WS;
        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the FileSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.EXTFILE_RECORD, FieldType.String, 335);

        }

        protected override string GetRecordName()
        {
            return Names.FileSection;
        }
        #endregion

        #region Initialize
        public override void Initialize()
        {
            InitializeWithLowValues();
            IFileHandler FileHandler = InversionContainer.GetImplementingObject<IFileHandler>();

            EXTFILE = FileHandler.GetFile("EXTFILE");
            EXTFILE.StatusField = WS.SWCSZE19.EXTFILE_STAT;
            EXTFILE.AssociatedBuffer = EXTFILE_RECORD;
        }
        #endregion

        #region Constructors
        public SWEXEE04_fd(SWEXEE04_ws ws)
            : base()
        {
            this.WS = ws;
            Initialize();

        }
        #endregion
    }
    #endregion File Section Class
    #region Working Storage Class
    internal class SWEXEE04_ws : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string WorkingStorage = "SWEXEE04_ws_WorkingStorage";
            internal const string FUNC_0656686762_ESC_FLAG = "FUNC_0656686762_ESC_FLAG";
        }
        #endregion

        #region Direct-access element properties
        public IField FUNC_0656686762_ESC_FLAG { get { return GetElementByName<IField>(Names.FUNC_0656686762_ESC_FLAG); } }

        public CPY_SWCSZE19 SWCSZE19 = new CPY_SWCSZE19(null, true);
        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the WorkingStorage IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.FUNC_0656686762_ESC_FLAG, FieldType.String, 1);


        }

        protected override string GetRecordName()
        {
            return Names.WorkingStorage;
        }
        #endregion

        #region Initialize
        public override void Initialize()
        {
            InitializeWithLowValues();
            SWCSZE19.InitializeWithLowValues();
        }
        #endregion

    }
    #endregion Working Storage Class

    #region Linkage Section Class
    internal class SWEXEE04_ls : PredefinedRecordBase
    {
        #region Name constants
        /// <summary>
        /// Name constants.
        /// </summary>
        internal static class Names
        {
            internal const string LinkageSection = "SWEXEE04_ls_LinkageSection";
            internal const string IEF_RUNTIME_PARM1 = "IEF_RUNTIME_PARM1";
            internal const string IEF_RUNTIME_PARM2 = "IEF_RUNTIME_PARM2";
            internal const string PSMGR_EAB_DATA = "PSMGR_EAB_DATA";
            internal const string PSMGR_EABPCB_CNT = "PSMGR_EABPCB_CNT";
            internal const string PSMGR_EABPCB_ENTRY = "PSMGR_EABPCB_ENTRY";
            internal const string PSMGR_EABPCB_ADR = "PSMGR_EABPCB_ADR";
            internal const string W_IA = "W_IA";
            internal const string A_0656686765_IA = "A_0656686765_IA";
            internal const string IMPORT_0001EV = "IMPORT_0001EV";
            internal const string EXTERNAL_FPLS_HEADER_0001ET = "EXTERNAL_FPLS_HEADER_0001ET";
            internal const string SPACES_1_0001AS = "SPACES_1_0001AS";
            internal const string SPACES_1_0001 = "SPACES_1_0001";
            internal const string SPACES_1_0001XX = "SPACES_1_0001XX";
            internal const string STATE_CODE_0001AS = "STATE_CODE_0001AS";
            internal const string STATE_CODE_0001 = "STATE_CODE_0001";
            internal const string STATE_CODE_0001XX = "STATE_CODE_0001XX";
            internal const string STATION_NUMBER_0001AS = "STATION_NUMBER_0001AS";
            internal const string STATION_NUMBER_0001 = "STATION_NUMBER_0001";
            internal const string STATION_NUMBER_0001XX = "STATION_NUMBER_0001XX";
            internal const string SPACES_2_0001AS = "SPACES_2_0001AS";
            internal const string SPACES_2_0001 = "SPACES_2_0001";
            internal const string SPACES_2_0001XX = "SPACES_2_0001XX";
            internal const string FPLS_HEADER_CONSTANT_0001AS = "FPLS_HEADER_CONSTANT_0001AS";
            internal const string FPLS_HEADER_CONSTANT_0001 = "FPLS_HEADER_CONSTANT_0001";
            internal const string FPLS_HEADER_CONSTANT_0001XX = "FPLS_HEADER_CONSTANT_0001XX";
            internal const string TOTAL_RESPONSES_0001AS = "TOTAL_RESPONSES_0001AS";
            internal const string TOTAL_RESPONSES_0001 = "TOTAL_RESPONSES_0001";
            internal const string TOTAL_RESPONSES_0001XX = "TOTAL_RESPONSES_0001XX";
            internal const string FPLS_SORT_CODE_0001AS = "FPLS_SORT_CODE_0001AS";
            internal const string FPLS_SORT_CODE_0001 = "FPLS_SORT_CODE_0001";
            internal const string FPLS_SORT_CODE_0001XX = "FPLS_SORT_CODE_0001XX";
            internal const string MM_DATE_GENERATED_0001AS = "MM_DATE_GENERATED_0001AS";
            internal const string MM_DATE_GENERATED_0001 = "MM_DATE_GENERATED_0001";
            internal const string MM_DATE_GENERATED_0001XX = "MM_DATE_GENERATED_0001XX";
            internal const string DD_DATE_GENERATED_0001AS = "DD_DATE_GENERATED_0001AS";
            internal const string DD_DATE_GENERATED_0001 = "DD_DATE_GENERATED_0001";
            internal const string DD_DATE_GENERATED_0001XX = "DD_DATE_GENERATED_0001XX";
            internal const string YY_DATE_GENERATED_0001AS = "YY_DATE_GENERATED_0001AS";
            internal const string YY_DATE_GENERATED_0001 = "YY_DATE_GENERATED_0001";
            internal const string YY_DATE_GENERATED_0001XX = "YY_DATE_GENERATED_0001XX";
            internal const string SPACES_3_0001AS = "SPACES_3_0001AS";
            internal const string SPACES_3_0001 = "SPACES_3_0001";
            internal const string SPACES_3_0001XX = "SPACES_3_0001XX";
            internal const string SPACES_4_0001AS = "SPACES_4_0001AS";
            internal const string SPACES_4_0001 = "SPACES_4_0001";
            internal const string SPACES_4_0001XX = "SPACES_4_0001XX";
            internal const string IMPORT_0002EV = "IMPORT_0002EV";
            internal const string EXTERNAL_FPLS_REQUEST_0002ET = "EXTERNAL_FPLS_REQUEST_0002ET";
            internal const string SPACES_1_0002AS = "SPACES_1_0002AS";
            internal const string SPACES_1_0002 = "SPACES_1_0002";
            internal const string SPACES_1_0002XX = "SPACES_1_0002XX";
            internal const string STATE_ABBR_0002AS = "STATE_ABBR_0002AS";
            internal const string STATE_ABBR_0002 = "STATE_ABBR_0002";
            internal const string STATE_ABBR_0002XX = "STATE_ABBR_0002XX";
            internal const string STATION_NUMBER_0002AS = "STATION_NUMBER_0002AS";
            internal const string STATION_NUMBER_0002 = "STATION_NUMBER_0002";
            internal const string STATION_NUMBER_0002XX = "STATION_NUMBER_0002XX";
            internal const string SPACES_2_0002AS = "SPACES_2_0002AS";
            internal const string SPACES_2_0002 = "SPACES_2_0002";
            internal const string SPACES_2_0002XX = "SPACES_2_0002XX";
            internal const string TRANSACTION_TYPE_0002AS = "TRANSACTION_TYPE_0002AS";
            internal const string TRANSACTION_TYPE_0002 = "TRANSACTION_TYPE_0002";
            internal const string TRANSACTION_TYPE_0002XX = "TRANSACTION_TYPE_0002XX";
            internal const string SSN_0002AS = "SSN_0002AS";
            internal const string SSN_0002 = "SSN_0002";
            internal const string SSN_0002XX = "SSN_0002XX";
            internal const string AP_CSE_PERSON_NUMBER_0002AS = "AP_CSE_PERSON_NUMBER_0002AS";
            internal const string AP_CSE_PERSON_NUMBER_0002 = "AP_CSE_PERSON_NUMBER_0002";
            internal const string AP_CSE_PERSON_NUMBER_0002XX = "AP_CSE_PERSON_NUMBER_0002XX";
            internal const string FPLS_LOCATE_REQUEST_IDE_0003AS = "FPLS_LOCATE_REQUEST_IDE_0003AS";
            internal const string FPLS_LOCATE_REQUEST_IDENT_0003 = "FPLS_LOCATE_REQUEST_IDENT_0003";
            internal const string FPLS_LOCATE_REQUEST_IDE_0003XX = "FPLS_LOCATE_REQUEST_IDE_0003XX";
            internal const string LOCAL_CODE_0003AS = "LOCAL_CODE_0003AS";
            internal const string LOCAL_CODE_0003 = "LOCAL_CODE_0003";
            internal const string LOCAL_CODE_0003XX = "LOCAL_CODE_0003XX";
            internal const string USERS_FIELD_0003AS = "USERS_FIELD_0003AS";
            internal const string USERS_FIELD_0003 = "USERS_FIELD_0003";
            internal const string USERS_FIELD_0003XX = "USERS_FIELD_0003XX";
            internal const string TYPE_OF_CASE_0003AS = "TYPE_OF_CASE_0003AS";
            internal const string TYPE_OF_CASE_0003 = "TYPE_OF_CASE_0003";
            internal const string TYPE_OF_CASE_0003XX = "TYPE_OF_CASE_0003XX";
            internal const string AP_FIRST_NAME_0003AS = "AP_FIRST_NAME_0003AS";
            internal const string AP_FIRST_NAME_0003 = "AP_FIRST_NAME_0003";
            internal const string AP_FIRST_NAME_0003XX = "AP_FIRST_NAME_0003XX";
            internal const string AP_MIDDLE_NAME_0003AS = "AP_MIDDLE_NAME_0003AS";
            internal const string AP_MIDDLE_NAME_0003 = "AP_MIDDLE_NAME_0003";
            internal const string AP_MIDDLE_NAME_0003XX = "AP_MIDDLE_NAME_0003XX";
            internal const string AP_FIRST_LAST_NAME_0003AS = "AP_FIRST_LAST_NAME_0003AS";
            internal const string AP_FIRST_LAST_NAME_0003 = "AP_FIRST_LAST_NAME_0003";
            internal const string AP_FIRST_LAST_NAME_0003XX = "AP_FIRST_LAST_NAME_0003XX";
            internal const string AP_SECOND_LAST_NAME_0003AS = "AP_SECOND_LAST_NAME_0003AS";
            internal const string AP_SECOND_LAST_NAME_0003 = "AP_SECOND_LAST_NAME_0003";
            internal const string AP_SECOND_LAST_NAME_0003XX = "AP_SECOND_LAST_NAME_0003XX";
            internal const string AP_THIRD_LAST_NAME_0003AS = "AP_THIRD_LAST_NAME_0003AS";
            internal const string AP_THIRD_LAST_NAME_0003 = "AP_THIRD_LAST_NAME_0003";
            internal const string AP_THIRD_LAST_NAME_0003XX = "AP_THIRD_LAST_NAME_0003XX";
            internal const string AP_DATE_OF_BIRTH_MONTH_0003AS = "AP_DATE_OF_BIRTH_MONTH_0003AS";
            internal const string AP_DATE_OF_BIRTH_MONTH_0003 = "AP_DATE_OF_BIRTH_MONTH_0003";
            internal const string AP_DATE_OF_BIRTH_MONTH_0003XX = "AP_DATE_OF_BIRTH_MONTH_0003XX";
            internal const string AP_DATE_OF_BIRTH_DAY_0003AS = "AP_DATE_OF_BIRTH_DAY_0003AS";
            internal const string AP_DATE_OF_BIRTH_DAY_0003 = "AP_DATE_OF_BIRTH_DAY_0003";
            internal const string AP_DATE_OF_BIRTH_DAY_0003XX = "AP_DATE_OF_BIRTH_DAY_0003XX";
            internal const string AP_DATE_OF_BIRTH_YEAR_0003AS = "AP_DATE_OF_BIRTH_YEAR_0003AS";
            internal const string AP_DATE_OF_BIRTH_YEAR_0003 = "AP_DATE_OF_BIRTH_YEAR_0003";
            internal const string AP_DATE_OF_BIRTH_YEAR_0003XX = "AP_DATE_OF_BIRTH_YEAR_0003XX";
            internal const string SEX_0003AS = "SEX_0003AS";
            internal const string SEX_0003 = "SEX_0003";
            internal const string SEX_0003XX = "SEX_0003XX";
            internal const string COLLECT_ALL_RESPONSES_T_0004AS = "COLLECT_ALL_RESPONSES_T_0004AS";
            internal const string COLLECT_ALL_RESPONSES_TOG_0004 = "COLLECT_ALL_RESPONSES_TOG_0004";
            internal const string COLLECT_ALL_RESPONSES_T_0004XX = "COLLECT_ALL_RESPONSES_T_0004XX";
            internal const string SPACES_3_0004AS = "SPACES_3_0004AS";
            internal const string SPACES_3_0004 = "SPACES_3_0004";
            internal const string SPACES_3_0004XX = "SPACES_3_0004XX";
            internal const string SEND_REQUEST_TO_0004AS = "SEND_REQUEST_TO_0004AS";
            internal const string SEND_REQUEST_TO_0004 = "SEND_REQUEST_TO_0004";
            internal const string SEND_REQUEST_TO_0004XX = "SEND_REQUEST_TO_0004XX";
            internal const string TRANSACTION_ERROR_0004AS = "TRANSACTION_ERROR_0004AS";
            internal const string TRANSACTION_ERROR_0004 = "TRANSACTION_ERROR_0004";
            internal const string TRANSACTION_ERROR_0004XX = "TRANSACTION_ERROR_0004XX";
            internal const string SPACES_4_0004AS = "SPACES_4_0004AS";
            internal const string SPACES_4_0004 = "SPACES_4_0004";
            internal const string SPACES_4_0004XX = "SPACES_4_0004XX";
            internal const string AP_CITY_OF_BIRTH_0004AS = "AP_CITY_OF_BIRTH_0004AS";
            internal const string AP_CITY_OF_BIRTH_0004 = "AP_CITY_OF_BIRTH_0004";
            internal const string AP_CITY_OF_BIRTH_0004XX = "AP_CITY_OF_BIRTH_0004XX";
            internal const string AP_STATE_OR_COUNTRY_OF__0005AS = "AP_STATE_OR_COUNTRY_OF__0005AS";
            internal const string AP_STATE_OR_COUNTRY_OF_BI_0005 = "AP_STATE_OR_COUNTRY_OF_BI_0005";
            internal const string AP_STATE_OR_COUNTRY_OF__0005XX = "AP_STATE_OR_COUNTRY_OF__0005XX";
            internal const string APS_FATHERS_FIRST_NAME_0005AS = "APS_FATHERS_FIRST_NAME_0005AS";
            internal const string APS_FATHERS_FIRST_NAME_0005 = "APS_FATHERS_FIRST_NAME_0005";
            internal const string APS_FATHERS_FIRST_NAME_0005XX = "APS_FATHERS_FIRST_NAME_0005XX";
            internal const string APS_FATHERS_MI_0005AS = "APS_FATHERS_MI_0005AS";
            internal const string APS_FATHERS_MI_0005 = "APS_FATHERS_MI_0005";
            internal const string APS_FATHERS_MI_0005XX = "APS_FATHERS_MI_0005XX";
            internal const string APS_FATHERS_LAST_NAME_0005AS = "APS_FATHERS_LAST_NAME_0005AS";
            internal const string APS_FATHERS_LAST_NAME_0005 = "APS_FATHERS_LAST_NAME_0005";
            internal const string APS_FATHERS_LAST_NAME_0005XX = "APS_FATHERS_LAST_NAME_0005XX";
            internal const string APS_MOTHERS_FIRST_NAME_0005AS = "APS_MOTHERS_FIRST_NAME_0005AS";
            internal const string APS_MOTHERS_FIRST_NAME_0005 = "APS_MOTHERS_FIRST_NAME_0005";
            internal const string APS_MOTHERS_FIRST_NAME_0005XX = "APS_MOTHERS_FIRST_NAME_0005XX";
            internal const string APS_MOTHERS_MI_0005AS = "APS_MOTHERS_MI_0005AS";
            internal const string APS_MOTHERS_MI_0005 = "APS_MOTHERS_MI_0005";
            internal const string APS_MOTHERS_MI_0005XX = "APS_MOTHERS_MI_0005XX";
            internal const string APS_MOTHERS_MAIDEN_NAME_0006AS = "APS_MOTHERS_MAIDEN_NAME_0006AS";
            internal const string APS_MOTHERS_MAIDEN_NAME_0006 = "APS_MOTHERS_MAIDEN_NAME_0006";
            internal const string APS_MOTHERS_MAIDEN_NAME_0006XX = "APS_MOTHERS_MAIDEN_NAME_0006XX";
            internal const string CP_SSN_0006AS = "CP_SSN_0006AS";
            internal const string CP_SSN_0006 = "CP_SSN_0006";
            internal const string CP_SSN_0006XX = "CP_SSN_0006XX";
            internal const string IMPORT_0007EV = "IMPORT_0007EV";
            internal const string EXTERNAL_0007ET = "EXTERNAL_0007ET";
            internal const string FILE_INSTRUCTION_0007AS = "FILE_INSTRUCTION_0007AS";
            internal const string FILE_INSTRUCTION_0007 = "FILE_INSTRUCTION_0007";
            internal const string FILE_INSTRUCTION_0007XX = "FILE_INSTRUCTION_0007XX";
            internal const string W_OA = "W_OA";
            internal const string A_0656686780_OA = "A_0656686780_OA";
            internal const string EXPORT_0008EV = "EXPORT_0008EV";
            internal const string EXTERNAL_0008ET = "EXTERNAL_0008ET";
            internal const string NUMERIC_RETURN_CODE_0008AS = "NUMERIC_RETURN_CODE_0008AS";
            internal const string NUMERIC_RETURN_CODE_0008 = "NUMERIC_RETURN_CODE_0008";
            internal const string NUMERIC_RETURN_CODE_0008XX = "NUMERIC_RETURN_CODE_0008XX";
            internal const string TEXT_RETURN_CODE_0008AS = "TEXT_RETURN_CODE_0008AS";
            internal const string TEXT_RETURN_CODE_0008 = "TEXT_RETURN_CODE_0008";
            internal const string TEXT_RETURN_CODE_0008XX = "TEXT_RETURN_CODE_0008XX";
            internal const string TEXT_LINE_80_0008AS = "TEXT_LINE_80_0008AS";
            internal const string TEXT_LINE_80_0008 = "TEXT_LINE_80_0008";
            internal const string TEXT_LINE_80_0008XX = "TEXT_LINE_80_0008XX";
            internal const string FILE_INSTRUCTION_0008AS = "FILE_INSTRUCTION_0008AS";
            internal const string FILE_INSTRUCTION_0008 = "FILE_INSTRUCTION_0008";
            internal const string FILE_INSTRUCTION_0008XX = "FILE_INSTRUCTION_0008XX";
        }
        #endregion

        #region Direct-access element properties
        public IField IEF_RUNTIME_PARM1 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM1); } }
        public IField IEF_RUNTIME_PARM2 { get { return GetElementByName<IField>(Names.IEF_RUNTIME_PARM2); } }
        public IGroup PSMGR_EAB_DATA { get { return GetElementByName<IGroup>(Names.PSMGR_EAB_DATA); } }
        public IField PSMGR_EABPCB_CNT { get { return GetElementByName<IField>(Names.PSMGR_EABPCB_CNT); } }
        public IArrayElementAccessor<IGroup> PSMGR_EABPCB_ENTRY { get { return GetArrayElementAccessor<IGroup>(Names.PSMGR_EABPCB_ENTRY); } }
        public IArrayElementAccessor<IField> PSMGR_EABPCB_ADR { get { return GetArrayElementAccessor<IField>(Names.PSMGR_EABPCB_ADR); } }
        public IGroup W_IA { get { return GetElementByName<IGroup>(Names.W_IA); } }
        public IGroup A_0656686765_IA { get { return GetElementByName<IGroup>(Names.A_0656686765_IA); } }
        public IGroup IMPORT_0001EV { get { return GetElementByName<IGroup>(Names.IMPORT_0001EV); } }
        public IGroup EXTERNAL_FPLS_HEADER_0001ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_FPLS_HEADER_0001ET); } }
        public IField SPACES_1_0001AS { get { return GetElementByName<IField>(Names.SPACES_1_0001AS); } }
        public IField SPACES_1_0001 { get { return GetElementByName<IField>(Names.SPACES_1_0001); } }
        public IField SPACES_1_0001XX { get { return GetElementByName<IField>(Names.SPACES_1_0001XX); } }
        public IField STATE_CODE_0001AS { get { return GetElementByName<IField>(Names.STATE_CODE_0001AS); } }
        public IField STATE_CODE_0001 { get { return GetElementByName<IField>(Names.STATE_CODE_0001); } }
        public IField STATE_CODE_0001XX { get { return GetElementByName<IField>(Names.STATE_CODE_0001XX); } }
        public IField STATION_NUMBER_0001AS { get { return GetElementByName<IField>(Names.STATION_NUMBER_0001AS); } }
        public IField STATION_NUMBER_0001 { get { return GetElementByName<IField>(Names.STATION_NUMBER_0001); } }
        public IField STATION_NUMBER_0001XX { get { return GetElementByName<IField>(Names.STATION_NUMBER_0001XX); } }
        public IField SPACES_2_0001AS { get { return GetElementByName<IField>(Names.SPACES_2_0001AS); } }
        public IField SPACES_2_0001 { get { return GetElementByName<IField>(Names.SPACES_2_0001); } }
        public IField SPACES_2_0001XX { get { return GetElementByName<IField>(Names.SPACES_2_0001XX); } }
        public IField FPLS_HEADER_CONSTANT_0001AS { get { return GetElementByName<IField>(Names.FPLS_HEADER_CONSTANT_0001AS); } }
        public IField FPLS_HEADER_CONSTANT_0001 { get { return GetElementByName<IField>(Names.FPLS_HEADER_CONSTANT_0001); } }
        public IField FPLS_HEADER_CONSTANT_0001XX { get { return GetElementByName<IField>(Names.FPLS_HEADER_CONSTANT_0001XX); } }
        public IField TOTAL_RESPONSES_0001AS { get { return GetElementByName<IField>(Names.TOTAL_RESPONSES_0001AS); } }
        public IField TOTAL_RESPONSES_0001 { get { return GetElementByName<IField>(Names.TOTAL_RESPONSES_0001); } }
        public IField TOTAL_RESPONSES_0001XX { get { return GetElementByName<IField>(Names.TOTAL_RESPONSES_0001XX); } }
        public IField FPLS_SORT_CODE_0001AS { get { return GetElementByName<IField>(Names.FPLS_SORT_CODE_0001AS); } }
        public IField FPLS_SORT_CODE_0001 { get { return GetElementByName<IField>(Names.FPLS_SORT_CODE_0001); } }
        public IField FPLS_SORT_CODE_0001XX { get { return GetElementByName<IField>(Names.FPLS_SORT_CODE_0001XX); } }
        public IField MM_DATE_GENERATED_0001AS { get { return GetElementByName<IField>(Names.MM_DATE_GENERATED_0001AS); } }
        public IField MM_DATE_GENERATED_0001 { get { return GetElementByName<IField>(Names.MM_DATE_GENERATED_0001); } }
        public IField MM_DATE_GENERATED_0001XX { get { return GetElementByName<IField>(Names.MM_DATE_GENERATED_0001XX); } }
        public IField DD_DATE_GENERATED_0001AS { get { return GetElementByName<IField>(Names.DD_DATE_GENERATED_0001AS); } }
        public IField DD_DATE_GENERATED_0001 { get { return GetElementByName<IField>(Names.DD_DATE_GENERATED_0001); } }
        public IField DD_DATE_GENERATED_0001XX { get { return GetElementByName<IField>(Names.DD_DATE_GENERATED_0001XX); } }
        public IField YY_DATE_GENERATED_0001AS { get { return GetElementByName<IField>(Names.YY_DATE_GENERATED_0001AS); } }
        public IField YY_DATE_GENERATED_0001 { get { return GetElementByName<IField>(Names.YY_DATE_GENERATED_0001); } }
        public IField YY_DATE_GENERATED_0001XX { get { return GetElementByName<IField>(Names.YY_DATE_GENERATED_0001XX); } }
        public IField SPACES_3_0001AS { get { return GetElementByName<IField>(Names.SPACES_3_0001AS); } }
        public IField SPACES_3_0001 { get { return GetElementByName<IField>(Names.SPACES_3_0001); } }
        public IField SPACES_3_0001XX { get { return GetElementByName<IField>(Names.SPACES_3_0001XX); } }
        public IField SPACES_4_0001AS { get { return GetElementByName<IField>(Names.SPACES_4_0001AS); } }
        public IField SPACES_4_0001 { get { return GetElementByName<IField>(Names.SPACES_4_0001); } }
        public IField SPACES_4_0001XX { get { return GetElementByName<IField>(Names.SPACES_4_0001XX); } }
        public IGroup IMPORT_0002EV { get { return GetElementByName<IGroup>(Names.IMPORT_0002EV); } }
        public IGroup EXTERNAL_FPLS_REQUEST_0002ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_FPLS_REQUEST_0002ET); } }
        public IField SPACES_1_0002AS { get { return GetElementByName<IField>(Names.SPACES_1_0002AS); } }
        public IField SPACES_1_0002 { get { return GetElementByName<IField>(Names.SPACES_1_0002); } }
        public IField SPACES_1_0002XX { get { return GetElementByName<IField>(Names.SPACES_1_0002XX); } }
        public IField STATE_ABBR_0002AS { get { return GetElementByName<IField>(Names.STATE_ABBR_0002AS); } }
        public IField STATE_ABBR_0002 { get { return GetElementByName<IField>(Names.STATE_ABBR_0002); } }
        public IField STATE_ABBR_0002XX { get { return GetElementByName<IField>(Names.STATE_ABBR_0002XX); } }
        public IField STATION_NUMBER_0002AS { get { return GetElementByName<IField>(Names.STATION_NUMBER_0002AS); } }
        public IField STATION_NUMBER_0002 { get { return GetElementByName<IField>(Names.STATION_NUMBER_0002); } }
        public IField STATION_NUMBER_0002XX { get { return GetElementByName<IField>(Names.STATION_NUMBER_0002XX); } }
        public IField SPACES_2_0002AS { get { return GetElementByName<IField>(Names.SPACES_2_0002AS); } }
        public IField SPACES_2_0002 { get { return GetElementByName<IField>(Names.SPACES_2_0002); } }
        public IField SPACES_2_0002XX { get { return GetElementByName<IField>(Names.SPACES_2_0002XX); } }
        public IField TRANSACTION_TYPE_0002AS { get { return GetElementByName<IField>(Names.TRANSACTION_TYPE_0002AS); } }
        public IField TRANSACTION_TYPE_0002 { get { return GetElementByName<IField>(Names.TRANSACTION_TYPE_0002); } }
        public IField TRANSACTION_TYPE_0002XX { get { return GetElementByName<IField>(Names.TRANSACTION_TYPE_0002XX); } }
        public IField SSN_0002AS { get { return GetElementByName<IField>(Names.SSN_0002AS); } }
        public IField SSN_0002 { get { return GetElementByName<IField>(Names.SSN_0002); } }
        public IField SSN_0002XX { get { return GetElementByName<IField>(Names.SSN_0002XX); } }
        public IField AP_CSE_PERSON_NUMBER_0002AS { get { return GetElementByName<IField>(Names.AP_CSE_PERSON_NUMBER_0002AS); } }
        public IField AP_CSE_PERSON_NUMBER_0002 { get { return GetElementByName<IField>(Names.AP_CSE_PERSON_NUMBER_0002); } }
        public IField AP_CSE_PERSON_NUMBER_0002XX { get { return GetElementByName<IField>(Names.AP_CSE_PERSON_NUMBER_0002XX); } }
        public IField FPLS_LOCATE_REQUEST_IDE_0003AS { get { return GetElementByName<IField>(Names.FPLS_LOCATE_REQUEST_IDE_0003AS); } }
        public IField FPLS_LOCATE_REQUEST_IDENT_0003 { get { return GetElementByName<IField>(Names.FPLS_LOCATE_REQUEST_IDENT_0003); } }
        public IField FPLS_LOCATE_REQUEST_IDE_0003XX { get { return GetElementByName<IField>(Names.FPLS_LOCATE_REQUEST_IDE_0003XX); } }
        public IField LOCAL_CODE_0003AS { get { return GetElementByName<IField>(Names.LOCAL_CODE_0003AS); } }
        public IField LOCAL_CODE_0003 { get { return GetElementByName<IField>(Names.LOCAL_CODE_0003); } }
        public IField LOCAL_CODE_0003XX { get { return GetElementByName<IField>(Names.LOCAL_CODE_0003XX); } }
        public IField USERS_FIELD_0003AS { get { return GetElementByName<IField>(Names.USERS_FIELD_0003AS); } }
        public IField USERS_FIELD_0003 { get { return GetElementByName<IField>(Names.USERS_FIELD_0003); } }
        public IField USERS_FIELD_0003XX { get { return GetElementByName<IField>(Names.USERS_FIELD_0003XX); } }
        public IField TYPE_OF_CASE_0003AS { get { return GetElementByName<IField>(Names.TYPE_OF_CASE_0003AS); } }
        public IField TYPE_OF_CASE_0003 { get { return GetElementByName<IField>(Names.TYPE_OF_CASE_0003); } }
        public IField TYPE_OF_CASE_0003XX { get { return GetElementByName<IField>(Names.TYPE_OF_CASE_0003XX); } }
        public IField AP_FIRST_NAME_0003AS { get { return GetElementByName<IField>(Names.AP_FIRST_NAME_0003AS); } }
        public IField AP_FIRST_NAME_0003 { get { return GetElementByName<IField>(Names.AP_FIRST_NAME_0003); } }
        public IField AP_FIRST_NAME_0003XX { get { return GetElementByName<IField>(Names.AP_FIRST_NAME_0003XX); } }
        public IField AP_MIDDLE_NAME_0003AS { get { return GetElementByName<IField>(Names.AP_MIDDLE_NAME_0003AS); } }
        public IField AP_MIDDLE_NAME_0003 { get { return GetElementByName<IField>(Names.AP_MIDDLE_NAME_0003); } }
        public IField AP_MIDDLE_NAME_0003XX { get { return GetElementByName<IField>(Names.AP_MIDDLE_NAME_0003XX); } }
        public IField AP_FIRST_LAST_NAME_0003AS { get { return GetElementByName<IField>(Names.AP_FIRST_LAST_NAME_0003AS); } }
        public IField AP_FIRST_LAST_NAME_0003 { get { return GetElementByName<IField>(Names.AP_FIRST_LAST_NAME_0003); } }
        public IField AP_FIRST_LAST_NAME_0003XX { get { return GetElementByName<IField>(Names.AP_FIRST_LAST_NAME_0003XX); } }
        public IField AP_SECOND_LAST_NAME_0003AS { get { return GetElementByName<IField>(Names.AP_SECOND_LAST_NAME_0003AS); } }
        public IField AP_SECOND_LAST_NAME_0003 { get { return GetElementByName<IField>(Names.AP_SECOND_LAST_NAME_0003); } }
        public IField AP_SECOND_LAST_NAME_0003XX { get { return GetElementByName<IField>(Names.AP_SECOND_LAST_NAME_0003XX); } }
        public IField AP_THIRD_LAST_NAME_0003AS { get { return GetElementByName<IField>(Names.AP_THIRD_LAST_NAME_0003AS); } }
        public IField AP_THIRD_LAST_NAME_0003 { get { return GetElementByName<IField>(Names.AP_THIRD_LAST_NAME_0003); } }
        public IField AP_THIRD_LAST_NAME_0003XX { get { return GetElementByName<IField>(Names.AP_THIRD_LAST_NAME_0003XX); } }
        public IField AP_DATE_OF_BIRTH_MONTH_0003AS { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_MONTH_0003AS); } }
        public IField AP_DATE_OF_BIRTH_MONTH_0003 { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_MONTH_0003); } }
        public IField AP_DATE_OF_BIRTH_MONTH_0003XX { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_MONTH_0003XX); } }
        public IField AP_DATE_OF_BIRTH_DAY_0003AS { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_DAY_0003AS); } }
        public IField AP_DATE_OF_BIRTH_DAY_0003 { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_DAY_0003); } }
        public IField AP_DATE_OF_BIRTH_DAY_0003XX { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_DAY_0003XX); } }
        public IField AP_DATE_OF_BIRTH_YEAR_0003AS { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_YEAR_0003AS); } }
        public IField AP_DATE_OF_BIRTH_YEAR_0003 { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_YEAR_0003); } }
        public IField AP_DATE_OF_BIRTH_YEAR_0003XX { get { return GetElementByName<IField>(Names.AP_DATE_OF_BIRTH_YEAR_0003XX); } }
        public IField SEX_0003AS { get { return GetElementByName<IField>(Names.SEX_0003AS); } }
        public IField SEX_0003 { get { return GetElementByName<IField>(Names.SEX_0003); } }
        public IField SEX_0003XX { get { return GetElementByName<IField>(Names.SEX_0003XX); } }
        public IField COLLECT_ALL_RESPONSES_T_0004AS { get { return GetElementByName<IField>(Names.COLLECT_ALL_RESPONSES_T_0004AS); } }
        public IField COLLECT_ALL_RESPONSES_TOG_0004 { get { return GetElementByName<IField>(Names.COLLECT_ALL_RESPONSES_TOG_0004); } }
        public IField COLLECT_ALL_RESPONSES_T_0004XX { get { return GetElementByName<IField>(Names.COLLECT_ALL_RESPONSES_T_0004XX); } }
        public IField SPACES_3_0004AS { get { return GetElementByName<IField>(Names.SPACES_3_0004AS); } }
        public IField SPACES_3_0004 { get { return GetElementByName<IField>(Names.SPACES_3_0004); } }
        public IField SPACES_3_0004XX { get { return GetElementByName<IField>(Names.SPACES_3_0004XX); } }
        public IField SEND_REQUEST_TO_0004AS { get { return GetElementByName<IField>(Names.SEND_REQUEST_TO_0004AS); } }
        public IField SEND_REQUEST_TO_0004 { get { return GetElementByName<IField>(Names.SEND_REQUEST_TO_0004); } }
        public IField SEND_REQUEST_TO_0004XX { get { return GetElementByName<IField>(Names.SEND_REQUEST_TO_0004XX); } }
        public IField TRANSACTION_ERROR_0004AS { get { return GetElementByName<IField>(Names.TRANSACTION_ERROR_0004AS); } }
        public IField TRANSACTION_ERROR_0004 { get { return GetElementByName<IField>(Names.TRANSACTION_ERROR_0004); } }
        public IField TRANSACTION_ERROR_0004XX { get { return GetElementByName<IField>(Names.TRANSACTION_ERROR_0004XX); } }
        public IField SPACES_4_0004AS { get { return GetElementByName<IField>(Names.SPACES_4_0004AS); } }
        public IField SPACES_4_0004 { get { return GetElementByName<IField>(Names.SPACES_4_0004); } }
        public IField SPACES_4_0004XX { get { return GetElementByName<IField>(Names.SPACES_4_0004XX); } }
        public IField AP_CITY_OF_BIRTH_0004AS { get { return GetElementByName<IField>(Names.AP_CITY_OF_BIRTH_0004AS); } }
        public IField AP_CITY_OF_BIRTH_0004 { get { return GetElementByName<IField>(Names.AP_CITY_OF_BIRTH_0004); } }
        public IField AP_CITY_OF_BIRTH_0004XX { get { return GetElementByName<IField>(Names.AP_CITY_OF_BIRTH_0004XX); } }
        public IField AP_STATE_OR_COUNTRY_OF__0005AS { get { return GetElementByName<IField>(Names.AP_STATE_OR_COUNTRY_OF__0005AS); } }
        public IField AP_STATE_OR_COUNTRY_OF_BI_0005 { get { return GetElementByName<IField>(Names.AP_STATE_OR_COUNTRY_OF_BI_0005); } }
        public IField AP_STATE_OR_COUNTRY_OF__0005XX { get { return GetElementByName<IField>(Names.AP_STATE_OR_COUNTRY_OF__0005XX); } }
        public IField APS_FATHERS_FIRST_NAME_0005AS { get { return GetElementByName<IField>(Names.APS_FATHERS_FIRST_NAME_0005AS); } }
        public IField APS_FATHERS_FIRST_NAME_0005 { get { return GetElementByName<IField>(Names.APS_FATHERS_FIRST_NAME_0005); } }
        public IField APS_FATHERS_FIRST_NAME_0005XX { get { return GetElementByName<IField>(Names.APS_FATHERS_FIRST_NAME_0005XX); } }
        public IField APS_FATHERS_MI_0005AS { get { return GetElementByName<IField>(Names.APS_FATHERS_MI_0005AS); } }
        public IField APS_FATHERS_MI_0005 { get { return GetElementByName<IField>(Names.APS_FATHERS_MI_0005); } }
        public IField APS_FATHERS_MI_0005XX { get { return GetElementByName<IField>(Names.APS_FATHERS_MI_0005XX); } }
        public IField APS_FATHERS_LAST_NAME_0005AS { get { return GetElementByName<IField>(Names.APS_FATHERS_LAST_NAME_0005AS); } }
        public IField APS_FATHERS_LAST_NAME_0005 { get { return GetElementByName<IField>(Names.APS_FATHERS_LAST_NAME_0005); } }
        public IField APS_FATHERS_LAST_NAME_0005XX { get { return GetElementByName<IField>(Names.APS_FATHERS_LAST_NAME_0005XX); } }
        public IField APS_MOTHERS_FIRST_NAME_0005AS { get { return GetElementByName<IField>(Names.APS_MOTHERS_FIRST_NAME_0005AS); } }
        public IField APS_MOTHERS_FIRST_NAME_0005 { get { return GetElementByName<IField>(Names.APS_MOTHERS_FIRST_NAME_0005); } }
        public IField APS_MOTHERS_FIRST_NAME_0005XX { get { return GetElementByName<IField>(Names.APS_MOTHERS_FIRST_NAME_0005XX); } }
        public IField APS_MOTHERS_MI_0005AS { get { return GetElementByName<IField>(Names.APS_MOTHERS_MI_0005AS); } }
        public IField APS_MOTHERS_MI_0005 { get { return GetElementByName<IField>(Names.APS_MOTHERS_MI_0005); } }
        public IField APS_MOTHERS_MI_0005XX { get { return GetElementByName<IField>(Names.APS_MOTHERS_MI_0005XX); } }
        public IField APS_MOTHERS_MAIDEN_NAME_0006AS { get { return GetElementByName<IField>(Names.APS_MOTHERS_MAIDEN_NAME_0006AS); } }
        public IField APS_MOTHERS_MAIDEN_NAME_0006 { get { return GetElementByName<IField>(Names.APS_MOTHERS_MAIDEN_NAME_0006); } }
        public IField APS_MOTHERS_MAIDEN_NAME_0006XX { get { return GetElementByName<IField>(Names.APS_MOTHERS_MAIDEN_NAME_0006XX); } }
        public IField CP_SSN_0006AS { get { return GetElementByName<IField>(Names.CP_SSN_0006AS); } }
        public IField CP_SSN_0006 { get { return GetElementByName<IField>(Names.CP_SSN_0006); } }
        public IField CP_SSN_0006XX { get { return GetElementByName<IField>(Names.CP_SSN_0006XX); } }
        public IGroup IMPORT_0007EV { get { return GetElementByName<IGroup>(Names.IMPORT_0007EV); } }
        public IGroup EXTERNAL_0007ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_0007ET); } }
        public IField FILE_INSTRUCTION_0007AS { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0007AS); } }
        public IField FILE_INSTRUCTION_0007 { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0007); } }
        public IField FILE_INSTRUCTION_0007XX { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0007XX); } }
        public IGroup W_OA { get { return GetElementByName<IGroup>(Names.W_OA); } }
        public IGroup A_0656686780_OA { get { return GetElementByName<IGroup>(Names.A_0656686780_OA); } }
        public IGroup EXPORT_0008EV { get { return GetElementByName<IGroup>(Names.EXPORT_0008EV); } }
        public IGroup EXTERNAL_0008ET { get { return GetElementByName<IGroup>(Names.EXTERNAL_0008ET); } }
        public IField NUMERIC_RETURN_CODE_0008AS { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0008AS); } }
        public IField NUMERIC_RETURN_CODE_0008 { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0008); } }
        public IField NUMERIC_RETURN_CODE_0008XX { get { return GetElementByName<IField>(Names.NUMERIC_RETURN_CODE_0008XX); } }
        public IField TEXT_RETURN_CODE_0008AS { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0008AS); } }
        public IField TEXT_RETURN_CODE_0008 { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0008); } }
        public IField TEXT_RETURN_CODE_0008XX { get { return GetElementByName<IField>(Names.TEXT_RETURN_CODE_0008XX); } }
        public IField TEXT_LINE_80_0008AS { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0008AS); } }
        public IField TEXT_LINE_80_0008 { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0008); } }
        public IField TEXT_LINE_80_0008XX { get { return GetElementByName<IField>(Names.TEXT_LINE_80_0008XX); } }
        public IField FILE_INSTRUCTION_0008AS { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0008AS); } }
        public IField FILE_INSTRUCTION_0008 { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0008); } }
        public IField FILE_INSTRUCTION_0008XX { get { return GetElementByName<IField>(Names.FILE_INSTRUCTION_0008XX); } }

        #endregion

        #region Data structure definition
        /// <summary>
        /// Defines the entirety of the LinkageSection IRecord structure as described by the Ateras.Framework.Buffer API.
        /// </summary>
        /// <param name="recordDef">The IStructureDefinition object to be used in defining the record structure.</param>
        protected override void DefineRecordStructure(IStructureDefinition recordDef)
        {
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM1, FieldType.String, 1);
            recordDef.CreateNewField(Names.IEF_RUNTIME_PARM2, FieldType.String, 1);

            recordDef.CreateNewGroup(Names.PSMGR_EAB_DATA, (PSMGR_EAB_DATA) =>
           {
               PSMGR_EAB_DATA.CreateNewField(Names.PSMGR_EABPCB_CNT, FieldType.CompInt, 9);
               PSMGR_EAB_DATA.CreateNewGroupArray(Names.PSMGR_EABPCB_ENTRY, 255, (PSMGR_EABPCB_ENTRY) =>
               {
                   PSMGR_EABPCB_ENTRY.CreateNewField(Names.PSMGR_EABPCB_ADR, FieldType.CompInt, 9);
               });
           });

            recordDef.CreateNewGroup(Names.W_IA, (W_IA) =>
           {
               W_IA.CreateNewGroup(Names.A_0656686765_IA, (A_0656686765_IA) =>
               {
                   A_0656686765_IA.CreateNewGroup(Names.IMPORT_0001EV, (IMPORT_0001EV) =>
                   {
                       IMPORT_0001EV.CreateNewGroup(Names.EXTERNAL_FPLS_HEADER_0001ET, (EXTERNAL_FPLS_HEADER_0001ET) =>
                       {
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_1_0001AS, FieldType.String, 1);

                           IField SPACES_1_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_1_0001, FieldType.String, 16);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.SPACES_1_0001XX, FieldType.String, SPACES_1_0001_local, 16);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.STATE_CODE_0001AS, FieldType.String, 1);

                           IField STATE_CODE_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.STATE_CODE_0001, FieldType.String, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.STATE_CODE_0001XX, FieldType.String, STATE_CODE_0001_local, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.STATION_NUMBER_0001AS, FieldType.String, 1);

                           IField STATION_NUMBER_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.STATION_NUMBER_0001, FieldType.String, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.STATION_NUMBER_0001XX, FieldType.String, STATION_NUMBER_0001_local, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_2_0001AS, FieldType.String, 1);

                           IField SPACES_2_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_2_0001, FieldType.String, 13);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.SPACES_2_0001XX, FieldType.String, SPACES_2_0001_local, 13);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.FPLS_HEADER_CONSTANT_0001AS, FieldType.String, 1);

                           IField FPLS_HEADER_CONSTANT_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.FPLS_HEADER_CONSTANT_0001, FieldType.String, 13);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.FPLS_HEADER_CONSTANT_0001XX, FieldType.String, FPLS_HEADER_CONSTANT_0001_local, 13);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.TOTAL_RESPONSES_0001AS, FieldType.String, 1);

                           IField TOTAL_RESPONSES_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.TOTAL_RESPONSES_0001, FieldType.SignedNumeric, 9);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.TOTAL_RESPONSES_0001XX, FieldType.String, TOTAL_RESPONSES_0001_local, 9);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.FPLS_SORT_CODE_0001AS, FieldType.String, 1);

                           IField FPLS_SORT_CODE_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.FPLS_SORT_CODE_0001, FieldType.String, 1);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.FPLS_SORT_CODE_0001XX, FieldType.String, FPLS_SORT_CODE_0001_local, 1);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.MM_DATE_GENERATED_0001AS, FieldType.String, 1);

                           IField MM_DATE_GENERATED_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.MM_DATE_GENERATED_0001, FieldType.SignedNumeric, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.MM_DATE_GENERATED_0001XX, FieldType.String, MM_DATE_GENERATED_0001_local, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.DD_DATE_GENERATED_0001AS, FieldType.String, 1);

                           IField DD_DATE_GENERATED_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.DD_DATE_GENERATED_0001, FieldType.SignedNumeric, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.DD_DATE_GENERATED_0001XX, FieldType.String, DD_DATE_GENERATED_0001_local, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.YY_DATE_GENERATED_0001AS, FieldType.String, 1);

                           IField YY_DATE_GENERATED_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.YY_DATE_GENERATED_0001, FieldType.SignedNumeric, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.YY_DATE_GENERATED_0001XX, FieldType.String, YY_DATE_GENERATED_0001_local, 2);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_3_0001AS, FieldType.String, 1);

                           IField SPACES_3_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_3_0001, FieldType.String, 200);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.SPACES_3_0001XX, FieldType.String, SPACES_3_0001_local, 200);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_4_0001AS, FieldType.String, 1);

                           IField SPACES_4_0001_local = EXTERNAL_FPLS_HEADER_0001ET.CreateNewField(Names.SPACES_4_0001, FieldType.String, 191);
                           EXTERNAL_FPLS_HEADER_0001ET.CreateNewFieldRedefine(Names.SPACES_4_0001XX, FieldType.String, SPACES_4_0001_local, 191);
                       });
                   });
                   A_0656686765_IA.CreateNewGroup(Names.IMPORT_0002EV, (IMPORT_0002EV) =>
                   {
                       IMPORT_0002EV.CreateNewGroup(Names.EXTERNAL_FPLS_REQUEST_0002ET, (EXTERNAL_FPLS_REQUEST_0002ET) =>
                       {
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_1_0002AS, FieldType.String, 1);

                           IField SPACES_1_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_1_0002, FieldType.String, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SPACES_1_0002XX, FieldType.String, SPACES_1_0002_local, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.STATE_ABBR_0002AS, FieldType.String, 1);

                           IField STATE_ABBR_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.STATE_ABBR_0002, FieldType.String, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.STATE_ABBR_0002XX, FieldType.String, STATE_ABBR_0002_local, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.STATION_NUMBER_0002AS, FieldType.String, 1);

                           IField STATION_NUMBER_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.STATION_NUMBER_0002, FieldType.String, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.STATION_NUMBER_0002XX, FieldType.String, STATION_NUMBER_0002_local, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_2_0002AS, FieldType.String, 1);

                           IField SPACES_2_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_2_0002, FieldType.String, 10);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SPACES_2_0002XX, FieldType.String, SPACES_2_0002_local, 10);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.TRANSACTION_TYPE_0002AS, FieldType.String, 1);

                           IField TRANSACTION_TYPE_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.TRANSACTION_TYPE_0002, FieldType.String, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.TRANSACTION_TYPE_0002XX, FieldType.String, TRANSACTION_TYPE_0002_local, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SSN_0002AS, FieldType.String, 1);

                           IField SSN_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SSN_0002, FieldType.String, 9);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SSN_0002XX, FieldType.String, SSN_0002_local, 9);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_CSE_PERSON_NUMBER_0002AS, FieldType.String, 1);

                           IField AP_CSE_PERSON_NUMBER_0002_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_CSE_PERSON_NUMBER_0002, FieldType.String, 10);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_CSE_PERSON_NUMBER_0002XX, FieldType.String, AP_CSE_PERSON_NUMBER_0002_local, 10);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.FPLS_LOCATE_REQUEST_IDE_0003AS, FieldType.String, 1);

                           IField FPLS_LOCATE_REQUEST_IDENT_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.FPLS_LOCATE_REQUEST_IDENT_0003, FieldType.SignedNumeric, 5);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.FPLS_LOCATE_REQUEST_IDE_0003XX, FieldType.String, FPLS_LOCATE_REQUEST_IDENT_0003_local, 5);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.LOCAL_CODE_0003AS, FieldType.String, 1);

                           IField LOCAL_CODE_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.LOCAL_CODE_0003, FieldType.String, 3);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.LOCAL_CODE_0003XX, FieldType.String, LOCAL_CODE_0003_local, 3);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.USERS_FIELD_0003AS, FieldType.String, 1);

                           IField USERS_FIELD_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.USERS_FIELD_0003, FieldType.String, 7);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.USERS_FIELD_0003XX, FieldType.String, USERS_FIELD_0003_local, 7);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.TYPE_OF_CASE_0003AS, FieldType.String, 1);

                           IField TYPE_OF_CASE_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.TYPE_OF_CASE_0003, FieldType.String, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.TYPE_OF_CASE_0003XX, FieldType.String, TYPE_OF_CASE_0003_local, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_FIRST_NAME_0003AS, FieldType.String, 1);

                           IField AP_FIRST_NAME_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_FIRST_NAME_0003, FieldType.String, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_FIRST_NAME_0003XX, FieldType.String, AP_FIRST_NAME_0003_local, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_MIDDLE_NAME_0003AS, FieldType.String, 1);

                           IField AP_MIDDLE_NAME_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_MIDDLE_NAME_0003, FieldType.String, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_MIDDLE_NAME_0003XX, FieldType.String, AP_MIDDLE_NAME_0003_local, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_FIRST_LAST_NAME_0003AS, FieldType.String, 1);

                           IField AP_FIRST_LAST_NAME_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_FIRST_LAST_NAME_0003, FieldType.String, 20);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_FIRST_LAST_NAME_0003XX, FieldType.String, AP_FIRST_LAST_NAME_0003_local, 20);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_SECOND_LAST_NAME_0003AS, FieldType.String, 1);

                           IField AP_SECOND_LAST_NAME_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_SECOND_LAST_NAME_0003, FieldType.String, 20);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_SECOND_LAST_NAME_0003XX, FieldType.String, AP_SECOND_LAST_NAME_0003_local, 20);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_THIRD_LAST_NAME_0003AS, FieldType.String, 1);

                           IField AP_THIRD_LAST_NAME_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_THIRD_LAST_NAME_0003, FieldType.String, 20);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_THIRD_LAST_NAME_0003XX, FieldType.String, AP_THIRD_LAST_NAME_0003_local, 20);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_DATE_OF_BIRTH_MONTH_0003AS, FieldType.String, 1);

                           IField AP_DATE_OF_BIRTH_MONTH_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_DATE_OF_BIRTH_MONTH_0003, FieldType.SignedNumeric, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_DATE_OF_BIRTH_MONTH_0003XX, FieldType.String, AP_DATE_OF_BIRTH_MONTH_0003_local, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_DATE_OF_BIRTH_DAY_0003AS, FieldType.String, 1);

                           IField AP_DATE_OF_BIRTH_DAY_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_DATE_OF_BIRTH_DAY_0003, FieldType.SignedNumeric, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_DATE_OF_BIRTH_DAY_0003XX, FieldType.String, AP_DATE_OF_BIRTH_DAY_0003_local, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_DATE_OF_BIRTH_YEAR_0003AS, FieldType.String, 1);

                           IField AP_DATE_OF_BIRTH_YEAR_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_DATE_OF_BIRTH_YEAR_0003, FieldType.SignedNumeric, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_DATE_OF_BIRTH_YEAR_0003XX, FieldType.String, AP_DATE_OF_BIRTH_YEAR_0003_local, 2);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SEX_0003AS, FieldType.String, 1);

                           IField SEX_0003_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SEX_0003, FieldType.String, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SEX_0003XX, FieldType.String, SEX_0003_local, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.COLLECT_ALL_RESPONSES_T_0004AS, FieldType.String, 1);

                           IField COLLECT_ALL_RESPONSES_TOG_0004_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.COLLECT_ALL_RESPONSES_TOG_0004, FieldType.String, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.COLLECT_ALL_RESPONSES_T_0004XX, FieldType.String, COLLECT_ALL_RESPONSES_TOG_0004_local, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_3_0004AS, FieldType.String, 1);

                           IField SPACES_3_0004_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_3_0004, FieldType.String, 12);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SPACES_3_0004XX, FieldType.String, SPACES_3_0004_local, 12);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SEND_REQUEST_TO_0004AS, FieldType.String, 1);

                           IField SEND_REQUEST_TO_0004_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SEND_REQUEST_TO_0004, FieldType.String, 45);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SEND_REQUEST_TO_0004XX, FieldType.String, SEND_REQUEST_TO_0004_local, 45);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.TRANSACTION_ERROR_0004AS, FieldType.String, 1);

                           IField TRANSACTION_ERROR_0004_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.TRANSACTION_ERROR_0004, FieldType.String, 10);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.TRANSACTION_ERROR_0004XX, FieldType.String, TRANSACTION_ERROR_0004_local, 10);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_4_0004AS, FieldType.String, 1);

                           IField SPACES_4_0004_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.SPACES_4_0004, FieldType.String, 14);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.SPACES_4_0004XX, FieldType.String, SPACES_4_0004_local, 14);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_CITY_OF_BIRTH_0004AS, FieldType.String, 1);

                           IField AP_CITY_OF_BIRTH_0004_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_CITY_OF_BIRTH_0004, FieldType.String, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_CITY_OF_BIRTH_0004XX, FieldType.String, AP_CITY_OF_BIRTH_0004_local, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_STATE_OR_COUNTRY_OF__0005AS, FieldType.String, 1);

                           IField AP_STATE_OR_COUNTRY_OF_BI_0005_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.AP_STATE_OR_COUNTRY_OF_BI_0005, FieldType.String, 3);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.AP_STATE_OR_COUNTRY_OF__0005XX, FieldType.String, AP_STATE_OR_COUNTRY_OF_BI_0005_local, 3);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_FATHERS_FIRST_NAME_0005AS, FieldType.String, 1);

                           IField APS_FATHERS_FIRST_NAME_0005_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_FATHERS_FIRST_NAME_0005, FieldType.String, 13);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.APS_FATHERS_FIRST_NAME_0005XX, FieldType.String, APS_FATHERS_FIRST_NAME_0005_local, 13);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_FATHERS_MI_0005AS, FieldType.String, 1);

                           IField APS_FATHERS_MI_0005_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_FATHERS_MI_0005, FieldType.String, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.APS_FATHERS_MI_0005XX, FieldType.String, APS_FATHERS_MI_0005_local, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_FATHERS_LAST_NAME_0005AS, FieldType.String, 1);

                           IField APS_FATHERS_LAST_NAME_0005_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_FATHERS_LAST_NAME_0005, FieldType.String, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.APS_FATHERS_LAST_NAME_0005XX, FieldType.String, APS_FATHERS_LAST_NAME_0005_local, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_MOTHERS_FIRST_NAME_0005AS, FieldType.String, 1);

                           IField APS_MOTHERS_FIRST_NAME_0005_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_MOTHERS_FIRST_NAME_0005, FieldType.String, 13);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.APS_MOTHERS_FIRST_NAME_0005XX, FieldType.String, APS_MOTHERS_FIRST_NAME_0005_local, 13);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_MOTHERS_MI_0005AS, FieldType.String, 1);

                           IField APS_MOTHERS_MI_0005_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_MOTHERS_MI_0005, FieldType.String, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.APS_MOTHERS_MI_0005XX, FieldType.String, APS_MOTHERS_MI_0005_local, 1);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_MOTHERS_MAIDEN_NAME_0006AS, FieldType.String, 1);

                           IField APS_MOTHERS_MAIDEN_NAME_0006_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.APS_MOTHERS_MAIDEN_NAME_0006, FieldType.String, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.APS_MOTHERS_MAIDEN_NAME_0006XX, FieldType.String, APS_MOTHERS_MAIDEN_NAME_0006_local, 16);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.CP_SSN_0006AS, FieldType.String, 1);

                           IField CP_SSN_0006_local = EXTERNAL_FPLS_REQUEST_0002ET.CreateNewField(Names.CP_SSN_0006, FieldType.String, 9);
                           EXTERNAL_FPLS_REQUEST_0002ET.CreateNewFieldRedefine(Names.CP_SSN_0006XX, FieldType.String, CP_SSN_0006_local, 9);
                       });
                   });
                   A_0656686765_IA.CreateNewGroup(Names.IMPORT_0007EV, (IMPORT_0007EV) =>
                   {
                       IMPORT_0007EV.CreateNewGroup(Names.EXTERNAL_0007ET, (EXTERNAL_0007ET) =>
                       {
                           EXTERNAL_0007ET.CreateNewField(Names.FILE_INSTRUCTION_0007AS, FieldType.String, 1);

                           IField FILE_INSTRUCTION_0007_local = EXTERNAL_0007ET.CreateNewField(Names.FILE_INSTRUCTION_0007, FieldType.String, 10);
                           EXTERNAL_0007ET.CreateNewFieldRedefine(Names.FILE_INSTRUCTION_0007XX, FieldType.String, FILE_INSTRUCTION_0007_local, 10);
                       });
                   });
               });
           });

            recordDef.CreateNewGroup(Names.W_OA, (W_OA) =>
           {
               W_OA.CreateNewGroup(Names.A_0656686780_OA, (A_0656686780_OA) =>
               {
                   A_0656686780_OA.CreateNewGroup(Names.EXPORT_0008EV, (EXPORT_0008EV) =>
                   {
                       EXPORT_0008EV.CreateNewGroup(Names.EXTERNAL_0008ET, (EXTERNAL_0008ET) =>
                       {
                           EXTERNAL_0008ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0008AS, FieldType.String, 1);

                           IField NUMERIC_RETURN_CODE_0008_local = EXTERNAL_0008ET.CreateNewField(Names.NUMERIC_RETURN_CODE_0008, FieldType.SignedNumeric, 2);
                           EXTERNAL_0008ET.CreateNewFieldRedefine(Names.NUMERIC_RETURN_CODE_0008XX, FieldType.String, NUMERIC_RETURN_CODE_0008_local, 2);
                           EXTERNAL_0008ET.CreateNewField(Names.TEXT_RETURN_CODE_0008AS, FieldType.String, 1);

                           IField TEXT_RETURN_CODE_0008_local = EXTERNAL_0008ET.CreateNewField(Names.TEXT_RETURN_CODE_0008, FieldType.String, 2);
                           EXTERNAL_0008ET.CreateNewFieldRedefine(Names.TEXT_RETURN_CODE_0008XX, FieldType.String, TEXT_RETURN_CODE_0008_local, 2);
                           EXTERNAL_0008ET.CreateNewField(Names.TEXT_LINE_80_0008AS, FieldType.String, 1);

                           IField TEXT_LINE_80_0008_local = EXTERNAL_0008ET.CreateNewField(Names.TEXT_LINE_80_0008, FieldType.String, 130);
                           EXTERNAL_0008ET.CreateNewFieldRedefine(Names.TEXT_LINE_80_0008XX, FieldType.String, TEXT_LINE_80_0008_local, 130);
                           EXTERNAL_0008ET.CreateNewField(Names.FILE_INSTRUCTION_0008AS, FieldType.String, 1);

                           IField FILE_INSTRUCTION_0008_local = EXTERNAL_0008ET.CreateNewField(Names.FILE_INSTRUCTION_0008, FieldType.String, 10);
                           EXTERNAL_0008ET.CreateNewFieldRedefine(Names.FILE_INSTRUCTION_0008XX, FieldType.String, FILE_INSTRUCTION_0008_local, 10);
                       });
                   });
               });
           });

        }

        protected override string GetRecordName()
        {
            return Names.LinkageSection;
        }
        #endregion

        public void SetPassedParameters(object[] args)
        {
            SetPassedParm(IEF_RUNTIME_PARM1, args, 0);
            SetPassedParm(IEF_RUNTIME_PARM2, args, 1);
            SetPassedParm(W_IA, args, 2);
            SetPassedParm(W_OA, args, 3);
            SetPassedParm(PSMGR_EAB_DATA, args, 4);
        }


        public void UpdateReturnParameters(object[] args)
        {
            SetReturnParm(IEF_RUNTIME_PARM1, args, 0);
            SetReturnParm(IEF_RUNTIME_PARM2, args, 1);
            SetReturnParm(W_IA, args, 2);
            SetReturnParm(W_OA, args, 3);
            SetReturnParm(PSMGR_EAB_DATA, args, 4);
        }
    }
    #endregion Linkage Section Class

    #region Business Logic Class
    public class SWEXEE04 : EABBase
    {

        #region Public Constructors
        public SWEXEE04()
            : base()
        {
            this.ProgramName.SetValue("SWEXEE04");

            WS = new SWEXEE04_ws();
            FD = new SWEXEE04_fd(WS);
            LS = new SWEXEE04_ls();
        }

        #endregion

        #region Private Fields


        //==== Working Storage Data Class ========================================
        private SWEXEE04_ws WS;

        //==== File Data Class ========================================
        private SWEXEE04_fd FD;

        //==== Linkage Section Data Class ========================================
        private SWEXEE04_ls LS;
        #endregion

        #region Public Methods
        //========================================================================
        //==== RunMain Entry Point Method ========================================
        //========================================================================
        public override int ExecuteMain(params object[] args)                                              //COBOL==> PROCEDURE DIVISION USING IEF-RUNTIME-PARM1 , IEF-RUNTIME-PARM2 , W-IA , W-OA , PSMGR-EAB-DATA.
        {
            try
            {
                WS.Initialize();
                LS.SetPassedParameters(args);
                RunMain();
                LS.UpdateReturnParameters(args);
                return Return_Code.AsInt();
            }
            catch (Exception ex)
            {
                Control.ReturnException(ex);
                return 12;
            }
        }
        #endregion

        #region Private Methods

        private void RunMain()
        {
            string returnMethod = "Main";
            // Execute Procedure Division Logic
            M_MAIN_0656686762(returnMethod);
        }
        /// <summary>
        /// Method M_MAIN_0656686762
        /// </summary>
        private void M_MAIN_0656686762(string returnMethod = "")
        {
            M_PARA_0656686762_INIT("M_PARA_0656686762_INIT_EXIT"); if (Control.ExitProgram) { return; }           //COBOL==> PERFORM PARA-0656686762-INIT THRU PARA-0656686762-INIT-EXIT
            M_PARA_0656686762("M_PARA_0656686762_EXIT"); if (Control.ExitProgram) { return; }                     //COBOL==> PERFORM PARA-0656686762 THRU PARA-0656686762-EXIT
            Control.ExitProgram = true; return;                                                                 //COBOL==> GOBACK.
        }
        /// <summary>
        /// Method M_PARA_0656686762
        /// </summary>
        private void M_PARA_0656686762(string returnMethod = "")
        {
            WS.FUNC_0656686762_ESC_FLAG.SetValue("N");                                                          //COBOL==> MOVE 'N' TO FUNC-0656686762-ESC-FLAG .
                                                                                                                // SWCSZE16   COPY SWCSZE16                                                                         //COBOL==> COPY SWCSZE16
                                                                                                                //COMMENT:     *******************************************
                                                                                                                //COMMENT:     *THIS CODE SWCSZE16 IS A PART OF SWEEXEE05*
                                                                                                                //COMMENT:     *OE_EAB_RECEIVE_FPLS_RESPONSE             *
                                                                                                                //COMMENT:     *******************************************
            LS.TEXT_RETURN_CODE_0008.SetValueWithSpaces();                                                      //COBOL==> MOVE SPACES TO TEXT-RETURN-CODE-0008.
            LS.NUMERIC_RETURN_CODE_0008.SetValue(ZEROES);                                                       //COBOL==> MOVE ZEROES TO NUMERIC-RETURN-CODE-0008.
            LS.FILE_INSTRUCTION_0008.SetValue(LS.FILE_INSTRUCTION_0007);                                        //COBOL==> MOVE FILE-INSTRUCTION-0007 TO FILE-INSTRUCTION-0008.
            if (returnMethod != "" && returnMethod != "M_PARA_0656686762") { M_1000_EAB_CODE_MAIN(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1000_EAB_CODE_MAIN
        /// </summary>
        private void M_1000_EAB_CODE_MAIN(string returnMethod = "")
        {
            if (LS.FILE_INSTRUCTION_0007.IsEqualTo("OPEN"))                                                     //COBOL==> IF FILE-INSTRUCTION-0007 = 'OPEN'
            {
                M_1100_OPEN_FILE("M_1100_EXIT"); if (Control.ExitProgram) { return; }                                 //COBOL==> PERFORM 1100-OPEN-FILE THRU 1100-EXIT
                M_9999_EXIT(CheckGotoReturn(returnMethod)); return;                                                 //COBOL==> GO TO 9999-EXIT
            }                                                                                                   //COBOL==> END-IF.
            if (LS.FILE_INSTRUCTION_0007.IsEqualTo("POSITION"))                                                 //COBOL==> IF FILE-INSTRUCTION-0007 = 'POSITION'
            {
                M_1200_EXTEND_FILE("M_1200_EXIT"); if (Control.ExitProgram) { return; }                               //COBOL==> PERFORM 1200-EXTEND-FILE THRU 1200-EXIT
                M_9999_EXIT(CheckGotoReturn(returnMethod)); return;                                                 //COBOL==> GO TO 9999-EXIT
            }                                                                                                   //COBOL==> END-IF.
            if (LS.FILE_INSTRUCTION_0007.IsEqualTo("WRITED"))                                                   //COBOL==> IF FILE-INSTRUCTION-0007 = 'WRITED'
            {
                M_1301_WRITE_FILE("M_1301_EXIT"); if (Control.ExitProgram) { return; }                                //COBOL==> PERFORM 1301-WRITE-FILE THRU 1301-EXIT
                M_9999_EXIT(CheckGotoReturn(returnMethod)); return;                                                 //COBOL==> GO TO 9999-EXIT
            }                                                                                                   //COBOL==> END-IF.
            if (LS.FILE_INSTRUCTION_0007.IsEqualTo("CLOSE"))                                                    //COBOL==> IF FILE-INSTRUCTION-0007 = 'CLOSE'
            {
                M_1400_CLOSE_FILE("M_1400_EXIT"); if (Control.ExitProgram) { return; }                                //COBOL==> PERFORM 1400-CLOSE-FILE THRU 1400-EXIT
                M_9999_EXIT(CheckGotoReturn(returnMethod)); return;                                                 //COBOL==> GO TO 9999-EXIT
            }                                                                                                   //COBOL==> END-IF.
            LS.TEXT_RETURN_CODE_0008.SetValue("FN");                                                            //COBOL==> MOVE 'FN' TO TEXT-RETURN-CODE-0008.
            LS.NUMERIC_RETURN_CODE_0008.SetValue(1);                                                            //COBOL==> MOVE 1 TO NUMERIC-RETURN-CODE-0008.
            M_9999_EXIT(CheckGotoReturn(returnMethod)); return;                                                 //COBOL==> GO TO 9999-EXIT.
        }
        /// <summary>
        /// Method M_1100_OPEN_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT:     OPEN OUTPUT FILE
        /// </remarks>
        private void M_1100_OPEN_FILE(string returnMethod = "")
        {
            FD.EXTFILE.OpenFile(FileAccessMode.Write);                                                          //COBOL==> OPEN OUTPUT EXTFILE.
            if (!(WS.SWCSZE19.EXTFILE_STAT.IsEqualTo(0)))                                                       //COBOL==> IF EXTFILE-STAT NOT = 0
            {
                LS.TEXT_RETURN_CODE_0008.SetValue("OP");                                                            //COBOL==> MOVE 'OP' TO TEXT-RETURN-CODE-0008
                LS.NUMERIC_RETURN_CODE_0008.SetValue(WS.SWCSZE19.EXTFILE_STAT);                                     //COBOL==> MOVE EXTFILE-STAT TO NUMERIC-RETURN-CODE-0008
            }                                                                                                   //COBOL==> END-IF.
            if (returnMethod != "" && returnMethod != "M_1100_OPEN_FILE") { M_1100_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1100_EXIT
        /// </summary>
        private void M_1100_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_1100_EXIT") { return; }                                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_1100_EXIT") { M_1200_EXTEND_FILE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1200_EXTEND_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT:     EXTEND THE OUTPUT FILE
        /// </remarks>
        private void M_1200_EXTEND_FILE(string returnMethod = "")
        {
            FD.EXTFILE.OpenFile(FileAccessMode.WriteExtend);                                                    //COBOL==> OPEN EXTEND EXTFILE.
            if (!(WS.SWCSZE19.EXTFILE_STAT.IsEqualTo(0)))                                                       //COBOL==> IF EXTFILE-STAT NOT = 0
            {
                LS.TEXT_RETURN_CODE_0008.SetValue("AP");                                                            //COBOL==> MOVE 'AP' TO TEXT-RETURN-CODE-0008
                LS.NUMERIC_RETURN_CODE_0008.SetValue(WS.SWCSZE19.EXTFILE_STAT);                                     //COBOL==> MOVE EXTFILE-STAT TO NUMERIC-RETURN-CODE-0008
            }                                                                                                   //COBOL==> END-IF.
            if (returnMethod != "" && returnMethod != "M_1200_EXTEND_FILE") { M_1200_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1200_EXIT
        /// </summary>
        private void M_1200_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_1200_EXIT") { return; }                                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_1200_EXIT") { M_1301_WRITE_FILE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1301_WRITE_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT:     WRITE DETAIL RECORD TO THE OUTPUT FILE
        /// </remarks>
        private void M_1301_WRITE_FILE(string returnMethod = "")
        {
            WS.SWCSZE19.WS_EXTERNAL_FPLS_REQUEST.SetValueCorresponding(LS.EXTERNAL_FPLS_REQUEST_0002ET);        //COBOL==> MOVE CORRESPONDING EXTERNAL-FPLS-REQUEST-0002ET TO WS-EXTERNAL-FPLS-REQUEST.
            FD.EXTFILE_RECORD.SetValue(WS.SWCSZE19.WS_EXTERNAL_FPLS_REQUEST);                                   //COBOL==> MOVE WS-EXTERNAL-FPLS-REQUEST TO EXTFILE-RECORD.
            FD.EXTFILE.WriteLine(FD.EXTFILE_RECORD.AsBytes);                                                    //COBOL==> WRITE EXTFILE-RECORD.
            if (!(WS.SWCSZE19.EXTFILE_STAT.IsEqualTo(0)))                                                       //COBOL==> IF EXTFILE-STAT NOT = 0
            {
                LS.TEXT_RETURN_CODE_0008.SetValue("WD");                                                            //COBOL==> MOVE 'WD' TO TEXT-RETURN-CODE-0008
                LS.NUMERIC_RETURN_CODE_0008.SetValue(WS.SWCSZE19.EXTFILE_STAT);                                     //COBOL==> MOVE EXTFILE-STAT TO NUMERIC-RETURN-CODE-0008
                WS.SWCSZE19.WS_RECORD_COUNT.Add(1);                                                                 //COBOL==> ADD 1 TO WS-RECORD-COUNT
            }                                                                                                   //COBOL==> END-IF.
            if (returnMethod != "" && returnMethod != "M_1301_WRITE_FILE") { M_1301_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1301_EXIT
        /// </summary>
        private void M_1301_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_1301_EXIT") { return; }                                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_1301_EXIT") { M_1400_CLOSE_FILE(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1400_CLOSE_FILE
        /// </summary>
        /// <remarks>
        ///COMMENT:     CLOSE THE OUTPUT FILE
        /// </remarks>
        private void M_1400_CLOSE_FILE(string returnMethod = "")
        {
            FD.EXTFILE.CloseFile();                                                                             //COBOL==> CLOSE EXTFILE.
            if (!(WS.SWCSZE19.EXTFILE_STAT.IsEqualTo(0)))                                                       //COBOL==> IF EXTFILE-STAT NOT = 0
            {
                LS.TEXT_RETURN_CODE_0008.SetValue("CL");                                                            //COBOL==> MOVE 'CL' TO TEXT-RETURN-CODE-0008
                LS.NUMERIC_RETURN_CODE_0008.SetValue(WS.SWCSZE19.EXTFILE_STAT);                                     //COBOL==> MOVE EXTFILE-STAT TO NUMERIC-RETURN-CODE-0008
            }                                                                                                   //COBOL==> END-IF.
            if (returnMethod != "" && returnMethod != "M_1400_CLOSE_FILE") { M_1400_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_1400_EXIT
        /// </summary>
        private void M_1400_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_1400_EXIT") { return; }                                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_1400_EXIT") { M_9999_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_9999_EXIT
        /// </summary>
        /// <remarks>
        ///COMMENT:     PLEASE NOTE THAT THIS IS OF THE USER WRITTEN CODE
        ///COMMENT:     THIS EXIT FUNCTIONS AS AN EXIT/RETURN.
        ///COMMENT:     CONTROL JUST FALLS THRU
        /// </remarks>
        private void M_9999_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_9999_EXIT") { return; }                                                      //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_9999_EXIT") { M_PARA_0656686762_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0656686762_EXIT
        /// </summary>
        private void M_PARA_0656686762_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0656686762_EXIT") { return; }                                           //COBOL==> EXIT.
            if (returnMethod != "" && returnMethod != "M_PARA_0656686762_EXIT") { M_PARA_0656686762_INIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0656686762_INIT
        /// </summary>
        private void M_PARA_0656686762_INIT(string returnMethod = "")
        {
            LS.EXPORT_0008EV.ResetToInitialValue();                                                             //COBOL==> INITIALIZE EXPORT-0008EV .
            if (returnMethod != "" && returnMethod != "M_PARA_0656686762_INIT") { M_PARA_0656686762_INIT_EXIT(returnMethod); }  //Check for pass through to next method
        }
        /// <summary>
        /// Method M_PARA_0656686762_INIT_EXIT
        /// </summary>
        private void M_PARA_0656686762_INIT_EXIT(string returnMethod = "")
        {
            if (returnMethod == "M_PARA_0656686762_INIT_EXIT") { return; }                                      //COBOL==> EXIT.
        }
        #endregion
    }
    #endregion
}
